### ISSUE TITLE
nsurlstoraged console error

### ISSUE THREAD

**Issue by galli-a** [felixhageloh/uebersicht#100]
In the console log I see repeated messages like

    25/04/15 09:28:55,615 nsurlstoraged[43443]: ERROR: shrinkDB - shrink of file system cache did not fully complete.  Result: 11

that stop as soon as I quit Übersicht. If my testing is correct, this happens at each refresh interval, for any widget containing a command.

I don't see any issue in the Übersicht console.

Any ideas?

**Comment by felixhageloh** [comment]
Interesting - do you notice any other side effects?

**Comment by galli-a** [comment]
No, everything works fine

**Comment by baberthal** [comment]
I see it too, and it's accompanied by 
```
nsurlstoraged[452]: Error: stepSQLStatement:toCompletionWithRetry - stepping returned unhandled result=11, DB=~/Library/Caches/tracesOf.Uebersicht/Cache.db
```
No other side effects. Just thought I'd let you know.

**Comment by chrismetcalf** [comment]
:+1:, I'm seeing the same thing...

**Comment by felixhageloh** [comment]
I think you can safely remove this file `/Library/Caches/tracesOf.Uebersicht/Cache.db`
It seems that sometimes the cache gets corrupted

**Comment by chrismetcalf** [comment]
Looks like it worked for me. Two things:

1. It's actually in `~/Library` not `/Library`
2. It's probably good to shut down Uber first. It got very unhappy when I deleted `Cache.db` out from underneath it, but a restart fixed it.

**Comment by galli-a** [comment]
This solves it for me as well
