### ISSUE TITLE
Feature: Choose active widgets

### ISSUE THREAD

**Issue by soberstadt** [felixhageloh/uebersicht#11]
It might be cool to add a UI for widget selection. Maybe move the `.widget` folder to/from a widget-bin folder or something.

**Comment by felixhageloh** [comment]
This is now possible in version 0.8, although it is a bit cumbersome. In the screens menu of a widget you can first select a display in the 'Show on selected screens section' and then uncheck all screens from the list. This essentially sets the widget to display on no screen, which is the same as hiding it. 

I will see if the UX of this can be improved in the future. Suggestions welcome!
![screen shot 2016-02-23 at 10 54 35](https://cloud.githubusercontent.com/assets/367503/13247900/13f58cfa-da1c-11e5-9a7c-77350829c559.png)
