### ISSUE TITLE
curl result always sent to widget

### ISSUE THREAD

**Issue by tiptronic** [felixhageloh/uebersicht#110]
I am querying a REST-API using curl (see below). The problem is, that when curl returns, it's output is always sent to my widget. That's what I do (yes - I prefer Javascript, as it's much better readable):

command: "curl -i --user xxx:yyy  http://myIP/json/somejson",

refreshFrequency: 1000000,

render: function(output) {
        return "";
}

Any idea?
OSX 10.10.3, latest Safari (release version)

**Comment by felixhageloh** [comment]
Yeah it is a common issue with curl. It uses stderr to display progress information, but Übersicht treats anything sent to `stderr` as an actual error. Luckily there is the `-s` flag for curl, which suppresses the progress message (and anything sent to stderr). If you still want to receive actual errors that happen you can use it in combination with `-S` which enables errors again. 

Long story short: Use `-sS` along with curl, so the whole command becomes:

```
command: "curl -sS -i --user xxx:yyy http://myIP/json/somejson",
```

**Comment by felixhageloh** [comment]
been inactive for a long time, closing for now
