### ISSUE TITLE
Unable to use any widgets downloaded from http://tracesof.net/uebersicht-widgets/

### ISSUE THREAD

**Issue by TheLittleTurkey** [felixhageloh/uebersicht#112]
I've tried moving many folders that end in .widget that I've downloaded from http://tracesof.net/uebersicht-widgets/ and I always get a similar error (the only difference in the error from widget to widget is the number after stylus:). 

I'm using a 2012 macbook pro retina, if that helps.

![screen shot 2015-06-24 at 3 12 54 pm](https://cloud.githubusercontent.com/assets/13039401/8340947/730fb968-1a87-11e5-8bf1-3b6184d6739a.png)

**Comment by TheLittleTurkey** [comment]
This is the OP. All I had to do was quit the app and reopen it and now it's working fine. Hopefully this info was useful to the developer.

**Comment by felixhageloh** [comment]
glad this got resolved! I've heard similar issues before, but not quite sure what could be causing it
