### ISSUE TITLE
Can server be made to bind/listen to *only* localhost/127.0.0.1?

### ISSUE THREAD

**Issue by jps3** [felixhageloh/uebersicht#115]
I would like to be able to ensure that Uebersicht _only_ listens on 127.0.0.1:${port} and not *:${port}. For the machines I'd like to use it on in my labs, I cannot have service ports open and listening like that. (We have zero need for any "non-localhosts" to connect to Ubersicht on any other host, and would prefer the peace of mind that it's not accepting incoming public connections.)

Is there a way to do this? I have looked through the source code to see if I could find anything obvious, but my ignorance of Node.js and weak Objective-C skills were not much help.

Perhaps there is some means to do this already? (If so, apologies if I missed this.) Alternatively, if anyone can tell me what file and line(s) this is controlled in, I would be happy to see if I can figure it out and issue a pull request.

Thank you.

**Comment by felixhageloh** [comment]
in `server/src/app.coffe` line 20:

```coffeescript
  .listen port, ->
    console.log 'server started on port', port
    widgetDir.watch changesServer.push
```

If you change that to `.listen port, '127.0.0.1', ->` I think it will do the trick. 
I think you are right, there is no need to accept requests from outside. The only neat thing right now is that you can use your browser to see widgets running on a different machine, but I guess that is not really a use case.

**Comment by jps3** [comment]
1. If I edit server.js in your supplied (and signed) app bundle, adding '127.0.0.1' seems to do the trick.
2. I have been trying to build from source, and while I've finally gotten it to build, regardless of whether it’s Debug or Release, I keep getting this: `error: Cannot find module './build/Release/fse'`
    _I will keep trying to figure this out as time allows, but hopefully there's an obvious fix. I did search the issues but didn't find anything obvious (to me), perhaps due to my ignorance of Node I didn't use quite the right keywords?_
