### ISSUE TITLE
Doesn't start up

### ISSUE THREAD

**Issue by the-wilhelm** [felixhageloh/uebersicht#116]
I have downloaded the app and tried to open it.  It acts like it is opening but then nothing happens. Also when I try to delete the app it tells me now that it can't move it to trash because the app is running but its not in my force quit list.  I am running on OS X 10.10.3.  Thank you.

**Comment by felixhageloh** [comment]
Do you see the 'ü' icon in your menu bar? That means the app is running (and you can also quit it using the menu).
