### ISSUE TITLE
How to access data from using @run

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#117]
I have a line in the update function like this:

@run("/Users/mikecampbell/doit.pl", $(domEl).find('.conditions').html('xxx'))

I would like to take the output from the doit.pl script and use it as the text for the conditions div I have setup. How would I do this?

The bigger picture here is that I want to combine the output from 3 different scripts into a single widget. I have a render set line this:

render: -> """
  <div class="weather-container">
  <div class="conditions"></div>
  <div class="time"></div>
  <div class="forecast"></div>
  </div>
"""

I can display the time just fine but I need to call 2 other scripts for the conditions and the forecast. How do I call these scripts and use the output in the widget?

**Comment by felixhageloh** [comment]
If I understand your question correctly, you could do:

```
render: -> """
  <div class='conditions'></>
"""

afterRender: ->
  @run("/Users/mikecampbell/doit.pl", $(domEl).find('.conditions').html('xxx'))
```

**Comment by mlcampbe** [comment]
Thanks Felix, that resolved my issue. I would have never figured that part out from the docs. You may want to add this as an example for future reference.
