### ISSUE TITLE
Subfolder javascript files give ubersicht errors

### ISSUE THREAD

**Issue by zanderp** [felixhageloh/uebersicht#120]
Can we work @ a fix at least to exclude folders like js or scriptd from Ubersicht widget search so it won't give errors on files in those folders?

**Comment by felixhageloh** [comment]
Yeah ideally the search should be more strict, but I am worried it would break some older widgets that might rely on this behaviour

**Comment by zanderp** [comment]
Then we should update those widgets, or ask the authors to do it. Because we need this new version of Ubersicht with this filter. For example one of my widgets have a JS folder and when I start the program I get a lot of errors and sometimes the program kills itself.

**Comment by felixhageloh** [comment]
I'm guessing you want a folder with js files for external modules?

**Comment by zanderp** [comment]
Something like that. See the note widget I posted.

**Comment by felixhageloh** [comment]
I see - yeah that will require some more work in general. I have some prototypes that work with CommonJS but it would also drastically change the way widgets are written, so I am thinking of  releasing this as a V2 (once I have some more time again)

**Comment by felixhageloh** [comment]
this should be fixed now - javascript files inside folders called `lib` `src` or `node_modules` are ignored
