### ISSUE TITLE
Get value .on() click and run a command ?

### ISSUE THREAD

**Issue by jacksonfylle** [felixhageloh/uebersicht#126]
Hello,
To explain my probleme, here is an example:

```html
<button id="Movies">Movies</button>
```
```coffeescript
$(domeEl).on 'click', "#button", -> @innerHTML
```
@innerHTML = Movies for exemple

I wish to get the value of the button and directly run a command like = @run "open ~/<getvalue>"

something like :
$(domeEl).on 'click', "#button", -> @run "open ~/" + @innerHTML

but i think we need to use the fat arrow => probleme if we use the fat arrow @innerHTML doesn't work any more.

any solution ?

## EDIT

```coffeescript
$(domEl).find('#execute button').on
    click: ->
        alert @innerHTML
        return
    click: =>
        @run "open ~/" + @innerHTML
        return
```
Both handlers won't execute. And i already try to get @innerHTML in a var but won't work.
anonymous function ? 

Sorry i'm pretty bad in javascript, coffee...

## EDIT
Everything good
$(domEl).find('#execute button').on 'click', => @run "open ~/" + event.target.id

**Comment by felixhageloh** [comment]
looks like you figured it out :+1:
