### ISSUE TITLE
I/O errors with top-cpu and top-mem widgets in El Capitan (10.11)

### ISSUE THREAD

**Issue by gboudreau** [felixhageloh/uebersicht#129]
Those errors repeat about 2-3 times a minute, on either widget, and fixes itself on next refresh.

Debug console:
<img width="758" alt="uber error 10 11 console" src="https://cloud.githubusercontent.com/assets/370329/10117180/fbec0088-641b-11e5-9598-e02d7547ec79.png">

Video:
http://cl.ly/1O1H0G1p040m

Any idea how to fix this? Or how I can update the widgets scripts so that when it happens, the widget is not refreshed (i.e. what can I put in the `update` function to not change the current widget UI?)

**Comment by gboudreau** [comment]
For now, I have added `2>/dev/null` after the awk and sort commands in those scripts; it seems to have fixed the issue.

**Comment by felixhageloh** [comment]
I just merged a pull request which will probably solve this issue
