### ISSUE TITLE
`geolocation.getCurrentPosition` not working

### ISSUE THREAD

**Issue by zhugexiaobo** [felixhageloh/uebersicht#138]
[authentic-ubersicht](https://github.com/reduxd/authentic-ubersicht) widget in 10.11.1 shows nothing, it seems `geolocation.getCurrentPosition ()` not called back, and system didn't show location service alert as well.

So, @felixhageloh can u help to look into this please.

**Comment by felixhageloh** [comment]
I had a quick check and `geolocation.getCurrentPosition()` seems to be working - can you confirm that this is the issue?

**Comment by zhugexiaobo** [comment]
Can you check [this code](https://github.com/reduxd/authentic-ubersicht/blob/master/authentic.widget/authentic.coffee#L47-L53) out? 
I found the issue by this widget.
Thanks for your time.

**Comment by felixhageloh** [comment]
I tried following code

```coffeescript
geolocation.getCurrentPosition (e) =>
  coords = e.position.coords
  [lat, lon] = [coords.latitude, coords.longitude]
  console.log lat, lon
```

and I seem to get valid `lat` and 'lon` values. I also tried the authentic weather widget (great widget, isn't it :) ) and it appears to work for me. 
Did you see any errors in the console? Maybe you had an issue with forecast io (wrong api key or they service was down or something like that)

**Comment by zhugexiaobo** [comment]
I checked again, it just worked for somehow.
The location service icon didn't show in the status bar before then, now it does work.
anyway, thanks for your help and Übersicht is cooooool!
