### ISSUE TITLE
Modifier-less clicks

### ISSUE THREAD

**Issue by skonesam** [felixhageloh/uebersicht#139]
Need the option to make clicks REQUIRE a modifier! I have a stock ticker at the bottom of my screen, which catches clicks on my dock (normally hidden). Already accidentally opened a few tabs with the local weather radar, too… not even sure how that happened, but it did.

**Comment by skonesam** [comment]
Figured out how the weather radar opened – Übersicht is registering clicks *no matter what is in front of it.* Tweetbot, Messages, whatever. Pretty sure that's not what you had in mind. :smile:

**Comment by TRMman** [comment]
I see the same here, can't use ctrl-click on the trackpad anymore. Restored the previous version of Übersicht.

**Comment by felixhageloh** [comment]
No indeed, that's not what I had in mid (that's why I used the modifier key before)! I thought I had figured out a solution but it appears not always to be working

**Comment by felixhageloh** [comment]
Just released an update that should fix this! Let me know if it is working for you

**Comment by gregorylebaron** [comment]
I just installed 0.6 (19) on Yosemite. When I right click on the desktop, two menus show up for an instant and then disappear, the expected desktop menu and a "Reload, Inspect Element" menu that seems to be coming from the taskbar.

Same thing when I right-click on a desktop icon.

**Comment by felixhageloh** [comment]
sounds like Issue #141 as well

**Comment by felixhageloh** [comment]
I've just released a new version (0.6.20) that should fix the right-click issue

**Comment by TRMman** [comment]
Hi Felix, I installed this new version and the problem with the right-click disappeared.  

Hartelijk dank voor de fixes en voor Übersicht.

**Comment by felixhageloh** [comment]
Great to hear, thanks!
