### ISSUE TITLE
Widgets stopped updating

### ISSUE THREAD

**Issue by gboudreau** [felixhageloh/uebersicht#14]
Port 41416 is still active, and receives requests.
I tried loading one of the widget's URL in my browser, and that works (it returns up to date data).
But my widgets, namely the default mem and cpu widgets, have been stuck for a while, showing very old data.

Let me know what I should try, to identify the issue.
I won't touch anything.

![screen shot 2014-06-19 at 15 42 38](https://cloud.githubusercontent.com/assets/370329/3332676/183e8412-f7ea-11e3-9881-dd127d96a6dc.png)

**Comment by felixhageloh** [comment]
Is this still an issue since updating to WKWebView (a few versions back)? Please re-open if so

**Comment by gboudreau** [comment]
I don't think it is still an issue. Been quite a while since I got any issue with this.

**Comment by Porco-Rosso** [comment]
Having this issue, I'm simply executing a script once per second and after a few minutes the widget stops refreshing.

**Comment by felixhageloh** [comment]
@Porco-Rosso are there any errors in the console?

**Comment by Porco-Rosso** [comment]
Nope, nothing. Don't know where to start troubleshooting because of that.
For reference here is the widget I am trying to work on that stops refreshing. 
[BeardedSpice.widget.zip](https://github.com/felixhageloh/uebersicht/files/832249/BeardedSpice.widget.zip)
Is there a limit to the number of times a script can be run?

**Comment by felixhageloh** [comment]
@Porco-Rosso (sorry for the late reply). There is no limit to the amount of times a script can run. However, it could be that the script your are running gets stuck and Übersicht will patiently wait for it to return something.

**Comment by Porco-Rosso** [comment]
@felixhageloh Thanks for getting back to me.
How should I address this? wrap my entire script in a try/on error ? 
Is there a timeout in widget via Beardedspice I could implement?

**Comment by felixhageloh** [comment]
@Porco-Rosso I think there is nothing you can do on the widget side, so you would have to add the error checking or timeouts to your script itself, yeah
