### ISSUE TITLE
Ubersicht modifier key

### ISSUE THREAD

**Issue by jacksonfylle** [felixhageloh/uebersicht#142]
Hello, i'm using Ubersicht since 6 months or more and suddenly i can't interact any more with my widget.
Also the menu where we could change the modifier key is gone .

Is it normal ? i think this append after the new version of ubersicht. 6.20.

Thanks.

**Comment by felixhageloh** [comment]
The modifier keys have been deprecated in v0.6 and instead widgets should be always clickable. Obviously it is not working for you, though. Do you have multiple screens by any chance?

**Comment by jacksonfylle** [comment]
yes i have two screens.
I've unplug my second screens, relaunch and refresh and it's work again.
Only the click button. 
I still can't scroll my pages any more.
Can i still get the last release who use the modifier key (5.9.xx) ?

![demo](https://raw.githubusercontent.com/jacksonfylle/Ubersicht/master/UbersichtSlow.gif)

**Comment by felixhageloh** [comment]
I'v found (and fixed) and issue with clicking on multiple screens, which I will release it shortly. 
Scrolling is a use case I had not taken into account - I will see if it is fixable as well! 
In the meantime, here is a link to v0.5 http://tracesof.net/uebersicht/releases/Uebersicht-0.5.app.zip

**Comment by dwitscher** [comment]
I’ve noticed that i can’t select text in a widget with the newest version. this works fine with the old modifier key method.

**Comment by soberstadt** [comment]
@felixhageloh it looks like people have come up with some pretty creative ideas for widgets going way beyond that basic stuff I do. This is sweet you've made something people are being so creative with! Just a bummer that you didn't know people were doing this stuff when you changed the feature.

**Comment by felixhageloh** [comment]
@dwitscher you can enable text selection by adding

```css
user-select: text
```

to the style of the widget in question. It is something I need to add to the Readme still

**Comment by felixhageloh** [comment]
@soberstadt I hear ya. I knew this was a risky change, but the only way to find out what would break was to release it. I feel it is very beneficial to 90% of the use cases out there, tho, and with a bit of luck I can also make it work for most of the remaining edge cases.

**Comment by felixhageloh** [comment]
I've decided to park this for now and reverted to using shortcut keys in v0.7 (released today). You can read more about it here http://tracesof.net/. 
Sorry for the issues it caused!
