### ISSUE TITLE
screen flicker on wallpaper change

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#143]
I created a simple widget that runs runs a perl script to generate an image that I wish to use as a desktop wallpaper background. The command runs every 5 minutes and updates my wallpaper.png file which I then display using a widget. However, I am finding that everytime the wallpaper changes the entire screen refreshes and I can see it remove the old/current wallpaper so that the OSX wallpaper is visible for a half second and then the new widget wallpaper is displayed. I am trying to find a way to prevent this "flash" refresh. I also notice the same thing if I change the OSX desktop space.

Any ideas on how to eliminate this with some type of CSS tricks?

**Comment by TRMman** [comment]
I'm afraid I don't have a solution. I see the same here on my display when a 175x175 picture is being refreshed.

**Comment by felixhageloh** [comment]
Not sure if this will fix the flash when you switch spaces, but it should definitely prevent flashing when a new wallpaper loads:

The trick is often called double buffering, which essentially means that you keep showing the old wallpaper until the new one has completely loaded. One way way of doing that would be to draw the new wallpaper behind the current one and then fade out the old one as soon as the `onload` event of the new one triggers.

Let me know if this helps, otherwise I can give a more detailed explanation!

**Comment by mlcampbe** [comment]
Felix,

I have tried something like that and had some success. In my case here is the code I am using:

update: (output, domEl) ->
  if (this.which == 1)
    $(domEl).find('.img1').css content: "url('teawallpaper.widget/wallpaper.png')"
    $(domEl).find('.img1').css display: "none"
    $(domEl).find('.img2').css display: "block"
    this.which = 2
  else
    $(domEl).find('.img2').css content: "url('teawallpaper.widget/wallpaper.png')"
    $(domEl).find('.img2').css display: "none"
    $(domEl).find('.img1').css display: "block"
    this.which = 1

However, this basically switches the wallpaper 1 cycle behind what I need it to do meaning that the currently generated wallpaper is generated in the display:none element and not visible until the 5 min refresh occurs.

If you have some other samples of using the onload and fading out the old wallpaper that would be a great help.

Mike Campbell
BDE Support Engineer, Oracle Access Manager
Decatur, Alabama 35601 USA
Telephone: +1.407.458.2313 | Email: mike.campbell@oracle.com

**Comment by felixhageloh** [comment]
Here is one example without a fade which just requires one image in the DOM, but it might just work:

```coffeescript
update: (_, domEl) ->
  image = $(domEl).find('.wallpaper')
  buffer = document.createElement('img')
  
  buffer.onload = -> 
    image.css content: "url('#{buffer.src}')"
  
  buffer.src = 'teawallpaper.widget/wallpaper.png'
```

**Comment by mlcampbe** [comment]
I gave it a try this morning but still see a screen flicker when the wallpaper changes. I have uploaded a quick screen recording to show the outcome at http://cl.ly/2c1W362B2O0d. The refresh is every 10 seconds so you will see it flicker at about 7 seconds and 17 seconds into the video. Perhaps I still need the double buffering techinque. If you or anyone else has an example to show that would be great.

**Comment by felixhageloh** [comment]
Sorry I finally had time to check this again. I had a typo in my code, it should be:

``` coffeescript
update: (_, domEl) ->
  image = $(domEl).find('.wallpaper')[0]
  buffer = document.createElement('img')

  buffer.onload = -> 
    image.src = buffer.src

  buffer.src = 'teawallpaper.widget/wallpaper.png'
```

The code is not the most efficient btw, but just to demonstrate the principle

**Comment by felixhageloh** [comment]
closing for now - let me know if you still have issues with this.
