### ISSUE TITLE
error running command with escaped (\")

### ISSUE THREAD

**Issue by ServeR00T** [felixhageloh/uebersicht#144]
```
disk = 'disk0'
delay = '1'  #seconds

command: "iostat -dw #{delay} -c 2 #{disk} | awk 'FNR>3' | awk '{printf \"%s,%s,%s\",$1,$2,$3}'"
```
as you wrote it's ok but it isn't at least with my macbook air it shows "error running command"

**Comment by hawkrives** [comment]
You could try using triple-quotes around `command`… that would allow you to not need to escape the double-quotes inside the string.

This is what I'm thinking:

```coffee
disk = 'disk0'
delay = '1'  #seconds

command: """iostat -dw #{delay} -c 2 #{disk} | awk 'FNR>3' | awk '{printf "%s,%s,%s",$1,$2,$3}'"""
```

**Comment by felixhageloh** [comment]
closing this for now. Let us know if you still have this issue
