### ISSUE TITLE
The application closes suddenly

### ISSUE THREAD

**Issue by ivallesp** [felixhageloh/uebersicht#145]
Hello,

I have a problem with Ubersicht. I configured all the plugins I like and they are running normally but suddenly, sometimes, the application is closed. How can I debug it? Is it a bug?

Thank you,
Iván

**Comment by tragicdog** [comment]
I have to do a little digging, but for me I think it's happen when I click on one of my widgets and then accidentally hit cmd+w. saw it close last night, other times it's just been randomly off.

**Comment by felixhageloh** [comment]
I can see how cmd+w would close Übersicht. That's probably something easily fixable.
For the rest, you guys can open the Console app (comes with OS X) and see if you see any crash reports related to Übersicht there
