### ISSUE TITLE
Refresh widget when link is clicked

### ISSUE THREAD

**Issue by agileadam** [felixhageloh/uebersicht#147]
I'd love to have a "Refresh" link (or icon) that, when clicked, would refresh the widget. Is this possible?

I know you can already embed links in your widget and they open the link in your browser when you CMD-click them.

I tried embedding a link that, when clicked, would execute update(), but I end up seeing all of my widgets in a new browser window.

Thanks!

**Comment by RywesTech** [comment]
In the uebersicht menu you can click on "Refresh All Widgets". This should fix your problem, or are you talking about something else?
![screen shot 2015-12-14 at 3 43 56 pm](https://cloud.githubusercontent.com/assets/10003122/11797687/bc83ab7a-a279-11e5-9a76-2728a423fca2.png)

**Comment by agileadam** [comment]
That's not quite what I was getting at.
I'd like to build, into my widget, a refresh icon that I can click to refresh the widget's output (or just a div within the output).

Basically it refreshes every 30 seconds but I'd like the option to refresh it sooner (without refreshing all other widgets).

**Comment by felixhageloh** [comment]
@agileadam I'm working on some other feature right now that would probably make this easily possible!

**Comment by agileadam** [comment]
Felix, that sounds awesome! Thanks :)

**Comment by d-4-ni** [comment]
For now I'm using this:

```coffeescript
afterRender: (domEl) ->
  that = this

  $(domEl).find('.refresh').click (e) ->
    e.preventDefault()
    that.refresh()
```

**Comment by agileadam** [comment]
Ooh! This looks good. I'll try it.
Thanks!

**Comment by felixhageloh** [comment]
nice one!

Small tip - in case this is not intentional - you can use CoffeeScript's fat arrow to bind `this`:
```coffeescript
afterRender: (domEl) ->
  $(domEl).find('.refresh').click (e) =>
    e.preventDefault()
    this.refresh()
```

and if you don't care about preventDefault, this should even work:

```coffeescript
afterRender: (domEl) ->
  $(domEl).find('.refresh').click(this.refresh)
```

**Comment by d-4-ni** [comment]
Yeah, forgot about the fat arrows, thanks!
...but then again, you never need to write `this` here...

```coffeescript
afterRender: (domEl) ->
  $(domEl).find('.refresh').click(@refresh)
```

**Comment by d-4-ni** [comment]
After thinking again, your short form will probably not work, because the refresh method isn't bound to the correct object at call time.
I did forget about the fat arrow though, thanks!

**Comment by felixhageloh** [comment]
Your thinking is correct - it is just that for the widget internals I use closures instead of relying on `this`. So the retry method does not need to be bound to an object to work correctly. All its internal state is inside a closure

**Comment by d-4-ni** [comment]
Oh, I guess it _should_ work correctly. But I just noticed that without the `.bind(this)` a new refresh cycle starts instead of restarting the current one.
Will create a separate issue for that.

**Comment by felixhageloh** [comment]
Oh, odd - good catch, thanks!

**Comment by d-4-ni** [comment]
The behavior is not related to the missing instance. So you were fully correct here :)

**Comment by felixhageloh** [comment]
There is another way to do this now as well, by using this command:
``` 
osascript -e 'tell application "Übersicht" to refresh widget id "my-widget"'
```

check the readme section about Scripting Support for more details (and how to get the `Ü` right)
