### ISSUE TITLE
[Feature Request] Option to have (or not to have) widgets always clickable .

### ISSUE THREAD

**Issue by RywesTech** [felixhageloh/uebersicht#149]
Hello,

When v0.6 came out I was very excited that widgets were always clickable and it helped me very much. I know that in v0.7 you have reverted it back to the modifier key option only. I think that it would be a good to allow the user to have it always clickable OR with a modifier key. That way if the user needs a modifier key, they can use if and if they do not want a modifier key, they can completely remove it.

Thanks, Ryan.

**Comment by felixhageloh** [comment]
Glad to hear that some people actually appreciated the troubled 0.6 release :).

I like your suggestion - the main issue is that I could find a way to get it working without any negative side effects. The final two issues remaining were that it could interfere with Mission Control and that clicks sometimes just stopped working (until you restarted the app). 

If I'm able to find a solution at some point I will probably release it as an optional feature as you suggested!

**Comment by felixhageloh** [comment]
btw I will close this issue because it is on my radar so I don't need an extra reminder. Trying to keep the list of open issues a bit shorter than I did in the past :)
