### ISSUE TITLE
FAQ?

### ISSUE THREAD

**Issue by mspreij** [felixhageloh/uebersicht#150]
I have a bunch of ideas for widgets but more questions, is there more detailed documentation somewhere, or a directory of simple examples (other than the widget gallery - while interesting to browse code after downloading some, it's not the best way to learn specific things), also in JavaScript?
Things I'd look for are best way to store variables, reserved function names, when to use command vs update+run vs refresh=false/setTimeout vs ..., etc. An irc channel or similar would be nice :-)
Does that make sense?

**Comment by felixhageloh** [comment]
better late than never, but I've opened a #uebersicht IRC channel on irc.freenode.net
