### ISSUE TITLE
Finding location of Widget Folder for custom script

### ISSUE THREAD

**Issue by zsugiart** [felixhageloh/uebersicht#151]
Hi, 

I have a python script in the same folder as index.coffee - how do I call it without hardcoding it's path?
is there a way of calling the script relative to the location of index.coffee?

When I use $PWD, I realized that it is set to the /Users/<username>/Library/Application. 
I'm hoping there's a variable set when the widget is initiated, and it points to the location of where the index.coffee is.

like $PWD, but relative to Ubersicht widget scope, something like:
command: "python $UB_PWD/run.py"

Where $UB_PWD points to the directory where that index.coffee is located when it is loaded by Ubersicht?

Regards
Zen

**Comment by felixhageloh** [comment]
You can use a path relative to your widgets folder (i.e. were all your widgets live). So if your widget is in a folder called my-widget, you can call `python my-widget/run.py`

**Comment by zsugiart** [comment]
Hi felix,

Yep I figure it out, my widget is going along pretty good actually!!

On Mon, Jan 4, 2016 at 4:44 PM, Felix <notifications@github.com> wrote:

> You can use a path relative to your widgets folder (i.e. were all your
> widgets live). So if your widget is in a folder called my-widget, you can
> call python my-widget/run.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixhageloh/uebersicht/issues/151#issuecomment-168604272>
> .
>



-- 
Regards,
Zen

**Comment by felixhageloh** [comment]
:+1:
