### ISSUE TITLE
uebersicht seems not respect the current locale

### ISSUE THREAD

**Issue by simo2409** [felixhageloh/uebersicht#152]
I'm running uebersicht as a user which has setup italian as system locale but when I put in command something "localeable" (like `date '+%A %d %B %Y'`) I get the english version instead of the italian one.

For example, running `date '+%A %d %B %Y'` in terminal I get: "Lunedì 28 Dicembre 2015" (italian)
Running che same command in a uebersicht widget I get: "Monday 28 December 2015" (english)

How can I get the localized output in uebersicht?

Thank you very much, this project is amazing!

**Comment by felixhageloh** [comment]
I will have a look how the locale is passed to the terminal and why that is not the case for Übersicht. I believe there are a few related issues that also come down to some system env not being set.
Thanks for reporting!

**Comment by nueh** [comment]
As a workaround use: `command: "LC_TIME='it_IT.UTF-8' date +'%a %d'"`

**Comment by simo2409** [comment]
:+1: @nueh thanks

**Comment by felixhageloh** [comment]
in version 1.2.48 you can now enable 'load Bash env' in preferences. Your locale should be set afterwards
