### ISSUE TITLE
use @import or @require in style

### ISSUE THREAD

**Issue by krid78** [felixhageloh/uebersicht#153]
Hi,
 
I'd like to use `@require` in in my style definition to include several common settings (mainly color definitions) in all of my widgets. Unfortunately, I can't get it to work.

If I use a absolute path to my .styl file, I don't get any error message, but the file is simply ignored. If I try a relative path, I always end up with an error `failed to locate @require file …`. I tried several ways.

Is there a way to use a common .styl file across widgets, or at least include a common definition (so I can maintain such file in one place and copy it to all of my widgets after changing it)?

**Comment by felixhageloh** [comment]
sorry for the late response - I did not have time yet to properly look into this. 
As you mentioned, an absolute path works and I think if you use a relative path to the _Widgets Directory_, so not your widget but the folder were all widgets live, it should work as well.

You then say the file just gets ignored. Is that because you don't see the styles applied correctly or do you not even see the style rules when you check in the debug console?

**Comment by krid78** [comment]
This time I have to excuse for the high latency ...
Having the styl-file in my base folder containing all widgets, I tried the following:
* `@import(colors-base16-solarized)` - failed to locate `@import` file `colors-base16-solarized.styl`
* `@import("<full path to>/colors-base16-solarized")` - No error, but styles not applied. I don't see them when I inspect the elements in the debug console.

Having the styl-file in my widgets folder, I tried the following:
* `@import("TopRamProcesses.widget/colors-base16-solarized.styl")` - failed to locate `@import` file `colors-base16-solarized.styl`

**Comment by felixhageloh** [comment]
I had  a quick look and it seems it is something that will require some tinkering to get to work properly. The problem is that I manually scope the styles inside the style definition, so the styles that are included via the @import get an extra widget-id in front of them.

**Comment by venkatperi** [comment]
Adding the import to the render fragment seems to work:
```
render: (output) ->
  """
<style>
  @import url(twitterStream.widget/font-awesome/css/font-awesome.css);
</style>
<table class="table" id="tweets">
  <tbody>
    <tr>
    </tr>
  </tbody>
</table>
"""
```
