### ISSUE TITLE
Random crashes since updating to v0.7

### ISSUE THREAD

**Issue by ChiefPoints** [felixhageloh/uebersicht#156]
Hello,

I'm experiencing random crashes since updating to v0.7. I haven't noted any specific action that causes the crashes, as they occur while the computer is not in use. I'm running OSX 10.11.2 and version 0.7 of Übersicht. See logs. 
[Übersicht_2016-01-19-101117.txt](https://github.com/felixhageloh/uebersicht/files/97060/Ubersicht_2016-01-19-101117.txt)

**Comment by felixhageloh** [comment]
Hi thanks for reporting. The crash log looks very similar to https://github.com/felixhageloh/uebersicht/issues/69 so I will close this one as a duplicate

**Comment by ChiefPoints** [comment]
Strange, since I never experienced any crashes until this last update - was fine through the .4 - .6 versions covered in the threads.

**Comment by felixhageloh** [comment]
Interesting. Is there a chance that you've added a new widget around the same time you upgraded to 0.7?

**Comment by ChiefPoints** [comment]
Nope, running the same widgets and settings that I've run for the last couple of years.
