### ISSUE TITLE
LOW PRIORITY: The link to nib library in README.me is broken

### ISSUE THREAD

**Issue by GavinJS** [felixhageloh/uebersicht#157]
nib library has moved to: https://tj.github.io/nib/

**Comment by hawkrives** [comment]
I made a PR! 
… Sorry, I should have asked if you wanted to make one, first. :disappointed:

**Comment by GavinJS** [comment]
@hawkrives no that's totally ok.  I don't have this repo forked anyway so wouldn't have been able to do one easily...  Unless there is another way I'm not aware of without having a fork?

**Comment by felixhageloh** [comment]
merged the PR, thanks guys!
