### ISSUE TITLE
Anchor link click support

### ISSUE THREAD

**Issue by yhbyun** [felixhageloh/uebersicht#16]
I made a widget including some html anchor link tag. They display well with underline link, but nothing happens when I click the link. It would be nice if the link click is supported.

**Comment by willmapp** [comment]
I tried adding support for a clickable link, but it isn't working properly.

I can click the link but the URL resolves to: http://127.0.0.1:<port>/%7Dhref%7D

Here's the code I'm attempting to reuse.

href = http://<somesite>.com, but doesn't get replaced properly. I've tried a couple of different things and just can't get it to work.

Thoughts?

for e in result.responseData.feed.entries
        localdate = new Date(e.publishedDate)
        localdate = localdate.toLocaleDateString()
        href = e.link
        #$ev.append('<div class="title">')
        #$ev.append('<a href=')
        #$ev.append('\"')
        #$ev.append(e.link)
        #$ev.append('\"')
        #$ev.append('>')
        #$ev.append(e.title)
        #$ev.append('</a></div>')
        $ev.append('<div class="title"><a href="#{href}">'+e.title+'</a></div>')
        $ev.append('<div class="entry"><div class="desc">'+e.contentSnippet+'</div>')
        $ev.append('<div class="date">'+localdate+'</div></div>')

**Comment by felixhageloh** [comment]
I might be a bit slow this morning, but I don't quite understand what you are trying to achieve. What's the url you are trying to link to? (http://.com doesn't look like a valid url, but maybe it got garbled when you pasted here)

**Comment by willmapp** [comment]
The link I'm attempting to click is valid.

It would be www.aserver.com that's coming from the feed.

href = e.link // www.server.com

#{href} is quite literally equal to #{href} in the end when I click the link and not the location I want to navigate to.

**Comment by TraderStf** [comment]
I am not a specialist, is it not simply the quotes " and '
single = no computation
double = computation

**Comment by felixhageloh** [comment]
@TraderStf is correct. You can't use the string interpolation syntax `"some-#{string}"` with single quotes. So this will do the trick:

```
$ev.append("<div class=\"title\"><a href=\"#{href}\">#{e.title}</a></div>")
```

**Comment by felixhageloh** [comment]
btw I fixed the formatting of your comment. You used \<\> which github will try to interpret as html tags, which is why I had a hard time understanding your question

**Comment by willmapp** [comment]
That did it!

Thanks for your help.
