### ISSUE TITLE
Übersicht doesn't follow symlinks in the widgets folder

### ISSUE THREAD

**Issue by dudeofawesome** [felixhageloh/uebersicht#161]
I am attempting to set up a build system to allow for splitting main widget files into multiple sub files (.html, .scss, .js) to allow for easier development.

The final result of the build gets put into a ./build/final folder, which I would link to symlink to in the Übersicht widget folder.

[https://github.com/uPaymeiFixit/forecast-widget/tree/build-system](https://github.com/uPaymeiFixit/forecast-widget/tree/build-system)

**Comment by felixhageloh** [comment]
I didn't look at this in detail, but could a solution be to have your development folder outside the widget directly and then set up your build path to the be widget directory? That way only the built widget ends up in the widget directly and you wouldn't need any symlinks

**Comment by dudeofawesome** [comment]
I've updated my Gulp script to copy the compiled widget into the Übersicht widget folder instead of symlinking it.
