### ISSUE TITLE
Applescript to refresh all/specific widgets

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#165]
Like others have mentioned my widgets do not refresh when the mac wakes from sleep. That would be a great feature to add. However, in the meantime I have found the tool called sleepwatcher that is supposed to be able to run scripts upon wake/sleep. So, my question is if there is an applescript callback that we can use to refresh all or a specific widget?

**Comment by CarlosMed** [comment]
@mlcampbe Its easy for a JS/Coffeescript code since you just set a callback of the function and using the setInterval to call it back every so often along with the update command.

**Comment by mlcampbe** [comment]
Yes, I do have the refreshFrequency parameter in the code but that does not work after the machine wakes from sleep. I would like to force a refresh of all widgets upon waking the machine. Without the ubsersicht code from doing that I wanted a way to do it from the commandline so I could script it instead of having to click the refresh all item from the system icon. Its a picky thing but thought it might be possible.

**Comment by skonesam** [comment]
Would be nice if there was even a work-around to script the clicking of the
menubar -> refresh. I'm not familiar with the details of how to make that
happen, but I know it doesn't work now…

**Comment by mlcampbe** [comment]
That is exactly what I am trying to do. The app sleepwatcher can execute scripts upon system wakeup. Therefore I want a workaround to run a script to refresh all widgets which I will then use with the sleepwatcher tool.

**Comment by felixhageloh** [comment]
Actually, Übersicht already automatically refreshed when waking from sleep - I guess it is not working properly then

**Comment by mlcampbe** [comment]
No, the auto refresh does not seem to work. I have not timed it but it seems that after the system wakes up that the refresh interval picks up from where it left off. For example, if the refresh is 60 min and I put the machine to sleep 20 minutes into the cycle then after waking up it will take 40 minutes before it refreshes.

**Comment by felixhageloh** [comment]
Yup, you are right I found the problem as well (was listening to the wrong notification center). I'll release a fix soon!

**Comment by mlcampbe** [comment]
Perfect. Thanks for the quick response.

**Comment by felixhageloh** [comment]
just released a fix! (version 0.7.24)

**Comment by LoicVerrall** [comment]
@felixhageloh Hi, I've been using Übersicht for a week now (and love it!!). Just updated to the latest version which fixes this 'update on wake' feature.

I was wondering whether you had any plans to include some kind of API to get Übersicht to update.

For example, let's say I have a calendar with the current day selected which I want to change at midnight obviously. Is there a way I can call the update function from elsewhere (e.g. an AppleScript), at midnight?

Thanks, Loic
