### ISSUE TITLE
Flickering on space change

### ISSUE THREAD

**Issue by samuelbrooks** [felixhageloh/uebersicht#166]
First of, love the app! Nice work man.

Are there any plans on dealing with the reloading issue every time you switch spaces? (everything "flickers" back on when going from space to space).  Not a major bug just a little annoying.

**Comment by felixhageloh** [comment]
Thanks :)!

it is a known issue. I noticed that sometimes widgets don't redraw correctly when switching spaces, so I am forcing a re-render (which causes the flickering). I will keep an eye open for better fixes, but till then this is better than having widgets looking broken sometimes after switching spaces.
