### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by HansWurst90** [felixhageloh/uebersicht#167]
I am new to JavaScript and the Command Line.
What is the best way to work with multiple commands.
For Example:
I want to use information from the 'istats' and 'ipconfig' in the same widget. But I'm limited to one output parameter in all the methods. Is there a away to store the information from multiple commands in an arrays or something similar?

I hope it's fine to post that here. I'm also new to git and wasn't sure if it's okay to use 'Issues' for community questions like this.

Thanks in advance

**Comment by felixhageloh** [comment]
It's fine to post questions here!
You could use the `@run()` method (details are in the readme) to run additional commands or you could use a shell script to combine different commands and then call that script inside `command`

**Comment by mstr3336** [comment]
Hey, I want to revisit this under the new react based framework - 
I'm writing a widget for monitoring HPC jobs, by querying job stats over ssh. 

There's a few steps to getting decent depth to queries. 

First, query the list of jobs for a given user, to get the individual job IDs.
Iterate over this list, and query each job individually. 

Most jobs are single jobs, which look like `123456`, and getting their state ends here.

```
get_job_info 3991196 | jq
```

<details>

  <summary>JSON Output</summary>

```json
{
  "info": {
    "Job_Name": "STDIN",
    "job_state": "R"
  },
  "resource_list": {
    "cr_mdcs_tok": "0",
    "fs_factor": "100",
    "is_highmem": "false",
    "is_interactive": "true",
    "max_meg_ram_per_chunk": "16384",
    "max_ncpus_per_chunk": "2",
    "meg_ram_per_core": "8192",
    "mem": "16gb",
    "nchunks": "1",
    "ncpus": "2",
    "ngpus": "0",
    "nodect": "1",
    "place": "free",
    "reporting_queue": "interactive",
    "select": "1:ncpus=2:mem=16GB",
    "sort_time": "1579507047",
    "walltime": "04:00:00"
  },
  "resource_used": {
    "cpupercent": "0",
    "cput": "00:00:00",
    "mem": "14456kb",
    "ncpus": "2",
    "vmem": "14456kb",
    "walltime": "00:57:43"
  }
}
```

</details>


Some jobs are array jobs, which look like `123456[]`, and when `123456[]` is queried, the output will also include some information about the array indices. 

```
get_job_info 3990761[] | jq
```

<details>

  <summary>JSON Output</summary>

```json
{
  "info": {
    "Job_Name": "sim1-binom",
    "job_state": "Q",
    "array": "True",
    "array_state_count": "Queued:200 Running:0 Exiting:0 Expired:0",
    "array_indices_submitted": "1-200",
    "array_indices_remaining": "1-200"
  },
  "resource_list": {
    "cr_mdcs_tok": "0",
    "fs_factor": "10",
    "is_highmem": "false",
    "is_interactive": "false",
    "max_meg_ram_per_chunk": "8192",
    "max_ncpus_per_chunk": "2",
    "meg_ram_per_core": "4096",
    "mem": "8gb",
    "nchunks": "1",
    "ncpus": "2",
    "ngpus": "0",
    "nodect": "1",
    "place": "free",
    "reporting_queue": "normal",
    "select": "1:ncpus=2:mem=8gb",
    "sort_time": "1579502482",
    "walltime": "50:00:00"
  },
  "resource_used": {}
}
```

</details>

I can query individual array indices for more info:

```
get_job_info 3990761[1] | jq
```

<details>

  <summary>JSON Output</summary>

```json
{
  "info": {
    "Job_Name": "sim1-binom",
    "job_state": "Q"
  },
  "resource_list": {
    "cr_mdcs_tok": "0",
    "fs_factor": "10",
    "is_highmem": "false",
    "is_interactive": "false",
    "max_meg_ram_per_chunk": "8192",
    "max_ncpus_per_chunk": "2",
    "meg_ram_per_core": "4096",
    "mem": "8gb",
    "nchunks": "1",
    "ncpus": "2",
    "ngpus": "0",
    "nodect": "1",
    "place": "free",
    "reporting_queue": "normal",
    "select": "1:ncpus=2:mem=8gb",
    "sort_time": "1579502482",
    "walltime": "50:00:00"
  },
  "resource_used": {}
}
```

</details>

**Comment by mstr3336** [comment]
Also - 

Am I able to make multiples calls to `run` from a `command` function, collect the result from the cumulative `run` calls, and then pass that to `dispatch` ?

**Comment by mstr3336** [comment]
Hey, just circling back to this - 
The base question:

- Is there a "right" way to use the results of commands in subsequent commands, and have these dispatch nicely? 

Still stands - Maybe a more complex/complete stateful implementation  demonstrating this could be given in the docs if so.

That being said, I'm just going to make a server-side command that returns the output of every job. 
I'll probably just use python since its available on my cluster's env.

**Comment by felixhageloh** [comment]
not sure about the "right" way, but my initial approach would be to do it like:

```js
run('command1')
  .then(ids => Promise.all(ids.map(id => run(`command2 ${id}`))))
  .then(stuff => dispatch(stuff) )
```

you should also  be able to use `await` these days, which will clean up the `.then` nesting


```js
const ids = await run('command1');
const stuff = await Promise.all(ids.map(id => run(`command2 ${id}`)));
dispatch(stuff);
```
