### ISSUE TITLE
übersicht does not respect user profile

### ISSUE THREAD

**Issue by roele** [felixhageloh/uebersicht#170]
It seems that übersicht is not respecting the user profile properly (related to how Node.js spawns the Shell i guess). My widget relies on a Ruby Gem which, when installed via RVM (Ruby Version Manager), does not work as the RVM binary is installed to the user directory and linked via PATH variable.

However as i execute the command via Shell script i was able to workaround the issue by executing `source ~/bash_profile` to ensure all variables are set properly.

**Comment by felixhageloh** [comment]
working on a fix!

**Comment by motleydev** [comment]
Status? :)

**Comment by felixhageloh** [comment]
I ran into some issues using a log in shell by default (it has been a while so I can't remember the details). So for now you have still use `source ~/bash_profile` or specify full paths to your binaries

**Comment by motleydev** [comment]
Ok, thanks.

**Comment by bauen1** [comment]
Using this as my command works
```bash
/bin/bash -l --
# your normal command follows
```
`-l` login shell
`--` read and execute from stdin

This will not only read ~/bash_profile but also all the other files that bash would normally read.

**Comment by felixhageloh** [comment]
true, using this will make sure that you get the same behavior as when using a terminal. It is a common setup (and the mac OS default?) to have your `.bash_profile` also load your `.bashrc` tho. 
The downside is that you are spawning an extra shell on every command, but that probably doesn't matter much in terms of performance 😄.

Unless you are heavily relying on your bash setup, I usually find it the easiest to just use the full path to my binaries, like `/usr/local/bin/foo`

**Comment by bauen1** [comment]
Adding `-l --` to https://github.com/felixhageloh/uebersicht/blob/a28b80c8944c5acdd86a3f765a0ba276d1a2eabc/server/src/command_server.coffee#L9
would enable it for every widget (which _might_ be useful, but could also come at performance decrease).
This could probably be closed then.

**Comment by felixhageloh** [comment]
I tried this again and didn't notice any obvious issues. I also could not find or recollect why this caused issues in the past. I guess the only way to find out is to add it again and see if people's widgets start breaking 😅

**Comment by hawkrives** [comment]
@felixhageloh Would it be helpful to start collecting widgets that break, with the eventual goal of having a suite of them that we can run tests against and assert that they work correctly?

**Comment by felixhageloh** [comment]
I think that would have to be all widgets in the widget gallery, if I understand your suggestion correctly @hawkrives

**Comment by felixhageloh** [comment]
You can now enable 'load Bash env' under preferences (since version 1.2.48)!
