### ISSUE TITLE
External Monitor

### ISSUE THREAD

**Issue by MishaFrenkman** [felixhageloh/uebersicht#174]
Übersicht seems not to work when an external monitor is plugged in.

**Comment by felixhageloh** [comment]
Hi! Do you have the monitor set to be a mirror display by any chance?

**Comment by MishaFrenkman** [comment]
Yes I have

**Comment by felixhageloh** [comment]
Cool, it is a known Issue #63. I have a link there to a new version that should fix it. If it works I will release it this weekend!

**Comment by MishaFrenkman** [comment]
Alright cool, thanks!

**Comment by felixhageloh** [comment]
should be fixed with version 0.8.35
