### ISSUE TITLE
Strict mode introduced in parseWidget.js

### ISSUE THREAD

**Issue by drewvolz** [felixhageloh/uebersicht#175]
The introduction of `use strict` in commit [7257570](https://github.com/felixhageloh/uebersicht/commit/72575702800a888a6069833dc370bc580206c2e3) inside of [server/src/parseWidget.js](https://github.com/felixhageloh/uebersicht/blob/72575702800a888a6069833dc370bc580206c2e3/server/src/parseWidget.js#L1) affects JavaScript code that is written either in a non-strict widget, or JavaScript embedded in CoffeeScript. 

A few widgets I have scripted are failing to be interpreted as a result of this.

**Comment by felixhageloh** [comment]
Thanks for the concise bug report! I was not aware that strict mode will affect eval - will release a fix soon!

**Comment by felixhageloh** [comment]
Should be fixed in version 0.8.35
