### ISSUE TITLE
0.8 not working for some users at all

### ISSUE THREAD

**Issue by felixhageloh** [felixhageloh/uebersicht#176]
Description:
I tried 0.8.31 and it does not work. My logs have this message repeated over and over:

26/02/2016 5:16:57.731 PM Übersicht[40458]: http://127.0.0.1:41416/69732992 failed to load: The request timed out. Reloading...

This is true for both 0.8.3 and 0.8.31

If I visit the address in my browser, I can see the widgets, however nothing shows on my desktop.

Version 0.7 works fine.

**Comment by felixhageloh** [comment]
@EnglishLFC can I ask what version of OS X you are using?
Also, do you see any errors in the JS console (select "Show Debug Console" from the status bar menu)?

**Comment by EnglishLFC** [comment]
OSX El Capitan version 10.11.3 (15D21)

**Comment by EnglishLFC** [comment]
I downgraded to version 0.7. I can try an upgrade sometime this week though and see what, if any, errors are there.

**Comment by EnglishLFC** [comment]
Version 0.8.35 resolves this issue for me. Thanks.

**Comment by felixhageloh** [comment]
ok great!
