### ISSUE TITLE
CSS doesn't seem to display files with encoded characters

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht#179]
In my Playbox widget, I download album covers from Last.fm. I decided to make their filenames cleaner by encoding illegal characters. For example:

`Venetian Snares-Chocolate Wheelchair Album.png`

is converted to:

`Venetian%20Snares-Chocolate%20Wheelchair%20Album.png`

For some reason, Ubersicht won't display these files if called with the following CSS:

`background-image: url(http://127.0.0.1:41416/Sidebar.widget/Playbox.widget/as/Venetian%20Snares-Chocolate%20Wheelchair%20Album.png);`

Here's what I see in the Console:

![](http://imgur.com/FeBqdWZ.jpg)

I suppose I could use a different encoding technique (CSS seems to trip on "%" character) but I thought I'd bring it up in case it's a valid issue and solving it makes Ubersicht more flexible.

If you want to look at my code, [I made a branch for it](https://github.com/Pe8er/Sidebar.Widget/tree/playbox_testing/Sidebar.widget/Playbox.widget).

**Comment by hawkrives** [comment]
I'm curious; what happens if you edit the path in the inspector to use spaces, instead of %-encoding? I've found CSS to be surprisingly forgiving about spaces in URLs.

**Comment by Pe8er** [comment]
It does work, good idea. However, I would prefer to get rid of 'illegal' characters one way or another. Album names sometimes have the craziest characters in them and it's just _unhygienic_ to not get rid of those :) Curl which I use to download covers doesn't like them, filesystem might not like them. I'm just wondering if it's a problem with my Applescript or is it something that can be optimized in Ubersicht.

**Comment by felixhageloh** [comment]
It could be that it is a 'double escaping' issue, i.e the encoded spaces `%20` get escaped to `\%20` somewhere. How are you setting those urls? Inside the render method or maybe using jquery?

**Comment by Pe8er** [comment]
OK so I went ahead and altered how I encode illegal characters — for curl and last.fm API I do `%n` and for everything else i do `_`. It's working perfectly now.

> How are you setting those urls? Inside the render method or maybe using jquery?

**In Applescript:**
- grab artist and album name
- encode illegal characters
- return this string

**In shell script:**
- call applescript and echo it

**In index.coffee:**
- call shell script
- cut echo from shell script with `values = output.split(" ~ ")`
- assign variables to each value.

I hope it's helpful!

**Comment by felixhageloh** [comment]
Glad you figured it out! I'll close this for now - it will pop up again if it is a bug
