### ISSUE TITLE
Refresh time vs completing commands

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht#181]
It's not an issue per se, more of a question to the experts / begging for help :smile: 

In my Playbox widget, I download artwork from last.fm using `curl` command. I have the widget's refresh frequency set to 1 second because it also shows a progress bar, which I want to update in real time.

Now, sometimes if the network connection is slow or the file is larger than usual, the curl doesn't complete in one second, widget refreshes, curl runs again and the widget shows an error.

I've been thinking about running the curl in some kind of background thread but I've no idea how to tackle it. I would appreciate any advice, thanks!

**Comment by felixhageloh** [comment]
Do you fetch the artwork using `command: ` or are you using `@run` to run an additional command?

**Comment by Pe8er** [comment]
I'm doing the former. `command` runs two Applescripts via a shell script.

**Comment by felixhageloh** [comment]
Is the artwork just an image? In that case maybe you don't need to fetch it via curl. You could just return the url from your apple script and use it to update an image tag.

**Comment by Pe8er** [comment]
So this is a very good-sounding idea. I don't have to do curl anymore, which was the biggest cause of problems with my widget. I made the change and it seems to work well so far. Just need to figure out a way to make image loading smoother. Thank you sir!
