### ISSUE TITLE
Debug Console doesn't display all running widgets

### ISSUE THREAD

**Issue by joecreighton** [felixhageloh/uebersicht#183]
Ubersicht 0.8 (36).  OSX 10.11.3.

A picture is worth a thousand words, right?

![screen shot 2016-03-08 at 13 22 55](https://cloud.githubusercontent.com/assets/17548684/13613323/38a57838-e531-11e5-9aff-66efbe56c434.png)

There are 5 widgets running properly (3 pictured) but only one appears in the debug console.

Updated to Ubersicht 0.8 (36) this morning on the office machine.  Home machine may still have older version to check against (I was debugging last night and all widgets were present) but that's 6 hours away from checking on.

**Comment by felixhageloh** [comment]
are those widgets running on the same screen or on different screens?

**Comment by joecreighton** [comment]
The top clock is on two monitors and it appears in the console; the 4 others only run on a secondary monitor.

I see where you're going with this: as I threw each widget onto both monitors or main monitor only, it appeared in the console.  Widgets on the secondary monitor do not appear.

**Comment by felixhageloh** [comment]
Yeah you are on the right track!
Each screen has it's own debug console. So if you use the Übersicht menu on the main screen, it will open the console for the main screen and if you use the menu on the secondary screen it will open it for the secondary screen. 

I understand that this is quite a hidden feature and uncommon for apps to work like this, but it was the quickest and easiest solution I could come up with :).

**Comment by joecreighton** [comment]
I accept your reasoning :)  I'll just throw the widget onto both if I need to peek at anything: I prefer no menu bar on the secondary and do most of the widget debugging from home. I merely had a thought I wanted to test while it was fresh.

Thanks for the quick response.

**Comment by felixhageloh** [comment]
Haha, cool. I think it could be improved by also providing an option to open the debug console for each screen in the menu.
Btw I was totally unaware that this was possible to hide the menu bar for secondary screen on OS X (at least not since Yosemite) - I found out how now, thanks!

**Comment by joecreighton** [comment]
You're quite welcome.  I'll take payment of widget assistance, to be named later ;)

**Comment by felixhageloh** [comment]
alright then :D
