### ISSUE TITLE
How do you install Ubersicht?

### ISSUE THREAD

**Issue by AccuHostPro** [felixhageloh/uebersicht#184]
i've downloaded it for my El Capitan MacBook Air, and i double clicked the zip file . . and then . . nothing . . how do i edit .coffee?

**Comment by felixhageloh** [comment]
It should extract the app when you double click the zip file. You can the run the app by double clicking. To install it you can drag it into your applications folder. 

You'll see that the app is running by the little ü icon in your menu bar 
![screen shot 2016-03-10 at 8 52 09](https://cloud.githubusercontent.com/assets/367503/13662811/76fc954a-e69d-11e5-91de-681ea9de45b8.png)
and you should also see a widget on your desktop. 

Let me know if this helps!

**Comment by AccuHostPro** [comment]
ah stupid me yes i see it now thank you!!

Thanks,
Charlie Rivera
<http://www.linkedin.com/in/charlierivera/>
