### ISSUE TITLE
Can't use fat arrow?

### ISSUE THREAD

**Issue by Egoscio** [felixhageloh/uebersicht#186]
I tried using ES6 fat arrows in my render code, but it gives me the following error in the debug console:
```
SyntaxError: Unexpected token '>'
```
I'm glad we finally have babel, but why doesn't this work? Is it a babelify issue?

Thanks,

Egoscio

**Comment by felixhageloh** [comment]
ES6 support hasn't been released yet. There is a pull request but it is not merged - which reminds me to check on the status on that!

**Comment by Egoscio** [comment]
Alright, thanks! I was able to use other ES6 (well, babel) features like backticks, so I thought arrow func should work as well.

**Comment by felixhageloh** [comment]
If you were using them inside a JS widget some ES6 features will work because Safari (and thus Übersicht) supports some, but not all ES6 features: https://kangax.github.io/compat-table/es6/#safari9
