### ISSUE TITLE
Successful render on one screen, failure on another (NOT a bug)

### ISSUE THREAD

**Issue by joecreighton** [felixhageloh/uebersicht#187]
The weirdest thing just happened.  When I set my widget to render on both screens (for debug console use), the primary (with Apple menu) failed while the secondary (no menu bar) succeeded:

![screen shot 2016-03-15 at 12 34 28](https://cloud.githubusercontent.com/assets/17548684/13787701/fc85f862-eaaa-11e5-837b-932348eed21b.png)
![screen shot 2016-03-15 at 12 34 39](https://cloud.githubusercontent.com/assets/17548684/13787699/fc7d09aa-eaaa-11e5-96b7-b8a399641b48.png)

One refresh later, I also had it occur in the reverse, and with a different error (even though the code had not changed):

![screen shot 2016-03-15 at 12 36 28](https://cloud.githubusercontent.com/assets/17548684/13788330/5418c224-eaad-11e5-907a-31d4612317bc.png)
![screen shot 2016-03-15 at 12 36 33](https://cloud.githubusercontent.com/assets/17548684/13788329/5415dcf8-eaad-11e5-8c90-773e17429fdc.png)

This was very repeatable but the screen that failed was not predictable.

I thought Ubersicht shared data across screens but this suggested it was executing things in parallel for each render.  Given that I create a temporary file for one curl command, I was probably encountering a collision.  To test, I made the temporary file safe by using the PID number of the execution
`ILLUMTAB="moon-phase.widget/illumtab.txt.$$"`
and, sure enough, two files were created and both screens rendered fine, one a moment after the other.

This isn't really a bug but I felt I should pass this along as a data point on slow rendered widgets and temporary file usage.

**Comment by felixhageloh** [comment]
Noted :)!
you are right, when a widget renders on several screens it is not mirrored, but there are actually separate instance of the same widget running. I guess either approach has it's pros and cons: 

Having two instances is less complex and thus less error prone. Also one could imagine widgets that need to act differently deepening on the screen size (e.g. fetch different images) or can be in a different state through user interaction. 

Sharing data would remove overhead in many cases and it would avoid collisions when widget commands have other side effects (like creating temples in your case)
