### ISSUE TITLE
Widgets don't show on startup

### ISSUE THREAD

**Issue by ranranking** [felixhageloh/uebersicht#188]
I set to `launch uebersicht when log in`. But every time I start my machine, the widgets don't show up. The program is started because I can find it on my menu bar. Once I click some options from the menu bar, for example `show debug console` or `preference`, the widgets then show up. I am using OSX 10.11.4, and the binary clock widget.

**Comment by felixhageloh** [comment]
Interesting - I've never seen this before! 
Do you see any errors in the debug console?

**Comment by ranranking** [comment]
no, there is no errors in the debug console, so I am not sure what's going on

**Comment by felixhageloh** [comment]
The next thing you can check is is system log (Console App). You can search for 'sicht' (it doesn't like the Ü) and paste a few lines of the log around the time when Übersicht starts. It should look something like this:

<img width="851" alt="screen shot 2016-03-28 at 11 50 53" src="https://cloud.githubusercontent.com/assets/367503/14075678/695e9568-f4db-11e5-81bf-1b03effe3741.png">

**Comment by ranranking** [comment]
Thank you for the help. I don't know what I have done, it is working well now. Maybe I will close this issue for now.

**Comment by felixhageloh** [comment]
ok great :)
