### ISSUE TITLE
Common Stylesheet import?

### ISSUE THREAD

**Issue by blackley** [felixhageloh/uebersicht#190]
Hi,

Is it possible to use @import url('style.css'); in widgets?  Or is there another way of using a common style sheet?  I am trying to develop a shell widget with widgets inside that need to have positioning relative to the shell/wrapper widget.

**Comment by felixhageloh** [comment]
there is a long discussion thread here with some workarounds :): https://github.com/felixhageloh/uebersicht/issues/44
