### ISSUE TITLE
How to use @run in plain JS?

### ISSUE THREAD

**Issue by mhulse** [felixhageloh/uebersicht#191]
For the life of me, I can't seem to figure out how to call `@run` in plain JS. I keep getting:

> ... Unexpected token ILLEGAL

Here's what I'm trying:

```js
update: function(output, domEl) {
    @run('echo "hello"', function(o) {
        // ...	
    });
},
```

Also, side question, but is viewing the console at <http://localhost:41416/> the best way to debug widgets?

**Comment by hawkrives** [comment]
`this.run` is the JS equivalent of `@run` – `@` in coffeescript expands to `this.`

Coffeescript's website has a nifty converter built-in: http://coffeescript.org/#try:%40run%20%22echo%20hello%22

**Comment by mhulse** [comment]
Ack, well, that was too easy. Thanks @hawkrives.

Hopefully this post will eventually help other noobs new to Übersicth and Coffeescript …

**Comment by mhulse** [comment]
> Also, side question, but is viewing the console at http://localhost:41416/ the best way to debug widgets?

For future readers:

http://localhost:41416/ is good for debugging, but there's also this:

![screenshot 2016-03-31 08 58 54](https://cloud.githubusercontent.com/assets/218624/14182131/d81a8062-f71e-11e5-9d88-9c1b10b01d38.png)

Which, for some reason, wasn't an obvious place for me to look when I first asked this question.

Hope that helps other noobs fresh to Übersicht. :+1: :octocat:
