### ISSUE TITLE
How to get href links working?

### ISSUE THREAD

**Issue by mhulse** [felixhageloh/uebersicht#192]
I am create a widget with absolute href links to web urls (like <http://google.com>).

Is it possible make links clickable and open default browser to go to clicked href url?

I've found info on anchor links, and there was a comment about `command` + `click`ing, but that does not seem to work.

When I visit <http://localhost:41416/> the link works perfectly.

**Comment by mhulse** [comment]
So, this is strange, I tested the <kbd>command</kbd> + <kbd>click</kbd> on my work computer and, to my surprise, the href opened in Chrome!

Not sure why I was not able to replicate this on my laptop.

Soooo, looks like <kbd>command</kbd> + <kbd>click</kbd> works for anchors and regular `http` links!

Aweeeeeeesome!

**Comment by mhulse** [comment]
> Not sure why I was not able to replicate this on my laptop.

AH, the interaction setting was set to none on my laptop. Just switched to command key and it works!

![screenshot 2016-03-31 18 57 19](https://cloud.githubusercontent.com/assets/218624/14195796/767c42b0-f772-11e5-9f4c-6667162adce8.png)

**Comment by felixhageloh** [comment]
glad you figured it out!

**Comment by chunkhang** [comment]
I set my interaction shortcut to ⌘, but it only works when debug console is on.

**Comment by chunkhang** [comment]
> I set my interaction shortcut to ⌘, but it only works when debug console is on.

Oops. My bad. The problem is macOS Mojave. The solution can be found at #324.
