### ISSUE TITLE
Symbolic link woes

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht#194]
A bit of a problem: when a widget folder residing in `widgets/` folder is actually a symbolic link to another folder elsewhere, it does not refresh when "Refresh All Widgets" menu command is issued. I need to relaunch Ubersicht to "kick" it.

The reason why I want to have widgets as symlinks is because I keep their repositories elsewhere and it's super easy to push updates to Github if actual widget files are within the repo AND they get updated in the app automatically. I can work on them in one place and I don't have to copy stuff around like a maniac. Any advice if there is a better way to do it all automatically perhaps? :smile:

**Comment by felixhageloh** [comment]
yeah symlinks turn out to be a bit of a pain - I guess the file watcher does not handle them correctly without extra work. Plus, there is a difference between OS X shortcuts and unix symlinks. It is probably all fixable but it will require some time.

In the meanwhile, let's see if we can find a quick solution to your problem: I guess I don't fully understand why you have symlinks to github repos in your widget folder instead of just having them in the widget folder directly

**Comment by Pe8er** [comment]
>  I guess I don't fully understand why you have symlinks to github repos in your widget folder instead of just having them in the widget folder directly

OK. Let me illustrate. Here's what a typical widget repo folder structure looks for me:

![](http://imgur.com/7TP7AMh.jpg)

I would love to be able to keep this whole thing in Ubersicht's `widgets` folder. Unfortunately when I put it there, the widget is not recognized. The reason is because command's path in `index.coffee` points to `widgets/Strava.widget/`:

`command: "osascript Strava.widget/Strava.applescript"`

whereas in this situation it should be one level deeper:

`command: "osascript Strava.widget/Strava.widget/Strava.applescript"`

It shows up in this case, but it means users would have to edit this path manually to make the widget work on their systems. Doesn't sound like a good idea :smile: 

So what I do instead is keep the repo elsewhere, symlink the `Strava.widget/Strava.widget` folder and put it in `widgets` folder. The widget shows up, but it doesn't refresh.

I hope I'm making sense here. If there is a way to do it in a simpler way, I'm all ears!

**Comment by felixhageloh** [comment]
alright I see! It is about the path to your script of course. I don't see a quick solution at the moment. I will replicate your setup and see what the issue is with the symbolic links!

**Comment by Willamin** [comment]
I'm having this issue too. One solution could be to use some deploy method (eg. Capistrano) to deploy to the actual widgets direction. Just until the issue is resolved.

**Comment by felixhageloh** [comment]
quick question: how do you create the symlinks? Do you do `ln -s` in the terminal or do you use Finder to create them?

**Comment by Pe8er** [comment]
I create them with `ln -s`.

**Comment by felixhageloh** [comment]
been a long time - do you still have this issue?

**Comment by Pe8er** [comment]
No, it's good now. Thanks for checking in!
