### ISSUE TITLE
[feature request] add "do not show" option for widget

### ISSUE THREAD

**Issue by tripflex** [felixhageloh/uebersicht#195]
First, thank you very much for all the time you have put into this project, it is greatly appreciated!

After searching around in the issues I was able to find this issue, which gave me details on how to "disable" a widget, which at this time seems to be a bit cumbersome and without reading the issue, I would have never known how to do this:

https://github.com/felixhageloh/uebersicht/issues/11

Anyways, for those who aren't sure, you can disable a widget by selecting a screen under `Show on selected screens` and then selecting that same screen again, which will essentially not disable the widget on any screen.

I think it would be much quicker, and more straight forward for other users if there was another menu item that says something like `Do not show (disable widget)`

I honestly haven't looked at any of the code yet, but I can't imagine it shouldn't be too difficult to just hook that menu item to set say the first screen option, then unselect that same screen option.

Thoughts?

**Comment by felixhageloh** [comment]
Thanks for the feedback! 
You are right, it is not too hard to add the extra menu item - I just wanted to start with the simplest iteration and see if people actually wanted this feature. Now that a few people have requested it I think it is safe to say that people do want it :). I will look into adding it soon!

**Comment by tripflex** [comment]
Excellent, thanks for the response!

**Comment by jn64** [comment]
+1. My current solution is to rename widget files from `*.coffee` to `*.disabled` (or whatever made-up extension you choose).

**Comment by felixhageloh** [comment]
You now have a 'hide' option directly in the widget menu. Released with version 1.1.45!
