### ISSUE TITLE
Is it possible to refresh a widget when network connection is established?

### ISSUE THREAD

**Issue by Diskutant** [felixhageloh/uebersicht#196]
I have a widget that executes a command which checks some stuff online. The problem is, when I wake the MBP Übersicht refreshes the widget but network connection isn't available at that moment. Also refreshFrequency is set to one hour, so just waiting for the next refresh isn't a good option.

**Comment by felixhageloh** [comment]
there is no builtin solution at the moment, but maybe you could listen for network errors and in that case try refreshing the widget (using `@refresh()`) in short intervals until it succeeds.

**Comment by Diskutant** [comment]
I found no sleep or wait function in coffeescript/javascript, I do it in a bash script now
If anyone else wants to do something similar, this is my script:

```#!/bin/bash
while true
do
	if ping -c 1 -t 1 8.8.8.8 &> /dev/null
	then
		echo $(<do something>)
		exit 1
	else
	 sleep 10
	fi
done
```

**Comment by joecreighton** [comment]
This is pretty elegant.  In my case, this is at the top of my code and I `break` at the `<do something>` to continue execution below.  It works well and now my widget doesn't fail on the usual first API call.

Thanks, @Diskutant

**Comment by felixhageloh** [comment]
nice one @Diskutant, thanks for sharing!
