### ISSUE TITLE
XericDesign EarthDesk and Uebersicht

### ISSUE THREAD

**Issue by DirkLBlak** [felixhageloh/uebersicht#198]
At first I wanna say big thanks to you for such a nice piece of software.
Today I installed on my desktop EarthDesk, but now all my widgets are hidden. It looks like the background of EarthDesk is on top of uebersicht. When I hit the command button (the standard interaction shortcut) on my keyboard the widgets appear. My question is, can I change the "z-index" to bring the widgets in front of the EarthDesk background? Any help is appreciated.
Thanks

**Comment by felixhageloh** [comment]
Glad you are enjoying the software and sorry for the late reply!
I had a quick look at the Earth View Background widget and it does indeed look like it has an issue with it's z-index. You can fix though, by modifying its style:

<img width="216" alt="screen shot 2016-05-04 at 10 46 21" src="https://cloud.githubusercontent.com/assets/367503/15009217/8e089f90-11e5-11e6-88c3-917a53d963a0.png">

The 

```css
width: 100%
height: 100%
z-index: -1
```

styles, which are set on the `.earth` element should be set on the root element. Also, the trailing `9` there looks like a typo

Hope this helps!

**Comment by felixhageloh** [comment]
closing for now. Feel free to re-open if you still have questions!

**Comment by encodis** [comment]
Hi

Just discovered Übersicht when looking for a Geektool replacement. Looks interesting but I have the same issue as the OP - the widgets do not show up on my main desktop that runs XericDesign's [EarthDesk](https://www.xericdesign.com/earthdesk.php) software. Your reply to the OP talks about the "Earth View" widget which is, I think, an entirely different thing - Earth**Desk** is not a widget but a standalone application. 

Is there a fix for this?

Thanks!

**Comment by felixhageloh** [comment]
It could be that the two are Apps incompatible, because they are both trying to occupy the same layer above the desktop. The only advice I can give for now is to ensure that you did _not_ enable 'compatibility mode' in the Übersicht preferences

**Comment by encodis** [comment]
Thanks for the tip, although unfortunately it didn't work. This seems similar to this issue
https://github.com/felixhageloh/uebersicht/issues/296 - I guess there are only so many layers available to the desktop, so it's not possible to put Übersicht "on top" of Earthdesk. 

However, would it be possible to add an option which would turn off widget interaction completely in exchange for placing Übersicht at a different layer? 

Thanks!
