### ISSUE TITLE
OS X 10.11.5 Update broke the coffee scripts?

### ISSUE THREAD

**Issue by aaker123** [felixhageloh/uebersicht#200]
Hi,

I am rather new to all of this but I find it very useful to have some folder shortcuts on the desktop or just show the calendar. Although today after trying to get some Übersicht widgets working I found that most widgets can only read but don't seem to be able to execute or write into the system (I may be wrong ofcourse). I tried to get the simple widget https://github.com/travtrigs/folder-launcher.widget/tree/845caef6cf6a97ac32d867d54608ac5c69eaa14a to work but it no longer does. I did give them 0755 rights too. Also when trying out some other widgets they seem not to function properly.
Any thoughts?

**Comment by felixhageloh** [comment]
Hi! Can you elaborates what breaks for the folder-launcher widget?

**Comment by aaker123** [comment]
As far as I can tell everything is installed as written in the manuals as per for Übersicht and the widget. So I literally wrote the only difference between my system and other systems where it may still work - which is that this morning I installed OS X 11.10.5

**Comment by felixhageloh** [comment]
But what is the issue that you are seeing with the folder-launcher widget? Does it not show at all or is some of the functionality broken?

**Comment by aaker123** [comment]
It cannot launch any folders or scripts

**Comment by felixhageloh** [comment]
I just tried the widget and it seems to work ok for me (I'm also on 10.11.5). I did have to fix the widget code first tho:

all paths were pointing to `folder-launcher.widget` whereas when I downloaded the widget, the folder was called `folder-widget`

**Comment by aaker123** [comment]
Thanks for the quick response :)

**Comment by aaker123** [comment]
`Aares-MacBook-Pro:~ aarepajuste$ cd Library/Application\ Support/Übersicht/widgets/
Aares-MacBook-Pro:widgets aarepajuste$ ls -l
total 0
drwxr-xr-x@ 4 aarepajuste  staff  136 May 18 10:59 Sidebar.Widget
drwx------@ 7 aarepajuste  staff  238 May 18 11:56 folder-launcher.widget
Aares-MacBook-Pro:widgets aarepajuste$`
The case is not the same for me though. When I downloaded that it is named correctly and the links for the images work too

**Comment by aaker123** [comment]
Here's my current code which won't launch Finder upon clicking the icons
http://pastebin.com/3DzVB8Nk

**Comment by felixhageloh** [comment]
Do you see any error message in the debug console? I used your code and it all works fine (after renaming `folder-launcher.widget` -> `folder-launcher`). Here is the code (I also removed some unnecessary hard-coded paths):

```coffeescript
command: ""

refreshFrequency: 300000

render: ->"""
<li class="button" id="iCloud">
 <img src="folder-launcher/Icons/iCloud.png">
</li>
<br>
<li class="button" id="Computer">
 <img src="folder-launcher/Icons/Computer.png">
</li>
<br>
<li class="button" id=Disk>
 <img src="folder-launcher/Icons/Disk.png">
</li>
<br>
<li class="button" id="Home">
 <img src="folder-launcher/Icons/Home.png">
</li>
<br>
<li class="button" id="Library">
 <img src="folder-launcher/Icons/Library.png">
</li>
<br>
<li class="button" id="Documents">
 <img src="folder-launcher/Icons/Documents.png">
</li>
<br>
<li class="button" id="Pictures">
 <img src="folder-launcher/Icons/Pictures.png">
</li>
<br>
<li class="button" id="Movies">
 <img src="folder-launcher/Icons/Movies.png">
</li>
<br>
<li class="button" id="Music">
 <img src="folder-launcher/Icons/Music.png">
</li>
"""

afterRender: (domEl) ->
  $(domEl).on 'click', '#iCloud', => @run "open '/Users/felix/Library/Mobile\ Documents/com~apple~CloudDocs'"
  $(domEl).on 'click', '#Computer', => @run "./folder-launcher/script.sh"
  $(domEl).on 'click', '#Disk', => @run "open '/'"
  $(domEl).on 'click', '#Home', => @run "open ~"
  $(domEl).on 'click', '#Library', => @run "open ~/Library"
  $(domEl).on 'click', '#Documents', => @run "open ~/Documents"
  $(domEl).on 'click', '#Pictures', => @run "open ~/Pictures"
  $(domEl).on 'click', '#Movies', => @run "open ~/Movies"
  $(domEl).on 'click', '#Music', => @run "open ~/Music"

style: """
 position: fixed
 top: 180px
 left: 0px

 img
   height: 35px

 .button
   display: inline
"""
```

**Comment by aaker123** [comment]
Unfortunately it still does not want to work with your code. I even uninstalled my antivirus, to see if it affected it, but to no avail. Debugger shows no errors upon clicking the icons...

**Comment by felixhageloh** [comment]
what happens if you run those commands directly in the terminal? `open ~/Music` for example?

**Comment by aaker123** [comment]
All of the commands work if ran from the terminal

**Comment by felixhageloh** [comment]
also, just to double check: is your interaction shortcut configured correctly (i.e, the key you need press to make widgets clickable)?

**Comment by aaker123** [comment]
There's the problem... silly me! Sorry for wasting your time

**Comment by felixhageloh** [comment]
:D all works now?

**Comment by aaker123** [comment]
Yeah, thanks a lot ... didn't realize the binding's necessary

**Comment by felixhageloh** [comment]
NP! glad it works after all
