### ISSUE TITLE
Move to the standard ES6 Module Loader

### ISSUE THREAD

**Issue by alexisvincent** [felixhageloh/uebersicht#201]
@felixhageloh 

I would like to propose that this project makes a move to the ES6 Module Loader specification such that every module exposes a certain properties (as is currently done), shifting preprocessing decisions to widget developers.

In this case use of coffeescript and stylas could instead be supported though ES6 Loaders, and widget writers can choose any build system or language that they are comfortable with, as is the case on the web. 

This would mean Uebersicht would provide much the same interface as modern browsers instead of providing alternative loops developers need to jump through.

I'd be interested to hear what you think?

**Comment by felixhageloh** [comment]
I think this should be possible with the new widget syntax (in fact that was one of the motivating factors behind it)! Widgets will just be JS modules and the default syntax will be ES2015 (with a dash of ES7 in there, like rest spread operators). To make sure I understand you correctly tho, can you elaborate what you mean by ES6 loaders?

**Comment by alexisvincent** [comment]
Sounds good :) I'd be happy to help with implementing this if you'd like https://github.com/ModuleLoader/es6-module-loader

**Comment by alexisvincent** [comment]
Also, how do you plan to support styling?

**Comment by felixhageloh** [comment]
Thanks for clarifying! My current implementation relies on browserfify. I haven't looked much into the es6 module leader since the standard is still changing. From what I understand, the current draft aims to be compatible with browserify (or at least provide hooks) so maybe it is a safe option to stick with it for now - what do you think?

For styling I want to use [inline styles](https://facebook.github.io/react/tips/inline-styles.html) - super simple and works similar to current widgets. People can also easily combine it with [Radium](http://stack.formidable.com/radium/) if they need simple support for :hover styles etc

Btw, you can already play with the new widget syntax in the current beta! If you call your file `.jsx` it should just work. And yes, help is welcome if you'd like to contribute

**Comment by alexisvincent** [comment]
The standard is pretty applicable especially in the form of https://github.com/systemjs/systemjs. Guy Bedford has an awesome project going and it would be especially great in this situation because of its universal module support. Inline styles sound like a good idea, would perhaps just be good to provide good widget boilerplates to guide people in their implementations for those who have never used CSS in JS techniques. I'd also caution against supporting just React over other rendering engines, as this might push away some developers.

**Comment by felixhageloh** [comment]
Cool thanks, I will have a look at systemjs! 
Supporting different render engines might be more tricky. The new widget engine heavily relies on a diffable virtual dom being present. I'm not using React btw, but [snabbdom](https://github.com/paldepind/snabbdom)

**Comment by alexisvincent** [comment]
Hmm, I have some alternative ideas you might want to consider. How would you feel having a discussion on Skype or something similar?

**Comment by alexisvincent** [comment]
I don't understand why you're using something like snabbdom at all? Why not just expose a regular dom api and let developers use their own tooling?

**Comment by felixhageloh** [comment]
sure, my Skype name is felixhageloh

Btw, I'm using a virtual dom because I want a sane and easy default for people developing widgets (many of which are not developers)

**Comment by felixhageloh** [comment]
hey there! Haven't seen you on Skype so far (I'm also not logged in very often) - let me know if you have specific time when you want to talk (maybe on the weekend)

**Comment by alexisvincent** [comment]
@felixhageloh Yeah, sorry, I don't actually ever keep Skype open. How about Saturday (morning?). What timezone are you in? I'm +2.

**Comment by felixhageloh** [comment]
my turn to apologize - it's been a crazy week! I could do this Saturday, tho - pretty much anytime after 12:30. Oh and we are in the same timezone :)!

**Comment by alexisvincent** [comment]
I'm interested to know, has this been achieved? Or are you just tidying up?

**Comment by felixhageloh** [comment]
Hey,  just typing up! Probably won't pick this up in the near future. Feel free to ping me if you want to discuss something!
