### ISSUE TITLE
Division calculation in style not working 

### ISSUE THREAD

**Issue by txt8888** [felixhageloh/uebersicht#207]
I have this in the style and it failed all the time:

`border-radius: 100px / 2`

but if I switched to this and it works:

`border-radius: 100px * 0.5`

is division NOT supported?

**Comment by evanfuture** [comment]
Isn't the syntax `calc(100px / 2)` ?

**Comment by felixhageloh** [comment]
from the stylus docs (http://stylus-lang.com/docs/operators.html):
> When using / within a property value, you must wrap with parens. Otherwise the / is taken literally (to support CSS line-height)


so I guess `/` is a special case and `border-radius: (100px / 2)` should work

**Comment by txt8888** [comment]
yes.  adding the parenthesis works.  Thanks!
