### ISSUE TITLE
After update can not view any widgets

### ISSUE THREAD

**Issue by shagless** [felixhageloh/uebersicht#208]
I updated after not using app for a while.  Wanted to tinker today.  When I first started app, widgets showed.  Then asked if I wanted to update.  Said yes.  Haven't seen a widget show since.  I emptied my folder and used the debugger on one widget.  Here is the error showing: Übersicht/widgets/devicebatt-2.widget/index.coffee: TypeError: Cannot read property 'position' of undefined while parsing file:

**Comment by felixhageloh** [comment]
yes unfortunately it is a known issue. Older versions of Übersicht allowed some invalid CoffeScript syntax. The devicebatt widget probably has a style declaration like this: 

```CoffeeScript
style: """
  some: style
  position: #{@position}
  ....
"""
```

if you change all occurrences of `@position` to just `position` it will all work!
