### ISSUE TITLE
Path monitoring

### ISSUE THREAD

**Issue by calexicoz** [felixhageloh/uebersicht#209]
Hey,

This is somewhat a feature request/question. I'd be interested in a simple way to update the widget based on inotify for specific paths. Specifically, some of my widgets are just transforms of text files, and I always want to see the most up to date version of those files. I can set a high update frequency (say every 1s), but then that drains the battery. It would be nicer if I could say: update whenever one of those path is updated. Then I would always see the latest version, but only pay the cost whenever those file change.

I feel like I can achieve something like this with the `update` call, and doing my own monitoring, but just wondering if that would make sense for uebersicht itself, or if there is some nice shortcut I could use.

Thanks!

**Comment by felixhageloh** [comment]
Hi, sorry for the late reply! I think it is a great feature and similar things have been requested in the past. I'm not quite sure how to tackle it just yet - Übersicht would have to expose some way to push data to a widget. 

In the meantime you can probably achieve what you want by either using web sockets or long polling. You'd have to build  program that listens to file changes and also sets up a simple web socket/http server.  You can then connect to that server from your widget and react whenever it pushes data back.

**Comment by calexicoz** [comment]
Hey Felix,

What I ended up doing was to use [Watchdog](https://pythonhosted.org/watchdog/) to monitor the directories, and to `touch` the coffee file when one of the watched files changes. Since Übersicht watches the coffee file, it will force a reload (and thus an update) :

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/bin/watchmedo shell-command \
  --recursive \
  --patterns="*.py,*.rb,*.cfg,..." \
  --command="touch ~/PATH_TO/WIDGET.coffee" \
  SOME_PATH
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The main use case is to watch the widget directory recursively. My widgets typically call out to ruby or python, so I want the widget to reload whenever the script it calls changes :

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
command: "script.py"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since you're already using `fsevents`, I figured there might be an easy way to do that already. Doesn't seem to be the case. Maybe a future improvement would be the ability to define the extensions/paths that can force a reload in the widget directory. That might cover a good number of cases.

**Comment by felixhageloh** [comment]
Oh right, so if I understand correctly you are mostly looking for this feature for developing widgets and not so much for the final result (i.e. widgets that don't have a refresh frequency but update based on external events)

**Comment by calexicoz** [comment]
Well, yes and no. I'll give you a more concrete example. I keep tasks & todos in 3 text files (priority 1, 2 , 3). I want to keep an eye on my priorities, so I created a widget that reads the text files, applies some transformations to the content (markdown and a few other things), and shows them on my desktop:

<img width="1228" alt="screen shot 2016-06-12 at 1 40 12 pm" src="https://cloud.githubusercontent.com/assets/76221/15992844/852e2bc8-30a4-11e6-9ade-c085041489ec.png">

I want what shows on my desktop to always reflect the content of those files, so I have 2 solutions:

- Refresh every few seconds (battery intensive)
- Refresh based on filesystem events (efficient)

I sometimes also make modifications to my transformer script (python), in which case I want the widget to refresh with each save. And I also have a config file that influences the process, and which should also trigger a refresh. To keep things practical, I just put everything inside the widget folder itself, and I symlink my text files to the desktop for quick editing. So my widget folder looks like this:

```
priorities/1.txt
priorities/2.txt
priorities/3.txt
scripts/transform.py
config.cfg
widget.coffee
```

Any change to any of this files should trigger a refresh, but I don't otherwise need time-based refresh.

Ideally, I think it would be nice to be able to monitor any files/folders, but everything inside the widget folder works just fine.

I hope this makes things a little clearer.

**Comment by felixhageloh** [comment]
clear! Thanks for the detailed response :)

**Comment by evanfuture** [comment]
Could you not just do a low-intensity check to see if the edit-itemstamp of a file has changed?  That's the approach I'm taking with my own widget that checks for location and gets a map of the area via mapbox only if its changed since the last time.

**Comment by calexicoz** [comment]
Hey Evan,

I could, but then I would have to check every file each time, and because I really want the instant feel of editing the file and having the result show on my desktop, I would like to check every second. That is a lot of work for something that filesystem events give for free, at no cost.
