### ISSUE TITLE
macOS 10.12 beta 1 won't load the debug console

### ISSUE THREAD

**Issue by mhartington** [felixhageloh/uebersicht#211]
Hey there!

After updating to macOS beta 1, I can no longer enable the debug console.
I know 10.12 won't be out for a while, but I figured I'd let you know before hand

**Comment by felixhageloh** [comment]
thanks for the heads up! I'm using an unofficial api to make the console work, so it could be that they finally closed that loophole

**Comment by felixhageloh** [comment]
fixed in version 1.0.43 released today
