### ISSUE TITLE
Unable to refresh after MacBook wakes from Sleep mode

### ISSUE THREAD

**Issue by heqian** [felixhageloh/uebersicht#213]
I noticed that in several scenarios, Übersicht will stop working and I have to relaunch the app:
1. MacBook wakes from Sleep mode. Übersicht shows nothing and it won't be able to refresh;
2. MacBook boots without Internet connection. After booting, it takes my MacBook ~10 seconds to connect to our campus's WPA2 Enterprise Wi-Fi. Before the connection is established, Übersicht finishes its launch. After the connection is okay, manually control Übersicht to refresh won't work. I have to relaunch it.

I took a look of the logs for the 1st scenario. This line caught my attention:
- `6/23/16 10:41:47.312 PM Übersicht[338]: using 0 screens`

BTW: My MacBook connects to external display and the internal display is turned off. Mac OS X: 10.10.5

**Comment by felixhageloh** [comment]
It looks like Übersicht doesn't find/recognize your display in those scenarios. Sound like a legit bug!

**Comment by russianidiot** [comment]
something wrong with /Applications/Übersicht.app directory. rm & reinstall helps

**Comment by felixhageloh** [comment]
This should be fixed with the latest release (1.1.45). Please re-open if you still have this issue!

**Comment by heqian** [comment]
I will pay attention to it and report back later. Great work, as always!
