### ISSUE TITLE
WindowServer is always above 12% CPU usage

### ISSUE THREAD

**Issue by sofux** [felixhageloh/uebersicht#215]
After installing the latest version, WindowServer CPU usage increased above 12% -13%. My mac is warming up very quickly after initial start when Uebersicht kicks in. If I quit Uebersicht, the WindowServer CPU usage drops to 3%.

**Comment by soberstadt** [comment]
What widgets are you using?

**Comment by sofux** [comment]
Here is the list of widgets
![widgets 2016-06-26 14-11-15](https://cloud.githubusercontent.com/assets/11154105/16363937/ddc025b2-3ba7-11e6-9d68-be8c0353d44a.png)

**Comment by felixhageloh** [comment]
has this improved with the latest version of Übersicht?

**Comment by sofux** [comment]
it is significantly down most of the time. Around 5.5% to 8%.

**Comment by felixhageloh** [comment]
awesome, I'll close this for now then!
