### ISSUE TITLE
Is there a way for widgets to detect which display they are on?

### ISSUE THREAD

**Issue by StJohn3D** [felixhageloh/uebersicht#216]
I have 3 displays and I want to make a widget that appears to travel between them. Is there a way for widgets to know which display they are in?

**Comment by felixhageloh** [comment]
there is no official way yet, but the url widgets are loaded from contains a screen id. So you can call `window.location.pathname` and you will get the screen id (with a leading `/`). Keep in mind that the id will also change if some screen configuration changes, though. This means that the same screen can have a different id sometimes

**Comment by StJohn3D** [comment]
Thanks!
