### ISSUE TITLE
Global `Refresh All Widgets` keyboard shortcut

### ISSUE THREAD

**Issue by dubstrike** [felixhageloh/uebersicht#219]
I'm using widgets with a background blur filter and they sometimes lose the blur. A refresh fixes the issue.

I'd love if there was a configurable keyboard shortcut that I could invoke from anywhere to refresh all widgets.

**Comment by felixhageloh** [comment]
I've been noticing the same, but I haven't manage to find a way to fix it. Using a global refresh keyboard shortcut might be a good idea (even in general), thanks!

**Comment by skonesam** [comment]
Gentle bump on this. I have a couple infrequently-updated widgets that I'd like to refresh when the data they're presenting changes. Keyboard shortcut would be nice; also nice would be a way to do it automatically (applescript, whatever).

**Comment by dubstrike** [comment]
AppleScript or something else would be perfect to use this shortcut with Alfred.

**Comment by felixhageloh** [comment]
Working on apple script support :)! 

As a side note tho, regarding refreshing widgets when data changes, you should already be able to do that -  unless I am missing something

**Comment by felixhageloh** [comment]
I've released AppleScript support with version 1.1.45 yesterday! I'll close this for now, considering that you can create a shortcut using Alfred. Feel free to reopen if you like to see this built into the app

**Comment by dubstrike** [comment]
Already done. Big thanks @felixhageloh! 👏
