### ISSUE TITLE
Ubersicht freezing on Mavericks

### ISSUE THREAD

**Issue by calvinchew** [felixhageloh/uebersicht#22]
When leaving it to run for extended periods, Ubersicht occasionally stops responding and freezes, sending one core on my MacBook Pro Retina 13" to 100% usage. 

Widgets installed: Mini Top Mem, Simple Clock, Top CPU, Total Memory (all from System Monitor Set), Spotify Current Track, and Network Thoroughput.

**Comment by felixhageloh** [comment]
Great! Hopefully that was really the fix then. I will close this issue for now
