### ISSUE TITLE
Call the @start() @stop() and @refresh() methods for a different widget?

### ISSUE THREAD

**Issue by jmrq** [felixhageloh/uebersicht#220]
Is there a way to have a button in Widget A that calls the @start(), @stop() and @refresh() methods for Widget B?

I'm looking for something like this (the code would be in Widget A):

afterRender: (domEl) ->
  $('#IDofButtonInWidetA').click => @start('Some magical way to start Widget B')
  
Is this possible?  How would I 'talk' to widget B from widget A?

I've used the debug console to get the ID of the widget I'm trying to talk to, and I've tried various combinations of the widget ID and the @start function but I can't seem to get it to work.

I'd imagine this would be useful for a variety of purposes.  In particular here's what I'm trying to do:

I have two widgets that display song info from Pandora (using Pianobar, a terminal based Pandora client).  Both widgets display the same info; one of them is a small desktop widget and the other is a fullscreen display similar to what you see in the Pandora app on xBox.  I only want one widget running at a time.  So when I click a botton on the desktop widget to open the fullscreen widget, I'd like to stop the desktop widget from running, but also start and refresh the fullscreen widget.  Similarly, when I click a button on the fullscreen widget to close it, I'd like to stop the fullscreen widget but also start and refresh the desktop widget.

Any suggestions?

Ps. THANKYOU Felix, Ubersicht is a fantastic app!!!

**Comment by felixhageloh** [comment]
Hey, sorry for the late reply!

There is no official way to communicate between widgets, but you could built some your own. I see a few possibilities:

### 1. Exposing a global function. Something like:
Widget B
```coffeescript

afterRender: -> 
  window.startWidgetB = () => @start()
```

Widget A
``` coffeescript
afterRender: (domEl) ->
  $('#IDofButtonInWidetA').click = window.startWidgetB
```


### 2. Using a custom event

Widget A
``` coffeescript
afterRender: (domEl) ->
  $('#IDofButtonInWidetA').click = -> $(window).trigger('startWidgetBButtonClicked')
```

Widget B
``` coffeescript
afterRender: (domEl) ->
  $(window).on 'startWidgetBButtonClicked', => @start()
``` 

And there are probably other ways that I didn't think of. Hope this helps!

**Comment by jmrq** [comment]
Hi Felix,

Thanks so much for taking the time to respond to my question and offer some solutions.  I've been messing around with your suggestions for a few days, but unfortunately I can't seem to get either strategy to work.  I must be missing something.

I'll continue to experiment with the two methods you suggested and post back here if I make any progress, but as of now no luck yet.

Thank you again for your help, and thank you for Ubersicht!
