### ISSUE TITLE
Submit to Homebrew

### ISSUE THREAD

**Issue by IVXCVI** [felixhageloh/uebersicht#221]
Please consider submitting to Homebrew package manager project:

https://github.com/Homebrew/brew

**Comment by alexfedoseev** [comment]
```
brew tap caskroom/cask
brew cask install ubersicht
```

**Comment by IVXCVI** [comment]
Thanks!

On July 28, 2016 12:59:34 PM CDT, Alex Fedoseev <notifications@github.com> wrote:
>```
>brew tap caskroom/cask
>brew cask install ubersicht
>```
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/felixhageloh/uebersicht/issues/221#issuecomment-235974737

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by felixhageloh** [comment]
thanks! I was not aware there was a cask for it already :)
