### ISSUE TITLE
limit certain widgets to one space

### ISSUE THREAD

**Issue by mikestr** [felixhageloh/uebersicht#222]
Hi,
I'm new to uebersicht, but it seems as though I can't configure it to show the widgets only on one space (desktops in mission control).  Is this possible, and if not, might it be implementable? MacOS lets you assign certain applications to particular spaces, so I imagine they are distinguishable somehow.

Regards,

ms

**Comment by felixhageloh** [comment]
Hi! Unfortunately I have not found a way to identify specific spaces in OS X yet - it seems like it is an undocumented functionality that apple keeps to itself.

**Comment by hawkrives** [comment]
There's apparently a private API to do so: https://manytricks.com/blog/?p=4056

**Comment by mikestr** [comment]
That's unfortunate.  All I found in my search was this page: http://apple.stackexchange.com/questions/191845/open-application-in-specific-space-through-applescript

which links to:    http://macscripter.net/viewtopic.php?id=23453

but the link from hawkrives suggests maybe Apple doesn't want to give access to specific spaces...

**Comment by felixhageloh** [comment]
Thanks for the links guys! I'll keep my eyes open for a good solution. For now I'm a bit reluctant to use a private API to add this feature. I'm using a private API for showing the debug console and that has already caused issues a few times (but it is a too important feature to miss IMO)
