### ISSUE TITLE
Why open a port on 127.0.0.1

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#223]
I see some references to this in the issues but no where do I find out why this port is active. I saw today on my machine that the process http://127.0.0.1:41416 was taking up a lot of CPU. I killed it and restarted ubersicht and it is fine now. However I also can access that URL in a browser and it shows a representation of my desktop. Why is this active and is there a way to stop it from running?

**Comment by felixhageloh** [comment]
Hi, you are seeing an open port because this is basically how Übersicht works: it is a large transparent browser window that loads a webpage, which is hosted on 127.0.0.1:41416. 
I am not sure what caused the CPU spike tho; it could have also been a widget acting up because of an error.
