### ISSUE TITLE
Possibility to Add Monitor specific CSS

### ISSUE THREAD

**Issue by gmcnaught** [felixhageloh/uebersicht#224]
If each monitor is running its own separate browser and individual widgets, is it possible to do css styling that is monitor specific?

**Comment by felixhageloh** [comment]
You could use media queries for max-width etc. if your screens have different dimensions.

The other alternative is more brittle and unsupported, so it might break in the future: each screen is loaded with a screen ID which you can grab from the end of the current URL (window.location.href) . You could read it in your afterRender callback and use it to set a CSS class on your widget. Other than being unofficial, the downside of this method is that the screen ID (which is provided by the OS) sometimes changes for the same screen
