### ISSUE TITLE
All widgets refresh whenever a resource intensive program is launched

### ISSUE THREAD

**Issue by 8bitgentleman** [felixhageloh/uebersicht#225]
Whenever I launch a program like Photoshop or Parallels all of the widgets on my desktop refresh (sometimes several times in a row). I have several widgets that are coded to refresh only once a day and the constant refreshing messes with them. Is there any way to fix this?

**Comment by felixhageloh** [comment]
It's known issue with graphics car switching https://github.com/felixhageloh/uebersicht/issues/189#issuecomment-201211761
