### ISSUE TITLE
Check if we have internet connection

### ISSUE THREAD

**Issue by vkravets** [felixhageloh/uebersicht#226]
I found that there is a property of window.navigator which show if there  is internet connection http://www.w3schools.com/jsref/prop_nav_online.asp. Also there are events when it was down and when it was up. Thus it can be simply used... but it seems that we have lack of infrastructure of the widgets.

We can use command as function and check all needs which we need and restore data if there is no internet connection but...
1. Each refresh widget fully recreate, thus there is no any possibility to save any data in widget as local variable
2. We can create endpoint to save widget's related data to specific folder and in specific format and saved it in memory or at disk...
3. Perform some logic to choose command to execute specific command in command function, but #227 

@felixhageloh what solution is more prefered for you? I can try to create PR for 1 or 2

**Comment by felixhageloh** [comment]
I you could use [localStorage](https://developer.mozilla.org/en/docs/Web/API/Window/localStorage) to store widget data when offline. 
I've also addressed Issue #227 separately

**Comment by vkravets** [comment]
@felixhageloh Thanks a lot, I'll check this and let you know if it's working as needed in our sandbox...

**Comment by vkravets** [comment]
@felixhageloh everything works as expected except #226... Thanks for pointing me to localStorage

Close this one
