### ISSUE TITLE
Widget internal API is not accessible from command function

### ISSUE THREAD

**Issue by vkravets** [felixhageloh/uebersicht#227]
Widget internal API is not accessible from command function

```
command: (callback) ->
   @run 'echo Hello World!', (error, data)->
     callback(error, data)
```

I will get error  this.run is not defined or something similiar

**Comment by vkravets** [comment]
I know that in documentation said that is correct behavior, but could you please add this to command function also...

As I described in #226 we can process come logic before execute command or choose command which we need to execute and execute if via @run... but unfortunately there is no any solution for that now in  uebersicht

**Comment by vkravets** [comment]
Ohhh, my miss I'm not very good with coffescript unfortunately...
I will check and close the issue if will no any questions...

**Comment by vkravets** [comment]
Not working... (

Such code:
```
command: (callback) =>
   @run 'echo Hello World!', (error, data) ->
     callback(error, data)
```

In console appeared such error:
```
TypeError: _this.run is not a function. (In '_this.run('echo Hello World!', function (error, data) {
                return callback(error, data);
            })', '_this.run' is undefined)
```

**Comment by vkravets** [comment]
May be as workaround change https://github.com/felixhageloh/uebersicht/blob/master/server/src/runCommand.js#L9

```
command(widget, callback);
```

and in this case command function will be looked like this one
```
command: (widget, callback) ->
   widget.run 'echo Hello World!', (error, data) ->
     callback(error, data)
```

This will work )

**Comment by felixhageloh** [comment]
looks like a real issue - I'll look into it!

**Comment by vkravets** [comment]
Working with normal arrow:
```
command: (widget, callback) ->
   widget.run 'echo Hello World!', (error, data) ->
     callback(error, data)
```

Working as expected, thanks a lot! Closing the issue

**Comment by vkravets** [comment]
Thanks a lot, widget with quote based on inspiration quote working well without internet )

```coffee
# *** Was ****
command: """
curl -L -s http://greatwords.ru/random -o inspirational-quote.widget/random.html ; \
cat inspirational-quote.widget/random.html | sed 's|<h2| (c) <h2|g' | awk '/quote-p/,/<\\/h2>/{print $0}' ; \
exit 0
"""
```

```coffee
# *** Now ***
command: (callback) ->
  isOnline = window.navigator.onLine
  storage = window.localStorage
  if isOnline
    console.log('online get from internet')
    cmd = "curl -L -s http://greatwords.ru/random | sed 's|<h2| (c) <h2|g' | awk '/quote-p/,/<\\/h2>/{print $0}'"
    @run cmd, (error, data) ->
      storage.setItem('greatwords.ru', data)
      callback(error, data)
   else
     console.log('offline get from storage')
     callback(null, storage.getItem('greatwords.ru'))
```

Works like a charm! )

**Comment by felixhageloh** [comment]
great! Did you build the app yourself, because I didn't release the fix yet :)?

**Comment by vkravets** [comment]
@felixhageloh partially =))) build only server part and override it on application folder )
