### ISSUE TITLE
It seems after returning from sleep webvew was reset

### ISSUE THREAD

**Issue by vkravets** [felixhageloh/uebersicht#228]
Found very strange behavior after usage webview localStorage

After returning from sleep there is no any data in localStorage it seems that browser (webview) was recreated.

I'm not sure that it's right behavior...

@felixhageloh is it possible to prevent such behavior but only going to sleep instead of recreation?

Because all internal states of webview is reseting during such user case

1. Run uebersicht
2. Make sure that all widgets run and show needed info
3. create widget which store something in localstorage and show it
4. close the notebook
5. Open fill the passowrd, look at the desktop... which wich show data from localstorage is empty...

**Comment by felixhageloh** [comment]
Good find, I will look into it! So far localstorage seemed to just work, but I guess I was wrong ...

**Comment by felixhageloh** [comment]
I finally got to looking into this. Can you confirm this issue? I just tried it and even after restarting my machine my localstorage was persisted

**Comment by felixhageloh** [comment]
closing for now - please ping me if you still have this issue
