### ISSUE TITLE
Widgets do not show up in new "desktop" space

### ISSUE THREAD

**Issue by atticusmatticus** [felixhageloh/uebersicht#231]
When I open a new desktop workspace (mission control) the widgets do not show up in the new space. Quitting ubersicht and relaunching (with both desktop spaces open) is the only way the widgets will show up in both spaces.

macOS 10.12 Macbook Pro

**Comment by nicjohnson145** [comment]
I have a similar problem, my instance will just stoping showing up when I simply switch between spaces. However it doesn't do it every time. 

OSX 10.10 Macbook Pro

**Comment by felixhageloh** [comment]
I can confirm this bug. I have a fix that will be released shortly!

**Comment by felixhageloh** [comment]
should be fixed in 1.0.44 released today

**Comment by eramdam** [comment]
Sorry to bump a very old thread but I figured it might be better than to open a duplicate issue.

I'm seeing this almost consistently on macOS 10.14.6 and 1.40.60, I have to basically tell Ûbersicht to refresh all the widgets every time I create a new space in Mission Control (which unfortunately happens quite a lot depending on the days..)
