### ISSUE TITLE
define global styles

### ISSUE THREAD

**Issue by hhsnopek** [felixhageloh/uebersicht#236]
I couldn't find an issue on this, but also haven't tried it out. I'd like to make global styles that affect **all** widgets - is this at all possible? I'm redefining styles way too many times for my liking. Is there a way to include a single css file instead of defining them within each widget?

```
.widget
  color: #333
  ...
```

**Comment by felixhageloh** [comment]
There is no way to include a global stylesheet at the moment. I think some people have written widgets that only add global styles as a workaround. Now that you can include npm modules, though, I think there is a nicer solution:

You could make a module/package with shared styles like 
`lib/sharedStyles.json`

```json
{
  "textColor": "#333",
  "someOtherStyle": "stuff"
}
```

and then include in your widgets:
`widget1.coffee`

```CoffeeScript
styles = require('./lib/sharedStyles')

command: "..."
style: """
  color: #{styles.textColor}
"""
```

**Comment by felixhageloh** [comment]
obviously you would add the same to all widgets that share this style

**Comment by hhsnopek** [comment]
hmm, I think I'll just end up injecting & loading the global file as I have styles that relate based on classname

**Comment by hhsnopek** [comment]
This could be a nice feature for the future tho! maybe just a directory named `css` that holds all css/stylus files and it would just add them to the DOM onload

**Comment by felixhageloh** [comment]
Noted! I will close this issue, since it is phrased as a question. 

As as side note, the package approach might seem cumbersome compared to CSS, but it has the advantage that
- it is more explicit, i.e. it is very obvious where you are inheriting which style
- it doesn't introduce a new 'thing' - it's just CommonJS modules all the way (widgets are actually also modules even though it is not obvious)

**Comment by hhsnopek** [comment]
Yeah - I'm not opposed to using a package, but it doesn't solve my problem of redundancy - great for another use case where I'm using similar logic, just not the answer for me in this case. Thank you for the timely responses! Love the app!

**Comment by felixhageloh** [comment]
Thanks, btw you might find this thread interesting as well https://github.com/felixhageloh/uebersicht/issues/125
