### ISSUE TITLE
Ubersicht not refreshing

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#237]
I seem to have an intermittent problem with ubersicht refreshing itself the first thing in the morning. After the machine has woken up from sleep I am finding that I sometimes have to quit the app and restart it to make it work again. Just selecting the 'refresh all widgets' option from the menu does not work. Also it seems that this has only started occurring after the mac update to Sierra. I am not 100% sure about this part but am fairly confident this did not happen prior to the update. I have deleted/reinstalled the app (version 1.0 44) with no help.

Any ideas or how to tell what is going on?

**Comment by mlcampbe** [comment]
Still seeing the same initial refresh problem. Seems to occur about 50% of the time when I first wake the machine in the morning. 

Thinking out loud could this be related to a widget for some reason? I only have a couple of widgets enabled (display ical appointments, weather, and IP address) so not sure if that would be related or not.

I did open the ubersicht console to try to identify a problem but nothing there nor anything that looks odd in the mac console.

Any other ideas?

**Comment by felixhageloh** [comment]
No, 'luckily' I have the same issue now on my new laptop :). Hoping to have a fix soon - just have been crazy busy the last 2 months!

**Comment by felixhageloh** [comment]
This should be fixed with the latest release (1.1.45). Please re-open if you still have this issue!
