### ISSUE TITLE
preview widget

### ISSUE THREAD

**Issue by edoardoc** [felixhageloh/uebersicht#239]
Hello,

is there a way to preview the widget without having to "Refresh All widgets"? 
(or is there any development environment I can write widgets in coffeescript)

thanks

**Comment by hawkrives** [comment]
Usually, the widget will update as soon as you save it. 

If you open edit the widget (with something like [TextMate][] or [Sublime Text][]), and, say, change the background color, does the widget not update as soon as you push cmd-s?

[TextMate]: https://macromates.com/download
[Sublime Text]: https://www.sublimetext.com/3

**Comment by edoardoc** [comment]
it does, but I am on a small screen and I have to move away the editor to
focus on the desktop, that can take time: isn't it possible to use... let's
say chrome to preview the widget?


—
Edoardo

**Comment by hawkrives** [comment]
Sure! Point Chrome to <http://localhost:41416> and you should see all your widgets there.

**Comment by felixhageloh** [comment]
you could also use the 'show desktop' gesture or keyboard shortcut to see the changes. Should take about the same amount of time than switching from your editor to chrome

**Comment by felixhageloh** [comment]
(closing this issue for now, but feel free to follow up with more questions)

**Comment by edoardoc** [comment]
hey! thanks a lot, this is exactly what I was looking for :)
