### ISSUE TITLE
Can't find variable: domEl

### ISSUE THREAD

**Issue by vacano** [felixhageloh/uebersicht#240]
Hey  guys,
Just installed this awesome program on my macbook with 10.12.1 macOSx

I see a small writing on the top lefto corner saying **Can't find variable: domEl**

And the very few widgets I have tried so far, do not show up properly on my desktop.

Any help would be appreciated!
Thanks!

**Comment by felixhageloh** [comment]
Hey there!. It sounds like one of the widgets you installed has an error, causing all the other ones to break as well. You could try removing them all and adding them again one by one to find out which one

**Comment by felixhageloh** [comment]
closing for now. Feel free to follow up with questions tho!
