### ISSUE TITLE
Unable to select multiple files on desktop

### ISSUE THREAD

**Issue by simo2409** [felixhageloh/uebersicht#241]
Usually I select spare files via command+click clicking on file's icons on desktop.

Recently I found it's not working anymore (I'm sure it was working not far in the past so it should be a bug recently introduced.

I'm running Übersicht 1.0 (44)

The problem arises only selecting spare files, click&drag works as usual

**Comment by hawkrives** [comment]
Is your Übersicht interaction key set to cmd? You can see it in the preferences. (I think that's the default.)

**Comment by felixhageloh** [comment]
I think @hawkrives  is on the right track: it is the interaction shortcut key that is interfering. You can change it to some other key (or disable it) - that should fix the issue

**Comment by simo2409** [comment]
Confirmed! Changing interaction shortcut solved! Thanks a lot!
