### ISSUE TITLE
WorldClock widget - 24h time

### ISSUE THREAD

**Issue by maikeru1202** [felixhageloh/uebersicht#244]
Is there a way to change the times to the 24H format?

**Comment by maikeru1202** [comment]
Figured it out.  To be clear, this is for the World Clock widget by Chris Johnson.

In the WorldClock.sh file, for all cities and regions:
change:   +'%-l:%M %p'
to:  +'%H%:%M'

**Comment by felixhageloh** [comment]
great you figured it out!
