### ISSUE TITLE
Alternative examples

### ISSUE THREAD

**Issue by skonesam** [felixhageloh/uebersicht#245]
Felix,

A few things… You rock. This project rocks; it's among the most useful features of my computing setup.

Second, pretty sure I'm an outlier here, but wanted to mention an alternative setup using Übersicht. Because it came out as Swift was, and because I needed an excuse to play with Swift, several of my widgets are simply calls to self-written Swift command-line applications. The Swift part, of course, isn't important; would work fine with anything. 

I have a weather widget that works this way, as does a stock market watching one, as does a display of my car trips (via the Automatic service and a simple text file integration with IFTTT).The programs generate the HTML and "print" it; Übersicht happily displays it. CSS is in the widget. Not the most straightforward setup, but it works great.

Thanks again for your hard work on this!

Best,
Pat

(Yeah, I know this isn't an "issue," unless you really stretch the definition to include "possible things for the very bottom of the readme." Sorry!)

**Comment by felixhageloh** [comment]
Hey Pat, thank you very much for the kind words :)! Great to hear that you have successfully been using 'server side rendering', if you will, for Übersicht. Also good for me to know about this use case for future changes, so thanks for opening this issue.

Btw I think I also get your previous comment now, mentioning that you want to refresh widgets via AppleScript when data changes. I can imagine it is less straight forward to achieve (and maybe impossible?) with your setup. I am hoping to release the scripting support soon - a few small things to iron out still.

**Comment by felixhageloh** [comment]
I think I might close this issue btw - I am aware of the use case now and I need to get better at managing the issue list :)
