### ISSUE TITLE
Using osascript to change desktops does not work

### ISSUE THREAD

**Issue by apierz** [felixhageloh/uebersicht#246]
I want to change my current desktop by clicking on a widget. I can change desktops using this script:

    osascript -e 'tell application "System Events" to key code 18 using control down'

I can get this script to work in terminal, bash scripts and using
 
    osascript screenOne.scpt

When I try to use it in my widget it does not work:

    $(".one").on 'click', => @run "osascript -e 'tell application \"System Events\" to key code 18 using control down'"

Other scripts work fine, e.g.

    $(".one").on 'click', => @run "osascript -e 'tell application \"iTunes\" to previous track'"

I've tried giving Ubersicht access to change my computer in the settings menu, but that did not have an effect.

I've also tried having the widget run the .scpt file and running the script in a bash file:

    $(".one").on 'click', => @run "sh screenOne.sh"

But this does not work with Ubersicht, though it works fine in terminal.

**Comment by felixhageloh** [comment]
Do you have `control` configured as your interaction shortcut by any chance?

**Comment by apierz** [comment]
I am using command for my interaction shortcut.

**Comment by apierz** [comment]
I think that's the issue. Thanks for the advice.
