### ISSUE TITLE
Übersicht blinks when opening certain apps

### ISSUE THREAD

**Issue by stfkbf** [felixhageloh/uebersicht#247]
This is a relatively minor thing, but since version 1.1 (45) Übersicht now seems to refresh when opening and closing certain apps on MacOs Sierra (version 10.12.2), for example Photos for Mac. Is there a way to prevent this?

Thank you for a great tool and apologies if this has been reported already.

**Comment by felixhageloh** [comment]
It sounds like this known issue: https://github.com/felixhageloh/uebersicht/issues/189
Basically, when certain graphics heavy apps open it causes a graphics card switch (if you own a mac that has several graphic cards, as most MacBooks do). To Übersicht it looks a like a new screen has been connected when this happens, so it refreshes to render on the new screen, which is what is causing the blinking. 

I have not found a workaround yet unfortunately. I will close this issue as a duplicate - you can track the Issue I linked to see if there is any progress on this!
