### ISSUE TITLE
Upcoming-iCal-Events.  CoreData: warning: dynamic accessors failed....

### ISSUE THREAD

**Issue by maikeru1202** [felixhageloh/uebersicht#248]
Was working fine, but now getting this error:

CoreData: warning: dynamic accessors failed to find @property implementation for 'uniqueId' for entity ABCDInfo while resolving selector 'uniqueId' on class 'ABCDInfo'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?
CoreData: warning: dynamic accessors failed to find @property implementation for 'uniqueId' for entity ABCDContact while resolving selector 'uniqueId' on class 'ABCDContact'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?

Checked and confirmed that Ubersicht has access in security & privacy (for contacts, calendars, and reminders).  

Any ideas how to fix?

**Comment by felixhageloh** [comment]
sorry for the late response - I had a look at this a few times but I am quite sure this is nothing related to  Übersicht. If you think it still might be the case feel free to re-open again!
