### ISSUE TITLE
Node module not defined

### ISSUE THREAD

**Issue by motleydev** [felixhageloh/uebersicht#249]
I am using the newer JSX syntax for my widget.
This is how my command (and require's) looks:

    const getData = require('./lib/systemUtils.js')
    export const refreshFrequency = 5000;
    export const command = function (callback){
      callback(null, getData())
    };

In my systemUtils file I have this code:

    const _ = require('lodash');
    const exec = require('child_process').execSync;
    const output = {};
    const data = exec('system_profiler SPDisplaysDataType').toString()

In my console, I am getting the error that "exec" is not defined. What am I missing?

**Comment by hawkrives** [comment]
Übersicht "bundles" your code before running it – it essentially loads a transparent web browser over your desktop, where it renders the widgets. As such, the bundle can only contain code that can run in a web browser – so no `fs`, `child_process`, or `http` modules. `path`, or `querystring`, or most js-only libraries on npm should work, though.

As far as I know, the only way you can run another command in Übersicht is with the traditional `command` feature, which runs in a shell and passes stdout and stderr to the rest of your widget.

**Comment by motleydev** [comment]
Hey @hawkrives - thanks for the response. If I understand it then, the switch is basically "if command get's a string - execute it in a shell, if it get's a function, execute it on the front-end" - does that seem about accurate? @felixhageloh?

**Comment by motleydev** [comment]
Is there a way to run multiple shell commands and pipe them on to the next render? Like run this system check, concat that text file, etc.. ?

**Comment by hawkrives** [comment]
Um, only through shell commands, I think; but, IIRC, you can run multiple commands in a few ways with bash:

```bash
# if you want to stop the subsequent commands if one errors
echo a && echo b && echo c

# if you want to run all the commands, no matter the error status
echo a; echo b; echo c
```

You could echo a specific delimiter between sources, like `system_config; echo "::::::::::::::"; cat text_file`, and then split the widget input on the delimiter you echoed?

--- 

As to your other question, yeah, that's pretty much it, I think. See [`server/src/runCommand.js`](https://github.com/felixhageloh/uebersicht/blob/master/server/src/runCommand.js) and [`server/src/command_server.coffee`](https://github.com/felixhageloh/uebersicht/blob/master/server/src/command_server.coffee#L8).

**Comment by felixhageloh** [comment]
@motleydev to answer your earlier question: yes, if the command is a function it will run on the frontend. If it is a string it is assumed to be a shell command.

For running multiple commands you'd have to use  https://github.com/felixhageloh/uebersicht#runcommand-callback. You could call several commands inside of your command function, although coordinating the responses might get tricky. Another option might be to write a little node app that does all the system commends and call that from Übersicht.

**Comment by hawkrives** [comment]
@felixhageloh Is `this.runCommand` available on the jsx widgets, or only in the coffeescript variant?

**Comment by felixhageloh** [comment]
ah yes sorry. You have access to it as a module:

```javascript
const run = require('run');
```

I am traveling for work right now so I only had a quick look at this :)

**Comment by hawkrives** [comment]
oh, nice! adding that to my bag o' tricks :)
