### ISSUE TITLE
Setup Command and Update Command

### ISSUE THREAD

**Issue by motleydev** [felixhageloh/uebersicht#250]
I would like to be able to run two different commands following the update and setup paradigm. I make a system profile command to fetch some generic display info like resolution, width/height, etc. I don't need to check that every time. 

Another possibility could be making local display data a first class citizen and giving it a global object in Ubersicht land. Such that the output object is something like {err, output, system}

**Comment by felixhageloh** [comment]
would `@run` work for this use case https://github.com/felixhageloh/uebersicht#runcommand-callback?

**Comment by motleydev** [comment]
Yah! I actually saw that after I posted. Mean to come back in and clean up the post. Thanks.
