### ISSUE TITLE
update method called too often

### ISSUE THREAD

**Issue by tuesd4y** [felixhageloh/uebersicht#256]
Hey, I just got into programming übersicht widgets. I've written a widget for jira to show the activity stream on the desktop. The problem I currently have is that the update method is called way to often and at the end stops calling the renderItem method. Which results in an empty element.

Screenshot of the debug console

<img width="903" alt="screen shot 2017-02-09 at 17 06 29" src="https://cloud.githubusercontent.com/assets/13107179/22792161/267218fe-eeec-11e6-9930-6f5e9ec24363.png">

Code: 

```coffeescript
  render: (output) ->
  console.log "j_render"
  if(!output)
    return
  """
  <div id="#{@project.id}">
    <div class="header">
      <span class="project-title">#{@project.title}</span>
      <div class="controls"></div>
    </div>
    <div class="jira-activity-stream">#{output}</div>
  </div>
  """

afterRender: (widget) ->
  # this is a bit of a hack until jQuery UI is included natively
  $.ajax({
    url: "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js",
    cache: true,
    dataType: "script",
    success: ->
      $(widget).draggable()
      return
  })

update: (output, widget) ->
  console.log "j_update"

  entries = $(output).find("entry")
  ele = $(widget).find('.jira-activity-stream')
  ele.empty()

  for entry in entries
    ele.append @renderItem(entry)

 renderItem: (data) ->

     console.log "j_renderItem"

     title = $(data).find("title").text()
     subject = $($(data).find("content").text()).first().text() + " " + $($($(data).find("content").text())[1]).text().trim()

     date = new Date($(data).find("published").text())
     days_ago = Math.round((new Date()-date)/(1000*60*60*24))

     if days_ago < 1
       hours_ago = Math.round((new Date()-date)/(1000*60*60))
       if hours_ago < 1
         date = "recently"
       else if hours_ago == 1
         date = hours_ago + " hour ago"
       else
         date = hours_ago + " hours ago"
     else if days_ago == 1
       date = days_ago + " day ago"
     else
       date = days_ago + " days ago"

     """
     <div class="row">
       <div class="title">#{title}</div>
       <div class="subject">#{subject}</div>
       <div class="line3">
         <span class="date">#{date}</span>
       </div>
     </div>
     """
```

**Comment by felixhageloh** [comment]
Hey there! What is your refresh frequency? The update method gets called every time the widget refreshes, so you can control how fast it gets called (by setting refreshFrequency to a higher number)

**Comment by tuesd4y** [comment]
Currently it's set to 30m. I've tried a few other frequencies like 2m, 60000, 1h but the result was always the same as the one shown above.

**Comment by felixhageloh** [comment]
is code you posted the full code of your widget?

**Comment by tuesd4y** [comment]
no it's not, here is the whole widget:
[jira.coffee.zip](https://github.com/felixhageloh/uebersicht/files/777852/jira.coffee.zip)

**Comment by felixhageloh** [comment]
Sorry for the late reply - I only had the time to have a quick look so far and I noticed that you have some syntax mistakes in your widget. Coffeescript is quite strict about white space, so if your code is indented wrong it might have unexpected consequences (and should usually not even compile)

Here is one example:
![screen shot 2017-02-27 at 14 00 16](https://cloud.githubusercontent.com/assets/367503/23362265/4f73e324-fcf5-11e6-8f71-3b69f254019e.png)

the code inside `renderItem: ->` should be indented by two spaces, not four.

If you still have problems after you fix those syntax errors, let me know and I can have a closer look again. Hope this helps!

**Comment by felixhageloh** [comment]
closing for now. Feel free to follow up if you still have questions!
