### ISSUE TITLE
afterRender On Click => Update of CSS

### ISSUE THREAD

**Issue by Cybermancer3D** [felixhageloh/uebersicht#258]
Hi everybody,

I started playing around with Übersicht a few months ago and so far was able to resolve all 'hurdles' I came across myself except the latest one:

I would like to be able to click on an image which should then update the CSS property of a div (specifically: change the CSS property 'visibility' from 'hidden' to 'inline').

afterRender: (domEl) ->
  $(domEl).on 'click', '#button', ->
    $(domEl).find(".myDIV").css visibility: inline
  
style: 
.myDIV
  position: fixed;
  top: 60px;
  left: 280px;
  display: inline;
  height: 20px;
  visibility: hidden;
  color: #6C9BAB;
  font-family: Helvetica Neue;
  font-size: 8px;

Can anybody please help me out?

**Comment by felixhageloh** [comment]
`visibility` only accepts `hidden`, `visible` and `collapse` (just found out about that last one as well). I believe you want `display: 'inline'`

**Comment by felixhageloh** [comment]
or maybe you need `visibility: 'visible'` since you are already setting display to inline in your CSS

**Comment by Cybermancer3D** [comment]
Thank you for the quick reply and your suggestions.

Changing the code to `visibility: 'visible'` did it.

Thanks a lot!
