### ISSUE TITLE
Cant click any widget

### ISSUE THREAD

**Issue by victorfonsec4** [felixhageloh/uebersicht#259]
Tried multiple widgets with clickable features and none of them worked. Any suggestions?

**Comment by begsthehessian** [comment]
Did you go to the Toolbar? 
Toolbar -> Preferences -> Interactive Shortcut (disabled on fresh install) and choose a shortcut.  

![image](https://cloud.githubusercontent.com/assets/21159671/23281507/d8b7266c-fa1d-11e6-9032-e31765086a43.png)

**Comment by victorfonsec4** [comment]
Thanks! I saw that and thought none meant you didn't need to press anything to interact =B.
