### ISSUE TITLE
Why can't I implement this JavaScript into Ubersicht?

### ISSUE THREAD

**Issue by Gallost** [felixhageloh/uebersicht#261]
Here's the file:
[snowstorm.zip](https://github.com/felixhageloh/uebersicht/files/812440/snowstorm.zip)

And here's the link to where I found the code:
https://jsfiddle.net/michelepisani/mdsw0wto/

Sorry if this seem obvious to some of the pros, but I am a complete newbie who just came across this amazing application yesterday and I have no idea how to work things out.

**Comment by Porco-Rosso** [comment]
If you can find a hosted page of your effect you can try to pull it off in the same iframe method I used here: 
https://github.com/Porco-Rosso/Ubersicht-Matrix

**Comment by Gallost** [comment]
Thank you so much for giving your advice! It worked out perfectly and it feels like dream come true! Would you mind if I re-post this snowstorm effect on to the Ubersicht widget website if I credit it to you? Btw here is what my desktop look like rn:
[Lol.zip](https://github.com/felixhageloh/uebersicht/files/819661/Lol.zip)

**Comment by Porco-Rosso** [comment]
Glad I could help.
Feel free to post it. hope your CPU isn't hurting too much.

**Comment by felixhageloh** [comment]
closing for now. Thanks for your help @Porco-Rosso
