### ISSUE TITLE
node module test fails WIDGET_ADDED

### ISSUE THREAD

**Issue by bauen1** [felixhageloh/uebersicht#263]
The test in `server/spec/backend/reducer_spec` fails due to the new hide feature.

It might be good to setup travis (or something like that) to run all the tests on the modules for every push, incase people forget about them.

**Comment by felixhageloh** [comment]
thanks for the heads up - got a busy week but I'll see if I can fix the specs. Some sort of CI would also be handy, but probably overkill for now since it is mostly me committing

**Comment by bauen1** [comment]
It wouldn't have to actually build stuff, just run the tests which really helps if you commit stuff and are too lazy / don't have the time to do a clean build beforehand

**Comment by hawkrives** [comment]
I'm taking a stab at automating Übersicht tests through TravisCI, as it's about the only CI provider I know of that can do free, unlimited OS X builds. And I like their service.

I'm working in my fork, [hawkrives/uebersicht#travis](https://github.com/hawkrives/uebersicht/tree/travis), and I'll make a PR once I've got it running.

**Comment by felixhageloh** [comment]
Spec is fixed btw
