### ISSUE TITLE
Widget on top of other widgets?

### ISSUE THREAD

**Issue by tristan-k** [felixhageloh/uebersicht#273]
I'm using a fullscreen video widget with the following code. How do I make widget appear on top of that widget?

```
render: ->"""
  <video width="1880" loop autoplay>
    <source src="b8-1_compressed.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>
"""

style: """
  top: 0px
  left: 0px
  border: 0px solid #fff
  z-index: 1000
  video
  margin-bottom: -4px
```

**Comment by hawkrives** [comment]
It should show on top if you add a higher `z-index` to the widget that you want on top.

**Comment by felixhageloh** [comment]
labeled as a question and closed the issue, but feel free to follow up if you have more questions
