### ISSUE TITLE
bash: line 2 shell_session_update: command not found 

### ISSUE THREAD

**Issue by stjagu** [felixhageloh/uebersicht#275]
Updated to 1.2 (46) and am now seeing "bash: line 2 shell_session_update: command not found" on certain widgets.

**Comment by hawkrives** [comment]
Is it always the same widgets, or does the error move around between widgets?

If it's always the same ones, can you upload the code for one of the widgets?

**Comment by felixhageloh** [comment]
It is most likely an issue with RVM (I'm on the road so I don't have a link right now). In any case, I've released 1.2.47 which removes the bash env feature again. This should fix this for now

**Comment by levifig** [comment]
Probably related, I can't seem to use `jq` with it… I have a bash script that works fine in the shell, but the widget running it outputs `jq: command not found`…

**Comment by felixhageloh** [comment]
1.2.48 has just been released with the option to load your bash env. 
@levifig if you enable this option, you will probably be able to use the `jq` command. 
@stjagu in your case you can leave the option off and things should keep working as before version 1.2
