### ISSUE TITLE
Latest update can not parse JavaScript widgets

### ISSUE THREAD

**Issue by imranzahid01** [felixhageloh/uebersicht#278]
I do not know much about coffee script therefore I wrote my widgets in JavaScript.
With the latest update (1.2 (47)) all my JavaScript widgets stopped working. To reproduce use the follow code in and index.js file:

```javascript
command: "echo Hello World! ",
refreshFrequency: '1m',

render: function (output) {
  return "<div><h1>" + output + "</h1></div>";
}
```

The above will work fine, however if your DOM is multi line and you do the following:
```javascript
command: "echo Hello World! ",
refreshFrequency: '1m',

render: function (output) {
  return "\
    <div><h1>" + output + "</h1></div>\
    <div><h2>" + output + "</h2></div>\
  ";
}
```

The the final dom which is rendered is:

```javascript
<div id="sample-index-js" class="widget">undefined</div>
```

multiline style like the following:

```css
style: "                                  \n\
  bottom: 1px                             \n\
  left: 1350px                            \n\
  font-family: Helvetica Neue             \n\
  font-size: 11px                         \n\
  color: #fff                             \n\
",
```

works fine, it is just what is under the `render` that is not working

**Comment by felixhageloh** [comment]
Thanks for reporting, I will look into it! I've updated a few dependencies (including babel) which could be the reason for this happening

**Comment by felixhageloh** [comment]
I need to investigate further on why this is happening now, but I noticed that you can fix the issue by wrapping your return statement in brackets, like:

```javascript 

command: "echo Hello World! ",
refreshFrequency: '1m',

render: function (output) {
  return("\
    <div><h1>" + output + "</h1></div>\
    <div><h2>" + output + "</h2></div>\
  ");
}
```

**Comment by hawkrives** [comment]
FWIW, babel parses the multiline version correctly (which doesn't mean it's not to blame): [online example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=let%20w%20%3D%20%7B%0A%0Acommand%3A%20%22echo%20Hello%20World!%20%22%2C%0ArefreshFrequency%3A%20'1m'%2C%0A%0Arender%3A%20function%20(output)%20%7B%0A%20%20return%20%22%5C%0A%20%20%20%20%3Cdiv%3E%3Ch1%3E%22%20%2B%20output%20%2B%20%22%3C%2Fh1%3E%3C%2Fdiv%3E%5C%0A%20%20%20%20%3Cdiv%3E%3Ch2%3E%22%20%2B%20output%20%2B%20%22%3C%2Fh2%3E%3C%2Fdiv%3E%5C%0A%20%20%22%3B%0A%7D%0A%0A%20%20%0A%7D)

**Comment by felixhageloh** [comment]
I've pinpointed the problem https://github.com/jquery/esprima/issues/1829. 

Until it is fixed in esprima I will see if I can downgrade to an older version again.

**Comment by imranzahid01** [comment]
I did an upgrade (again) and updated all my scripts to include brackets in the return statement as you have suggested and it works fine for now.

Even though you may fix the issue by either downgrading the esprima library or the library fixing the issue, I think in your readme file for there should be instructions for JavaScript users to always return render output in brackets. Similarly the example widget should be updated as well. This is just as a precaution in case something else breaks later down the road.

**Comment by felixhageloh** [comment]
yeah sorry for the flood of updates 😁 

I'm unsure about advising people to use brackets for multiline string return statements - a different bug might break different syntax, so there is no guaranty that using brackets will protect you from it. 

In any case, I am hoping to release this fix soon and for now there is a workaround!

**Comment by simonhaenisch** [comment]
I just switched from geektool to übersicht and wanted to use js instead of coffeescript (because I never used it), and came across this issue.

Why don't you use [template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals) for your multiline strings?

This is the javascript widget boilerplate code I came up with that works well for command line stuff:

```js
command: `date "+%H:%M"`,

refreshFrequency: '1s',

render: res => `<pre>${res}</pre>`,

style: `
-webkit-font-smoothing: antialiased
top: 20px
left: 20px

pre
  margin: 0
  font-family: "Source Code Pro"
  font-size: 16px
  font-weight: 700
`
```

btw i believe that ES6+ javascript is nicer to write than coffeescript, you might want to consider focussing more on it for this project 🤓  love übersicht, the geektool UI freaked me out 😝

**Comment by felixhageloh** [comment]
@simonhaenisch ES6 widgets + JSX are in a beta stage (for quite some time now 😳 ). You can see an example here https://gist.github.com/felixhageloh/94d5dd41cc5ff8a633900ffb28bd195a

Let me know if you have any questions and I am glad to get feedback

**Comment by felixhageloh** [comment]
Have been waiting for esprima to fix the issue, but it hasn't happened so far. If downgraded in v1.2.53 released today, so this should be fixed again
