### ISSUE TITLE
Calling a JS function in the render

### ISSUE THREAD

**Issue by edasque** [felixhageloh/uebersicht#281]
Hi,

While https://github.com/felixhageloh/uebersicht/issues/44 touches upon some of these it's more about bringing in JS files than calling JS within the render.

I have code that does this:
```
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/jquery.sparkline.min.js"/>
  <script type="text/javascript">
    $(function() {
        /** This code runs when everything has been loaded on the page */
        /* Inline sparklines take their values from the contents of the tag */
        $('.inlinesparkline').sparkline(); 
    });
    </script>

Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.

```

The js file gets loaded, in fact I can run ```$('.inlinesparkline').sparkline();``` interactively in the debug console and it works but the function above never gets called AFAIK.

@felixhageloh how would you handle this?

Erik

**Comment by hawkrives** [comment]
@edasque Can you post more of your problematic widget for us to debug with, please?

**Comment by edasque** [comment]
@hawkrives sure, how about this:
The full code could look like this:
```
command: ""

refreshFrequency: 160000

style: """
right 10px
bottom 550px
width 100px
height 45px
color white
"""

render: -> """
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/jquery.sparkline.min.js"/>
  <script type="text/javascript">
    $(function() {
        /** This code runs when everything has been loaded on the page */
        /* Inline sparklines take their values from the contents of the tag */
        $('.inlinesparkline').sparkline(); 
    });
    </script>
  <h1>HERE</h1>
Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.

"""
```

And it should look like this:

<img width="120" alt="screenshot_6_29_17__1_51_pm" src="https://user-images.githubusercontent.com/219187/27702483-35fd2ff8-5cd2-11e7-9106-2a4043e3d55c.png">

But it looks like this:

<img width="112" alt="screenshot_6_29_17__1_51_pm" src="https://user-images.githubusercontent.com/219187/27702511-4467deee-5cd2-11e7-9404-c7a12a2a92e6.png">

Because $('.inlinesparkline').sparkline();  is never called, because the jquery .ready() function which short form is ```$(function() {}``` is never executed

**Comment by hawkrives** [comment]
Offhand, I'm not sure why it wouldn't work.

… ah, wait one sec.

Try changing your `render` to this:

```html
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/jquery.sparkline.min.js"></script>
  <script type="text/javascript">
    $(function() {
        /** This code runs when everything has been loaded on the page */
        /* Inline sparklines take their values from the contents of the tag */
        $('.inlinesparkline').sparkline(); 
    });
    </script>
  <h1>HERE</h1>
Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.
```

If that works, it's because you can't have a `script` tag close itself, so it's consuming the rest of the document until it finds `</script>`, which is after the call to `.sparkline()`. So the browser engine is either using the content of the script tag or the `src` attribute; I forget which one wins.

**Comment by edasque** [comment]
I hear what you're seeing, made the change to see if that makes any difference but it didn't.

I did manage to get it working by taking the function and putting it in an external resource I link to like the first one.

```
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/jquery.sparkline.min.js"></script>
  <h1>OK</h1>
Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/sparkline.run.js"></script>
```

@felixhageloh could you take a look and suggest a better solution? This is less than ideal.

**Comment by hawkrives** [comment]
@edasque Just to check, what if you just call the sparkline function from a script element after your declare the data for it? That is, declare the data, then call the function, so that there's no need for the jQuery.ready functionality?

**Comment by edasque** [comment]
@hawkrives the following doesn't help if that's what you're suggesting:

```
  <script type="text/javascript" src="http://bunchofjson.s3-website-us-east-1.amazonaws.com/jquery.sparkline.min.js"></script>

  <h1>OK</h1>
Inline Sparkline: <span class="inlinesparkline">1,4,4,7,5,9,10</span>.
    <script type="text/javascript">
        $('.inlinesparkline').sparkline(); 
    </script>
```

but I think that's simply because inline JS doesn't seem to work:
```
    <script type="text/javascript">console.log("BOB");</script>
```

Doesn't output anything in the console.

**Comment by felixhageloh** [comment]
I think the best solution would be using an npm / ES6 module, like https://www.npmjs.com/package/sparkline
https://www.npmjs.com/package/sparklines

that way you can just `require` the library and use your render or afterRender function to draw

**Comment by felixhageloh** [comment]
If you must use the jquery plugin, you need to call 

` $('.inlinesparkline').sparkline(); ` in your afterRender method. However, there is no way to ensure the jquery plugin has loaded yet, afaik (you don't have to worry about whether jQuery itself is loaded - widgets are only started after page load)

**Comment by felixhageloh** [comment]
closing for now - feel free to follow up with question of course!
