### ISSUE TITLE
High energy usage normal?

### ISSUE THREAD

**Issue by phlind** [felixhageloh/uebersicht#283]
Hi,

I just would like to ask if it's normal that Übersicht has such a high energy usage?

![bildschirmfoto 2017-07-22 um 20 31 58](https://user-images.githubusercontent.com/30386310/28498923-ce2c37e4-6fa9-11e7-8ce4-33d144bffae9.png)

Normally apps that run in the background have an index of around '1', but currently Übersicht uses '24' on average (Firefox for example uses '17'). Maybe it could have something to do with my setup or is that normal? 

Thanks

------
**Edit**: I found that it's not Übersicht, but a certain widget (circulat-battery-js) which causes the high energy usage. So I will ask there for help. Thanks

**Comment by felixhageloh** [comment]
Hey, sorry for the late reply. Glad you identified the widget!
