### ISSUE TITLE
BUG: Near Constant Parse Errors

### ISSUE THREAD

**Issue by gethubguy** [felixhageloh/uebersicht#285]
two of my three widgets that have been operating fine for quite some time now spit out parse errors  incessantly ... i've attached a screen shot of the notification errors
<img width="322" alt="screen shot 2017-09-03 at 2 36 22 pm" src="https://user-images.githubusercontent.com/9064491/30005670-8b6298e0-90b5-11e7-8fcf-37ff01f4317a.png">

**Comment by hawkrives** [comment]
@gethubguy Can you attach the widgets in question, or point us to where you got them from?

Did you recently update Übersicht?

**Comment by gethubguy** [comment]
I got them off the widget store :-) http://tracesof.net/uebersicht-widgets/ sorry i didn't respond - my notifications went to spam

**Comment by felixhageloh** [comment]
@gethubguy did you get these errors from a fresh install or after you modified those widgets?

**Comment by felixhageloh** [comment]
closing for now.  Feel free to follow up tho
