### ISSUE TITLE
Create scrollable div with links that work?

### ISSUE THREAD

**Issue by imtoobose** [felixhageloh/uebersicht#287]
I want to create a scrollable widget with multiple links that I want opened through the browser. The links show up, but if I use overflow-y: scroll in the CSS, and even force the scrollbar to show I can't actually use the scrollbar. Also, the links aren't clickable.

Is there a way for me to make this work?

**Comment by felixhageloh** [comment]
You can scroll only while Übersicht is in the foreground. You can bring it into the foreground by pressing the interaction shortcut key (you can configure it under preferences) 
This works quite well for pressing links, but I can imagine it won't give you the scrolling UX you would like.

**Comment by felixhageloh** [comment]
closing this issue because it is a question, but feel free to follow up in this thread!
