### ISSUE TITLE
Widget background not immediately refreshing on automatic wallpaper change

### ISSUE THREAD

**Issue by nanobra1n** [felixhageloh/uebersicht#288]
Is it possible to refresh widgets when the wallpaper changes? I have my wallpapers set to change automatically every 30 minutes and I notice that the background of my widgets (using   -webkit-backdrop-filter: blur(10px) still uses the wallpaper change (at least for a while, eventually it catches up)

**Comment by felixhageloh** [comment]
Are you on High Sierra? I have the same issue since upgrading. Fix coming soon!

**Comment by nanobra1n** [comment]
Yes, I am indeed.

Thanks

**Comment by felixhageloh** [comment]
Should be fixed in version 1.2.51 released today
