### ISSUE TITLE
Cannot refresh using AppleScript: variable refresh is not defined.

### ISSUE THREAD

**Issue by nitrocode** [felixhageloh/uebersicht#290]
The doc says that I can run this command to refresh all the widgets

    tell application "Übersicht" to refresh

When I run it in `osascript` it gives the following error

    $ osascript -e 'tell application "Übersicht" to refresh'
    32:39: execution error: The variable refresh is not defined. (-2753)

**Comment by felixhageloh** [comment]
Could be an issue with typing the app name. It is not so straight forward unfortunately: Check this section of the readme for details https://github.com/felixhageloh/uebersicht#typing-the-umlaut-Ü

**Comment by nitrocode** [comment]
Wow. You are correct.

    $ ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1
    Übersicht

Copying and pasting the output from that into the command worked

    $ osascript -e 'tell application "U<0308>bersicht" to refresh'

One liner

    $ osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh'

Thanks

**Comment by iubuntu** [comment]
thanks
