### ISSUE TITLE
Vibrancy?

### ISSUE THREAD

**Issue by LoganDark** [felixhageloh/uebersicht#293]
macOS has NSVisualEffectView (I think, I almost never use Xcode), is there a way to create these in a widget?

**Comment by felixhageloh** [comment]
If I understand your question correctly, you can achieve the effects of NSVisualEffectView using -webkit-backdrop-filter in your CSS https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

**Comment by felixhageloh** [comment]
closing this because it is a question, but feel free to keep the conversation going here

**Comment by LoganDark** [comment]
Native vibrancy is well, vibrant, some color shows through and it looks nice. -webkit-backdrop-filter is only blur, colors are washed out

**Comment by felixhageloh** [comment]
@LoganDark do you have an example of native vs -webkit-backdrop-filter to show what you mean?

From my experience, if you use the right combination of background color, transparency and blur radius (don't have concrete numbers form the top of my head), you can get pretty much the same effect.

**Comment by LoganDark** [comment]
Here's vibrancy:
![image](https://user-images.githubusercontent.com/4723091/33368599-fc34c298-d4a6-11e7-9e06-104f891e76fd.png)
That's using the title bar material, there are different materials too, such as dark:
![image](https://user-images.githubusercontent.com/4723091/33368660-21e30162-d4a7-11e7-9cf0-f72a19079eb1.png)
And here are regular blurs, added by image editing software:
![bitmap](https://user-images.githubusercontent.com/4723091/33368918-db72c540-d4a7-11e7-8f34-a4afb3f8840e.png) (50% white, 50px blur)
![bitmap](https://user-images.githubusercontent.com/4723091/33368921-e2390a2e-d4a7-11e7-87e4-be5c02159684.png) (25% black, 25px blur)
You might not be able to see the difference since there isn't much detail. Vibrancy really starts to shine on detailed backgrounds:
![image](https://user-images.githubusercontent.com/4723091/33368944-f1748d88-d4a7-11e7-8325-7ac2a3fbfbc6.png)
Here's the dull, blur-only version:
![bitmap](https://user-images.githubusercontent.com/4723091/33369029-3165c2fe-d4a8-11e7-9da0-bf9d0337920d.png) (25% black, 25px blur)
There may not be a very large difference, but I absolutely _love_ native features and hate hacks.

Additionally, vibrancy supports border-radius (or will if you implement it correctly). -webkit-backdrop-filter doesn't care how many nasty hacks you try to perform, it will be a square.

**Comment by Pe8er** [comment]
I know it's still a hack, but I found that manipulating contrast and saturation does a pretty good job of emulating vibrancy. For example:

`-webkit-backdrop-filter: blur(16px) brightness(80%) contrast(100%) saturate(140%);`

Also, I managed to get the rounded corners to work. You can see how in my Playbox widget: https://github.com/Pe8er/Playbox.widget/blob/master/Playbox.widget/index.coffee

Hope this helps!

**Comment by LoganDark** [comment]
What exactly am I supposed to be looking at?

Can you make a demo please? By _itself_, and without 20 other probably unrelated things?
