### ISSUE TITLE
Widget visible in Ubersicht menu but doesn't appear on desktop or debugger

### ISSUE THREAD

**Issue by joecreighton** [felixhageloh/uebersicht#294]
Background: restored user files from 10.11.6 El Capitan to new Mac running 10.12.6 Sierra.  Ubersicht says it's current at 1.2.  Moon Phase widget (mine) doesn't appear on the desktop while others do.  Attempted hide/show, restart/refresh, and monitor selections to no avail.

I'd love to try and debug my widget but I have no idea how if it doesn't appear in the debugger :)

Open to ideas or suggestions.  Thanks.

![screen shot 2017-11-08 at 23 34 05](https://user-images.githubusercontent.com/17548684/32590185-a5d2fb9a-c4de-11e7-83aa-276401d756f2.png)

**Comment by joecreighton** [comment]
Interestingly, that fixed it (even though there is only one display available).  Unsure why I didn't try that but... easy issue is easily closed.  :)

Thanks.

**Comment by felixhageloh** [comment]
It does sound like there is an issue - it should also work with 'show on all screens' set. I was mostly trying to see what the underlying cause might be

**Comment by joecreighton** [comment]
Unfortunately, I can't replicate the issue.  I can walk through selecting each of 'Show on all screens', 'Show on main display' and 'Show on Built-in Display' (which checks 'Show on selected screens:' but is greyed out).  In each case, the widget goes away, does its work and reappears properly; deselecting 'Show on Built-in Display' leaves the greyed out item and the widget is no longer visible (as expected).

Let me know if I can do anything.  I'm willing to help in any way I can; I could go so far as to attempt to restore any related files from backup prior to the purchase of this new machine (replicating the initial restore/install of files when I first noticed things).

**Comment by felixhageloh** [comment]
I see! Seems to be a fluke related to restoring files from backup then. I will close this until it happens more often
