### ISSUE TITLE
Change the refreshFrequency within a widget?

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#301]
Is it possible to change the refreshFrequency of a widget dynamically from within the widget itself? For example, if I set the refreshFrequency to 5m initially can I then change it to 8h programatically within the update() function?

**Comment by felixhageloh** [comment]
@mlcampbe to achieve what you want to do, you have to control refreshes yourself - there is no api to change the refresh frequency  at the moment. 

You can set `refreshFrequency` to false and then run commands manually (either using `@run` or `@refresh`) inside `afterRender` and/or `update`. You can control when the next command runs using `setTimeout` or `setInterval` https://javascript.info/settimeout-setinterval. 

Another option would be to set the refresh frequency to 5min and then call `@stop` whenever you want to pause the widget and use a `setTimeout` with 8h to `@start` the widget again

**Comment by felixhageloh** [comment]
(closing because it is a question, but feel free to follow up)
