### ISSUE TITLE
Selecting 'none' as modifier key makes it impossible to interact

### ISSUE THREAD

**Issue by blahsd** [felixhageloh/uebersicht#304]
Preferences allow you to select the modifier key as 'none'. Selecting this option makes it so that interaction is never possible with widgets. The more intuitive behaviour imho would be that selection this option makes it so that interaction with widget does not require pressing any key. Is the current behaviour intended? And if so, is there any chance that it could be reversed?

Edit: #259 makes it seems as this is, in fact, intended behaviour. I'd guess this turns into a feature request then :P

**Comment by felixhageloh** [comment]
Unfortunately I have not found a way so far to make widgets clickable without breaking interaction with the desktop (icons become unclickable). That's the reason this modifier key exists in the first place; as a sort of hack to still make widgets intractable.

**Comment by blahsd** [comment]
I’d gladly do without icons interaction - and I’m sure so would the many
who don’t use desktop icons at all. If you already have the code, wouldn’t
it be possible to make it maybe selectable behavior?

Il giorno 15 febbraio 2018 @ 16:31:23, Felix (notifications@github.com) ha
scritto:
