### ISSUE TITLE
Find if Interaction Key is pressed

### ISSUE THREAD

**Issue by JakeMan314** [felixhageloh/uebersicht#305]
Is there a way to tell when the interaction key is pressed inside a coffeescript? My intent would be to have a script with networking info only available when that specific key is pressed, as it is only needed sometimes.

**Comment by felixhageloh** [comment]
I think there is no way, or at least I am not explicitly passing that info to the web view. You could maybe use a standard keypress event handler, but you'd have to know which key is configured as the interaction shortcut 🤔

**Comment by felixhageloh** [comment]
closing this because it is a question, but feel free to follow up
