### ISSUE TITLE
Making runtime-generated elements clickable? 

### ISSUE THREAD

**Issue by blahsd** [felixhageloh/uebersicht#307]
Hi! I'm making a sort of task manager. To do so, my widget generates a list of applications which are currently running in the foreground, and displays them as icons. I would like to make these icons clickable, to switch to one or the other application. 

To do so, I need to create an event listener that listens for an object of which I don't know the name (I know the format that the name will have though). So for instance, if Finder, Preview and Safari are running, there will be three buttons, ID'd #Finder-task, #Preview-task and #Safari-task. 

I'm trying to understand if there is a way for me to make such buttons clickable just by self-referencing in the event listener. Something like this: 
```
afterRender: (domEl) -> 
  $(domEl).on 'click', ".button", => 
    $(domEl).find( [BUTTON WHICH HAS BEEN CLICKED] ).addClass("clicked")
```

I haven't had any luck though. 
The other option I'm seeing is procedurally generating event listeners, in a way that might be similar to this: 

```
afterRender: (domEl) ->
  for button in domEl.find('.button')
    $(domEl).on 'click', button => button.addClass("clicked")
```

Is there a way to do any of these two things?

**Comment by felixhageloh** [comment]
```js
$(domEl).on 'click', ".button", (e) -> 
  $(e.target).addClass('clicked')
```

should do the trick. 

Note that if your button has any child elements, `e.target` might refer to a child, in which case you need to find the first parent which is of type button. Alternatively you can also use css to set 'pointer-events: none', on all children, so the click event will only be generated by the button itself
