### ISSUE TITLE
[Request] Merge ~/Library/Application Support/Ubersicht and ~/Library/Application Support/tracesOf.Uebersicht

### ISSUE THREAD

**Issue by blahsd** [felixhageloh/uebersicht#308]
I just stumbled upon the second folder and I can't see any reason why it should be separated from the main one. I'm assuming it might be a leftover of previous iterations of the software?

**Comment by felixhageloh** [comment]
`~/Library/Application Support/tracesOf.Uebersicht` is the OS provided dir to store any app preferences. The second one `~/Library/Application Support/Übersicht` just contains the default widget folder. You can remove it if you have configured a different widget folder
