### ISSUE TITLE
Energy Consumption

### ISSUE THREAD

**Issue by blahsd** [felixhageloh/uebersicht#309]
I'm trying to track down what makes Ubersicht so energy-hungry, so I've been going step by step trying to identify the culprit.

* The scripts that the widgets are running are not particularly energy-intensive. Cronning them and running them outside of Ubersicht with the same frequency requires a reasonable amount of energy and resources. 
* The background Ubersicht app has pretty much a 0 energy consumption if there are no widgets in the widget folder.

Now we get to the first issue proper which I have identified:

* Having widgets in the widget/ folder, even if all of them are disabled, spikes up energy-usage to an average energy impact of 2, with extreme variance. So the impact will be close to 0 most of the time and spike up periodically. This looks like a lot (more than what Microsoft Word uses when word processing, for instance) for doing basically nothing, can anybody reproduce? Should we be looking for a faulty-something within the code, possibly at the stage of scanning the widgets?

**Comment by felixhageloh** [comment]
how did you establish that Übersicht is energy-hungry in the first place?

**Comment by blahsd** [comment]
Not sure what you mean. Because for me it runs with an avg energy consumption of ~30 where my second-most resource intensive is Atom with avg energy consumption of ~20? (and Atom is known to have a problem on this)

By the way thank you for the amazing work, this tool is super useful and its customisability knows no bounds.

**Comment by felixhageloh** [comment]
Cool, that was what I wanted to double check. So something is up in your case - for me the average power consumption is ~3. (I only usually have 3 - 4 widgets running tho)]

The first thing to check is whether to have a specific widget that consumes a lot of energy. I usually find that that is the cause (intensive graphics/animations or a lot of unnecessary re-rendres are usually the cause)

**Comment by blahsd** [comment]
How would you establish that? Just plain trial and error by deactivating
them one at a time? Just asking because I’m very inexperienced and there
might be smarter methods to track it down

-- 
R

Il giorno 7 marzo 2018 @ 15:22:35, Felix (notifications@github.com) ha
scritto:

**Comment by blahsd** [comment]
Just as an update, I tried running the same script on Ubersicht and Geektools (a simple clock, refreshing by the second) just to check the differences in energy consumption and they are astounding (negatively).

Please do note that I'm not insisting on this issue as a criticism, I will keep using Ubersicht anyways because it's the absolute best by far in this class of software. I'm just trying to help isolate the issue it seems to have with energy consumption because I would rather not worry about keeping it on when I'm mobile. If you know of any approach that I could use to track down where this energy consumption is happened, please do let me know.

**Comment by felixhageloh** [comment]
sorry for the late response: 

To track down perf issues you can use the debug console - it has a profiling tool (in the Timelines tab). 
The fact that you see a different performance for Geektool just validates that it most likely has to do how the clock is rendered

**Comment by felixhageloh** [comment]
if you don't mind sharing the code for the clock widget I can maybe also help you more

**Comment by blahsd** [comment]
Oh wow thanks for the tip about the profiling tool. That will definitely come in handy. I did not save the code for the clock because I had just whipped it up to do this quick test and didn't keep it. At any rate, most of my tinkering is going on at [my repo here](http://github.com/blahsd/supernerd.widget) on the greened branch if you're interested. I think that there are a couple of things that I'm trying out that might be interesting also from a best practice point of view, if you intend to publish any at some point. 

For instance what I'm trying now, which you can see in the base-monitor.coffee widget, is having frequently updating widgets check if the values have changed before updating the text / icons, so that, if I haven't messed up, the indicators are only re-rendered if the value is actually changing. 

What baffles me though, is that even with all my widgets set to a refreshFrequency of false, I'm still getting pretty high levels of energy (ie more than safari, for instance), so maybe I'm just missing something about how the rendering works here.

**Comment by blahsd** [comment]
I take that back. It was a mistake on my part somewhere. I re-run the test of setting everything to zero, and the energy consumption drops accordingly to below 1. So I am indeed just rendering badly the widgets.

**Comment by felixhageloh** [comment]
No worries, this stuff is quite hard. I am hoping that the next version of widget syntax (currently in beta) will make this a lot easier!
I saw some nice looking widgets in your repo btw!
