### ISSUE TITLE
Combine 2 widgets vertically

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#312]
Is it possible to somehow take 2 individual widgets and combine them into a vertical 'sidebar' type style. For example, I'd like to re-use 2 existing widgets (one for weather and one for calendar) and display them 1 on top of the other at the top left of the screen. Sure I could combine the functionality of each into a new widget but was hoping there was a way to create a container widget that includes the other 2 widgets in a stacking type of fashion.

**Comment by mlcampbe** [comment]
Do you know of any widgets that implement something like this that I can take a look at? I've tried reviewing a couple that sounded similar but could not find anything that loaded other widgets.

**Comment by felixhageloh** [comment]
I think some widgets by @Pe8er do something like that

**Comment by felixhageloh** [comment]
closing this as a question btw, but feel free to follow up here!
