### ISSUE TITLE
widgets output type over

### ISSUE THREAD

**Issue by aplsms** [felixhageloh/uebersicht#318]
Hello,
I have strange problem on widgets output with transparent background.
it looks like:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/2309682/42045612-cd6f7d4e-7ab0-11e8-8f93-a6a4a7e33d26.png">
Refresh widgets does not fix the problem, but restart of uebersicht
 looks like fix it.
This is how it looks after restart: 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/2309682/42045761-34d73a44-7ab1-11e8-8b1b-ba9b3217cbc0.png">

Maybe it happens if another user logged in om my mac (i have 3 users active).
Widget attached.

[WorldClock.widget.zip](https://github.com/felixhageloh/uebersicht/files/2146022/WorldClock.widget.zip)

Please take a look.

**Comment by felixhageloh** [comment]
are you still seeing this issue? It looks a bit like a known issue: the web view that Übersicht uses under the hood seems to have some subtle bugs with transparency. Sometimes has issues adapting to the desktop image and you need to refresh or change workspace to fix it. It is something out of my control ,unfortunately (or at least I have not found a way to fix it).
