### ISSUE TITLE
geolocation.getCurrentPosition not working with USB wifi adapter

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#321]
I've been using the following code for quite a while now:

  geolocationSuccess = false
  setTimeout =>
    if !geolocationSuccess
        console.log("geolocation timed out, proceeding with fallback")
      @run .....
  ,7000
  geolocation.getCurrentPosition (e) =>
    geolocationSuccess = true
    coords = e.position.coords

All has been working well using the built-in airport wifi card of the iMac. Today I installed a USB wifi card to get AC speeds and now the geolocation pieces are no longer working. It times out after the 7s and logs the console message.

However, accessing geolocation at https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation shows me the proper lat/long coords. 

Any ideas?

**Comment by mlcampbe** [comment]
Oddly enough it seems to be working properly today so this may not be an issue after all.

**Comment by mlcampbe** [comment]
Actually it seems hit or miss. This morning it was working fine for several updates and then all of a sudden it stops working. I'm not sure how/if this can be debugged.

**Comment by mlcampbe** [comment]
Final update...

It seems that geolocation on OSX does not work unless the built-in wifi adapter is enabled. My hit or miss tests yesterday must have had both adapters enabled. After further debugging it seems that with ONLY the external wifi adapter enabled network access is fine but if I try to use the maps app to find my current location it fails with "Turn on Wi-Fi to allow Maps to determine your current location.". As soon as I turn on the built-in wifi it works.

As a hack I turned on the built-in wifi but have not associated it with any access point and thus it does not have any IP address nor a connection to anything. But, this works. I can now use the maps app as well as uebersicht geolocation successfully.

**Comment by felixhageloh** [comment]
Cool you figured it out  yourself!
Yeah, your laptop doesn't have GPS build in, so it is using the presence of (known) wifi networks to figure out your location.
