### ISSUE TITLE
Refresh the command at a certain time

### ISSUE THREAD

**Issue by Freakwill** [felixhageloh/uebersicht#322]
I want to refresh the command at a certain time, instead of in a certain frequency. How can I implement it?

**Comment by jack-michaud** [comment]
I don't know if this functionality exists in Uebersicht, but as a workaround I would put the command in a cronjob and direct the output to some file and make the command in the coffee script `cat` out that file.

**Comment by Freakwill** [comment]
> I don't know if this functionality exists in Uebersicht, but as a workaround I would put the command in a cronjob and direct the output to some file and make the command in the coffee script `cat` out that file.

I ever used apscheduler, a python scheduler module, but it did not work well. Maybe it is my mistake, and I never tried it again. I hope that there is a native way to do it. Thank you, I will consider your advice.

**Comment by felixhageloh** [comment]
I would also suggest using a cronjob, You can either use @jack-michaud's approach or use [Übersicht's AppleScript hooks](https://github.com/felixhageloh/uebersicht#scripting-support) to refresh the widget you want

**Comment by felixhageloh** [comment]
Another approach would be to refresh your widget, say, every couple of minutes and check for the time

**Comment by felixhageloh** [comment]
closing this as a question but feel free to follow up here
