### ISSUE TITLE
Where can I see the ouput from "console.log(output)" macOS 10.13

### ISSUE THREAD

**Issue by TechJedi51** [felixhageloh/uebersicht#323]
Where can I see the ouput from "console.log(output)" macOS 10.13? It doesn't show up in the WebInspector nor Console app.

**Comment by felixhageloh** [comment]
it should show up in the WebInspector - make sure that you are not only filtering for error message, but have 'All' messages enabled:

![image](https://user-images.githubusercontent.com/367503/44980343-e3a0d880-af6f-11e8-96fd-5544f6e8d996.png)

**Comment by TechJedi51** [comment]
I do have "All" selected. Maybe I am misunderstanding what should be there. For example, I'll get a notification (macOS Notifications) that an error has occurred. I'll open the "Show Debug Console" and it appears empty.
![screen shot 2018-09-06 at 7 10 15 pm](https://user-images.githubusercontent.com/28914268/45194617-9e4b0800-b208-11e8-8db0-25063fe547dc.PNG)

**Comment by felixhageloh** [comment]
I see! It seems like the error happens very early o , i.e your widget can't be parsed at all. You should still see an error message in the console (as well as on the notification), but it looks like you found an edge case or bug here. 

What is the message you get in the notification?

**Comment by TechJedi51** [comment]
It is only the beginning of the path to the widget in Notification Center.

**Comment by felixhageloh** [comment]
since 1.3 you should be getting better error output now, including the exact line where your error happens
