### ISSUE TITLE
Unexpected token while parsing file - minimal widget example - React / jsx

### ISSUE THREAD

**Issue by halvardlange** [felixhageloh/uebersicht#330]
Hey, 

I don' t have a ton of experience with React/jsx so I may be missing something obvious here. Testing out the new .jsx widgets, ,and I just copied the example simple widget from http://tracesof.net/uebersicht/

```
  export const command = "echo Hello World!"

  export const refreshFrequency = 5000 // ms

  export const render ({ output }) => (
    <h1>{output}</h1>
  )

  export const className = `
    left: 20px
    top: 20px
    color: #fff
  `
```
When saved, I get the following error 

`Unexpected token (5:20) while parsing file:`

![image](https://user-images.githubusercontent.com/19482662/48222192-fa91eb80-e361-11e8-9192-aa31a7beb00d.png)

If insert  `=` , it does render, i.e.  
```
 export const render = ({ output }) => (
    <h1>{output}</h1>
  )
```
I have a similar error with 
```
export const command "echo Hello World";
```
that throws an error unless I alter it to 

```
export const command = "echo Hello World";
```

What could cause this?

**Comment by datitisev** [comment]
That's how regular JavaScript works. `const` is just a scoped variable constant (see https://medium.com/javascript-scene/javascript-es6-var-let-or-const-ba58b8dcde75).

When you `export`, you export named exports, which are basically just the global object returned when retrieving all the values, i.e. `{ command: '', render: ... }`.
Think of it as `export var command = "echo Hello World";`

The example in the website is simply missing an equals sign for the variable assignment.

Hope I helped 🙂.

**Comment by felixhageloh** [comment]
yes, my bad, the example on the website was missing an `=`! Fixed now

**Comment by singalen** [comment]
BTW it's not clear that the extension should be `.jsx`.
