### ISSUE TITLE
help with refreshing widgets with specific name

### ISSUE THREAD

**Issue by ans87gh** [felixhageloh/uebersicht#332]
So I'm trying to refresh all widgets that I've named background. I want to leave all other widgets alone. This is what I've come up with but it doesn't seem to be doing anything. Any suggestions?
```AppleScript
tell application "Übersicht"
	set lstWidget to every widget
	set lstBckgrndWidget to {}
	tell application "Übersicht"
		set bckgrndWidget to every widget whose id contains "background"
		repeat with crrntWidget in bckgrndWidget
			set crrntBckgrndWidget to (the id of crrntWidget)
			copy crrntBckgrndWidget to the end of lstBckgrndWidget
		end repeat
		repeat with i from 1 to length of lstBckgrndWidget
			set rfrshWidget to item i of lstBckgrndWidget
			refresh widget id rfrshWidget
		end repeat
	end tell
end tell
```

**Comment by ans87gh** [comment]
If I'm understanding you correctly, that's where the prompt 'every widget' comes in.
It pulls all the widgets loaded into Ubersicht.
The next set of prompts isolate all widgets with background anywhere in the id - remember that the id is not only the name assigned, but also the names of all parent folders nested after /ubersicht/widgets. So that takes care of the unique issue.
Without making a list, I had a problem feeding in each widget because of how it was output from the 'every widget' prompt.
So I made a list and fed thad into a repeat loop of the action refresh widget.

When I print each variable, they are correct. That is, they are what I wanted them to be. But I can't seem to refresh (or even reload when replacing refresh with reload) any of the widgets.

**Comment by felixhageloh** [comment]
@ans87gh are you able to refresh them if you hard code the ids?

**Comment by ans87gh** [comment]
Yes

**Comment by felixhageloh** [comment]
I've tried you script and it seems to work for me. I don't have any widgets with "background" in their name but I tried it with other substrings that do occur
