### ISSUE TITLE
Error running commands error

### ISSUE THREAD

**Issue by yu-george** [felixhageloh/uebersicht#334]
After I updated to Übersicht 1.3, many of my old widgets stopped working, the output all turned into `error running command` errors with a white background. All the commands worked in previous versions.

One of my command looks like this:
```/usr/local/bin/python3 -c 'from datetime import date; print((date(2019, 11, 1) - date.today()).days)'```

Even if I adapted the old coffee script into jsx scripts, the widget will still output the `error running command` error for about a third of the time.

What could be the possible causes for this error? And what can I do to fix it?

**Comment by felixhageloh** [comment]
this might be a bug. I noticed something similar, although not as often as you described. I will investigate!

**Comment by felixhageloh** [comment]
Are you using the default render method btw, or do you have your own render method implementation?

**Comment by yu-george** [comment]
@felixhageloh I think the frequency decreased significantly after half a day or so, which is pretty odd…I think the problem occurs pretty randomly. Anyhow, it is working for most of the times now.

I used the default render method, I don't think there is a problem with that:
```jsx
export const render = ({ output }) => {
  return (
    <div>
      <h1 className={header}>{output} Days Left, {Math.round((1 - output / 435) * 100)}% Passed</h1>
      <div className={container}>
        <div className={progress} style={{width: (output / 435 * 100) + '%'}} />
      </div>
    </div>
  );
}
```

And the old syntax version:
```coffee
render: (output) -> """
  <div>
    <h1>#{output} Days Left, #{Math.round((1 - output / 435) * 100)}% Passed</h1>
    <div class='container'>
      <div class='progress' style='width: #{output / 435 * 100}%'></div>
    </div>
  </div>
"""
```

As of now, I refreshed multiple times, and both versions worked without giving me the `error running command` error.

**Comment by felixhageloh** [comment]
From what I can tell so far, it is an old issue. Basically Safari (which is what Übersicht uses under the hood) is very picky when it comes to processing ajax requests and sometimes rejects requests fetching the command output for a widget. 
In the past this would go unnoticed, but in the latest release I made command errors more explicit to help people notice when something goes wrong. 

An easy fix is to ignore end retry those specific errors, which I think I will release pretty soon. In theory it should also be possible to avoid those errors altogether but I haven'y quite figured out what Safari doesn't like about the server responses exactly.

**Comment by felixhageloh** [comment]
This should be fixed in the latest release - let me know if you are still seeing this error!

**Comment by yu-george** [comment]
@felixhageloh I updated to the latest release and the same error persists. I think I am experiencing the same bug as described in #338 and #340. The fail rate is pretty high, about 60%-70% times I refresh the widgets, the error will occur.
