### ISSUE TITLE
Help with converting javascript to react code

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#336]
I was barely any good with coffeescript but managed to get some widgets thrown together for my own use. Now I am trying to convert some of the simplest ones over to react and having a lot of problems with syntax and features. For example, I have the coffeescript:

```
command: "curl ...."

refreshFrequency: 900000

style: """
  bottom: 0px

  .verse
    color: #fff
    font-family: Calbria
    font-style: italic
    font-size: 16px
"""

render: -> """
  <div class='verse'></div>
"""

update: (output, domEl) ->
  $(domEl).find('.verse').html(output.replace(/--/g, '<br><center>'))
  posH = ($(window).width()/2)-(($(domEl).width())/2)
  $(domEl).css({'left':posH})
```

When this ran it would download a string and center it horizontally along the bottom of the screen.  However, this is not working too well with react. I have corrected a couple of problems and this is my current code:

```
export const command = "curl ...";
export const refreshFrequency = 900000;

import { css } from "uebersicht"
export const className = `
  bottom: 0px;
`
const verse = css`
  color: #fff;
  font-family: Calbria;
  font-style: italic;
  font-size: 16px;
`

export const render = ({output, error}) => {
  var result = output.replace('--', '<br><center>');
  var windowWidth = window.innerWidth/2;
  var verseWidth = result.length/2;
  var posH = windowWidth-verseWidth;
  console.log(posH)
  return (
    <div style={{paddingLeft: posH}} className={verse}>{result}</div>
  );
}
```

Syntactically it is running now but I have a few problems:

1  - The output is not getting centered on the monitor. It seems that there is a problem with converting the length of a string to screen pixels that was not happening in coffeescript.

2 - The html I am adding to the output is not getting rendered but left as plain text.  For example, if the output was "this is my string --Nov 15" it gets converted to "this is my string <br><center>Nov 15" and is displayed that way all on 1 line instead of having the html interpreted.

Can anyone help me get started with some basics?

**Comment by hawkrives** [comment]
To output raw HTML, you can say `<div dangerouslySetInnerHTML={{__html: "<p>whatever</p>"}}/>`.

I'll have to think more about the other issue. Please ping me if I haven't said anything in a few days ;-)

**Comment by felixhageloh** [comment]
Not sure if understand your use case 100%, but I'd make your widget take the entire width of the screen and use text align center: 

```jsx

export const command = "curl ...";
export const refreshFrequency = 900000;

import { css } from "uebersicht"
export const className = `
  bottom: 0px;
  left: 0;
  right: 0;
`
const verse = css`
  color: #fff;
  font-family: Calbria;
  font-style: italic;
  font-size: 16px;
  text-align: center;
`

export const render = ({output, error}) => {
  const lines = output.split('--');
  return (
    <div className={verse}>{lines.map((line) => <p>{line}</p>)}</div>
  );
}

```

**Comment by mlcampbe** [comment]
Thanks, the above works as expected now.
