### ISSUE TITLE
mojave security/privacy settings are stricter making it difficult to run scripts

### ISSUE THREAD

**Issue by corporate-gadfly** [felixhageloh/uebersicht#341]
I have a übersicht widget which used to work all the up to High Sierra (through various macOS upgrades over the years). The script uses `/usr/libexec/PlistBuddy` to extract information from `/Library/Preferences/com.apple.TimeMachine.plist`.

After upgrading to Mojave, I am no longer able to see the contents of the `.plist` file _(thanks to the stricter security and privacy settings in Mojave)_.
```
$ /usr/libexec/PlistBuddy -c "PrintDestinations" /Library/Preferences/com.apple.TimeMachine.plist
Error Reading File: /Library/Preferences/com.apple.TimeMachine.plist
```
File permissions:
```
$ ls -al /Library/Preferences/com.apple.TimeMachine.plist
-rw-r--r--  1 root  wheel  5563  1 Dec 02:12 /Library/Preferences/com.apple.TimeMachine.plist
```
I am looking for ideas on how to give the script FDA access _(e.g., by using Script Editor to wrap a shell script into a `.app`, or [Platypus](https://sveinbjorn.org/platypus))_.

Thanks in advance.

**Comment by felixhageloh** [comment]
I think granting Übersicht full disk access would work: 

<img width="780" alt="image" src="https://user-images.githubusercontent.com/367503/58623784-0e397b00-82cf-11e9-93fd-a76580b3ad85.png">

**Comment by corporate-gadfly** [comment]
Whadaya know.... It worked. Pretty sure I had tried that earlier. Oh, well.
![image](https://user-images.githubusercontent.com/1200537/58648835-9a9c6b80-82d8-11e9-91d1-c704720d45ac.png)

**Comment by tillsanders** [comment]
Can we add this to a Troubleshooting section or something? 🙈
