### ISSUE TITLE
Permissions for calendar via iCalBuddy

### ISSUE THREAD

**Issue by patrick91** [felixhageloh/uebersicht#347]
Hello, I was trying a widget that was using iCalBuddy but it didn't work, I think it a Mojave permission issue, maybe we need to add the permissions reason, like it was done for iTerm2? https://github.com/ali-rantakari/icalBuddy/issues/20

**Comment by kuroshirokun** [comment]
Same issue here

**Comment by peterbaker** [comment]
Same issue here.

**Comment by felixhageloh** [comment]
this should be fixed now

**Comment by patrick91** [comment]
@felixhageloh it works now! thank you!
