### ISSUE TITLE
Ubersicht failed to load resource: the network connection was lost.

### ISSUE THREAD

**Issue by John-woodman** [felixhageloh/uebersicht#349]
So I just downloaded Ubersicht for mac os high sierra 10.13.6 and I copied a widget to the widget folder, but no option to select it showed up in the drop down menu for ubersicht. I checked debug console and it shows this: 
<img width="996" alt="screen shot 2019-01-22 at 6 04 53 pm" src="https://user-images.githubusercontent.com/32111296/51571489-40922200-1e70-11e9-8e66-aba3c389d96d.png">

I then checked the system log files after restarting ubersicht and this is what it tells me:
<img width="1078" alt="screen shot 2019-01-22 at 6 06 29 pm" src="https://user-images.githubusercontent.com/32111296/51571574-8bac3500-1e70-11e9-93eb-1dd3394852d7.png">

Any help would be much appreciated!

**Comment by felixhageloh** [comment]
this should be fixed
