### ISSUE TITLE
Use System / Application Audio with a widget

### ISSUE THREAD

**Issue by reteps** [felixhageloh/uebersicht#350]
Is this possible? If not make this a [feature-request], if not [question].

**Comment by hawkrives** [comment]
By "use", do you mean "control" (play/pause/etc), or "play" some custom audio over the output, or something else?

**Comment by reteps** [comment]
Something else. I want to be able to take in an audio stream.

**Comment by hawkrives** [comment]
Generally speaking, Übersicht widgets can do anything that you can do on the Unix command line, so if you can figure out a way to do what you're trying to do in the Terminal, you can probably do it with Übersicht. 

Out of curiosity, what are you looking to do with the audio stream? Where is it coming from?

**Comment by reteps** [comment]
I figured out how to do it, this was a stupid question haha. Does uebersicht do well with high refresh rates for it's widget? Like if I want to sample audio every 50ms.

**Comment by hawkrives** [comment]
Uh… I've never tried. Please test it out and let us know!
