### ISSUE TITLE
Weather widgets won't refresh on Mojave

### ISSUE THREAD

**Issue by the-sweet** [felixhageloh/uebersicht#351]
I know Mojave is pretty strict about access, but I made sure to give Übersicht access in Security & Privacy for Accessibility and Location (for weather widgets that use it), but no matter how many times I refresh the widgets, they still all show the same location, and are a day behind (indicating they don't seem to have permission to check the correct time, either). Is there some other way of granting access I'm not seeing/forgetting? Do individual widgets need to get permissions somehow?

I'm using the Übersicht Weather Widget and Übersicht 1.3.

**Comment by twhite96** [comment]
Having  the same issue. Now they won't render at all, just showing a white block of nothing.

**Comment by felixhageloh** [comment]
This should be fixed now - let me know whether it is still breaking for you in version 1.4.58

**Comment by the-sweet** [comment]
I updated Übersicht, The Weather widgets now display weather, but they're all stuck to the same city, even though I have two of them set to be a "fixed" location rather than automatic location detection. Should I try and update the widgets themselves, too?
