### ISSUE TITLE
Recent update broke all of my old/simple widgets?

### ISSUE THREAD

**Issue by bjs-github** [felixhageloh/uebersicht#354]
I am extremely happy that Ubersicht exists, and have been satisfied for years with my simple widgets, but I am also just barely competent at setting them up.

The last time I (manually) updated Ubersicht was at least ~ 6-9 months ago.  I just updated now, and now I can't get any of my widgets to appear any longer; they are listed in the menu-bar menu as before, but they simply don't appear on my screen (despite restarting, reinstalling, resetting the widgets folder, etc.).  Nor do any error messages.  (When I downgrade using the original installer I first downloaded from 2015, they all appear again.  I didn't save any of the updates since 2015, but I remember updating several times, always without trouble until now.)  For complicated reasons, I'm still using this on a machine with Yosemite.

I'm sure I'm missing something obvious, but I can't figure out what it is.  I do see that widgets are now written as .jsx files; mine are still all the older .coffee files, but the current readme file suggests that these are still supported.  (Or do I have to do something to enable that support?)

Any suggestions for how I can get my widgets to reappear again?  Or, failing that, is there any way to downgrade to a previous version that's not so absurdly old?

Thank you.

Here is a sample (.coffee) widget, modified long ago from one of the early ones I found online.

---------------------------

stylingOptions =
  # background color
  background: 'rgba(#fff, 0.0)' 
  # show fullscreen -> true
  fullscreen: false
  # display position 'top', 'middle', 'bottom'
  vertical: 'bottom'

dateOptions =
  # display not only 'time' also 'date'
  showDate: false
  # format of 'date'
  date: '%d/%m/%Y %a'

format = (->
  if dateOptions.showDate
    dateOptions.date + '\n' +'%l:%M %p'
  else
    '%l:%M'
)()

command: "date +\"#{format}\""

# the refresh frequency in milliseconds
refreshFrequency: 30000

# for update function
dateOptions: dateOptions

render: (output) -> """
  <div id='simpleClock'>#{output}</div>
"""

update: (output) ->
  if this.dateOptions.showDate
    data = output.split('\n')

    html = data[1]
    html += '<span class="date">'
    html += data[0]
    html += '</span>'
    
  else
    html = output

  $(simpleClock).html(html)

style: (->
  fontSize = '4em'
  width = 'auto'
  transform = 'auto'
  bottom = '1%'
  top = 'auto'

  if stylingOptions.fullscreen
    fontSize = '10em'
    width = '94%'

  if stylingOptions.vertical is 'middle'
    transform = 'translateY(50%)'
    bottom = '50%'
  else if stylingOptions.vertical is 'top'
    bottom = 'auto'
    top = '3%'

  return """
    background: #{stylingOptions.background}
    color: #FFFFFF
    font-family: Herculanum

    right: 8px
    top: #{top}
    bottom: 10px
    transform: #{transform}
    width: #{width}

    #simpleClock
      font-size: #{fontSize}
      font-weight: 100
      margin: 0
      text-align: center
      padding: 20px 55px

    #simpleClock .date
      margin-left: .5em
      font-size: .5em
  """
)()

---------------------------

**Comment by bjs-github** [comment]
Two updates:

1.  I managed to find an older 1.2.53 app from the updates rss feed, and my widgets are working again in that version.

2.  It seems like this may be a problem with older .coffee  widgets not working after all in 1.3, since even older ones I download now from http://tracesof.net/uebersicht-widgets/ won't appear.

**Comment by felixhageloh** [comment]
Is this still an issue for you? I have a few old coffeescript widgets running that seem to work fine. 
In case they are still breaking, do you see any error in the console?
