### ISSUE TITLE
Any way to access hover states?

### ISSUE THREAD

**Issue by alex-taxiera** [felixhageloh/uebersicht#356]
For example with css pseudo class `:hover` or JSX `onMouseEnter` and `onMouseLeave`.

I know we can capture clicks given the interaction button, but is there any way we can capture these other mouse events?

**Comment by hawkrives** [comment]
I think `:hover` can be activated when you're holding down the interaction shortcut; other than that, I don't think it's (currently?) possible to trigger any sort of interaction without holding the key down.

**Comment by alex-taxiera** [comment]
Here's what I observe when trying to use `:hover`

Example widget:
```jsx
export const refreshFrequency = 1

export const className = `
  .test {
    background: white;
  }
  .test:hover {
    background: red;
  }
`

export const render = () => (
  <div className="test">
    Testing
  </div>
)
```
Holding down the interaction button and mousing over the widget does nothing.

Holding down the interaction key and clicking on the widget activates the `:hover` state, then if you click elsewhere from the widget (only while holding down the interaction key) the `:hover` state will be gone again.

For reference:

MacOS 10.14.3
Übersicht 1.3

**Comment by felixhageloh** [comment]
I have seen this issue and unfortunately I have not been able to find a solution so far. I think it has to do with the internal WebView having a transparent background, which is not officially supported.
