### ISSUE TITLE
1 widgets errors causes another widget to break?

### ISSUE THREAD

**Issue by kknopper** [felixhageloh/uebersicht#357]
@felixhageloh Just noticed that when developing a new .jsx widget, it was causing another .jsx widget of mine to break.

I was working on a simple calendar widget, and after updating my updateState function to catch errors (#355 thanks for this explanation btw :), I noticed the app was giving me errors every few times I refreshed. Saving my .jsx file would fix the app, but every time I refreshed from the ubersicht menu it was inconsistently working.

I realized by removing another widget I was working on from my widgets folder, my calendar app no longer had any issues.

Not sure how one widget could break another as I  thought each widget was supposed to be code independent.

**Comment by alex-taxiera** [comment]
Could you provide the two widgets and steps to reproduce the issue?

**Comment by kknopper** [comment]
Closing this as I was unable to properly reproduce
