### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'process.env.NODE_ENV') when importing React, PropTypes, etc.

### ISSUE THREAD

**Issue by tupton** [felixhageloh/uebersicht#358]
In a virtual dom (react) widget, an attempt to import React or PropTypes (and I'm sure others) results in the widget failing to load with an error `TypeError: undefined is not an object (evaluating 'process.env.NODE_ENV')`.

Is there a way we can either be able to import these modules or let them be exported from the `uebersicht` module like Emotion currently is?

**Comment by felixhageloh** [comment]
Not yet, but it will be fixed in the next version!

**Comment by felixhageloh** [comment]
react is now exposed in the `uebersicht` package. 

`import {React} from 'uebersicht'` should work

**Comment by roele** [comment]
What about `Component` etc.? Trying to extract error rendering into an Error.jsx component gives me the following error (pointing to `class Error extends React.Component`).

```
TypeError: undefined is not an object (evaluating '_uebersicht2.default.Component')
(anonymous function) — Error.jsx:23
...
```
_Error.jsx_
```
import React from 'uebersicht';
import PropTypes from 'uebersicht';

class Error extends React.Component {

    constructor(props) {
        super();
        this.props = props;
    }

    render() {
        return (
            <div>
                {this.props.error}
            </div>
        );
    }

}

Error.propTypes = {
    error: PropTypes.string
};

export default Error;
```

**Comment by tupton** [comment]
@roele `React` is one of a few things exported `from 'uebersicht'`. [The default export is just a plain object with these properties set](https://github.com/felixhageloh/uebersicht/blob/master/server/src/uebersicht.js#L6).

If you use `import { React } from 'uebersicht';` then `React.Component` should work as expected.

Note that this does not expose `PropTypes`.

**Comment by roele** [comment]
Thanks for the hint @tupton. Guess i have to workaround (disable) the PropTypes linting for now.

**Comment by tupton** [comment]
Yep, that's what I do. I try to keep prop type definitions up to date but commented out in my uebersicht widget. I also disable prop type linting with `react/prop-types: off`. Somewhat related: I found that using a yaml eslint config works best for uebersicht widget repos; otherwise Uebersicht tries to render js or json eslint configs.

**Comment by felixhageloh** [comment]
@tupton from what I understand, PropTypes now lives in its own package: https://www.npmjs.com/package/prop-types. Übersicht does not come bundled with it, but you should be able to bundle it with your widget

**Comment by tupton** [comment]
For some reason, adding and importing `prop-types` in a widget project results in the same error as above. I haven't really digged in to why, but I can create a separate issue for that with any details I can find if that helps.
