### ISSUE TITLE
Referencing assets?

### ISSUE THREAD

**Issue by MaciekBaron** [felixhageloh/uebersicht#361]
Hi, I was wondering whether it is still possible to reference assets from a widget.

I've tried installing https://github.com/callahanrts/bar but the icon-font doesn't work as the minified css file used by awesome fonts cannot be loaded anymore. How can this be achieved with the latest version? Thanks!

**Comment by felixhageloh** [comment]
I was not able to reproduce this in the latest version. Is it still a problem for you?
