### ISSUE TITLE
Show/hide individual widgets on separate windows ("desktops", "spaces")

### ISSUE THREAD

**Issue by Amw94** [felixhageloh/uebersicht#363]
I'm aware this question has already been addressed in quite a few threads... but just posting in hopes maybe someone found a solution since the last time this was asked...

From all that I've read it seems there is no easy solution to identifying individual windows ("desktops", "spaces") and in turn being able to turn on/off individual widgets on select windows. 

Has anyone been able to find a workaround for this issue?

**Comment by felixhageloh** [comment]
closing as duplicate: https://github.com/felixhageloh/uebersicht/issues/381
