### ISSUE TITLE
tell application id "tracesOf.Uebersicht"

### ISSUE THREAD

**Issue by andrewp-as-is** [felixhageloh/uebersicht#364]
README.md invalid applescript examples (utf-8 issue?)

wrong: `tell application "Übersicht"`
script error: Expected class name but found identifier. (-2741)

valid: `tell application id "tracesOf.Uebersicht"`

**Comment by felixhageloh** [comment]
did you try to use one of the solutions proposed in the Readme https://github.com/felixhageloh/uebersicht#typing-the-umlaut-ü?

**Comment by looking-for-a-job** [comment]
I suggest a more convenient way :)

**Comment by felixhageloh** [comment]
thanks! I vaguely remember that this didn't work in the past, but I can confirm it works now. I will update the readme
