### ISSUE TITLE
applescript show/hide not works

### ISSUE THREAD

**Issue by looking-for-a-job** [felixhageloh/uebersicht#366]
`tell application id "tracesOf.Uebersicht" to set hidden of widget id "datetime" to false`
execution error: Übersicht got an error: Can’t set widget id "datetime" to false. (-10006)

**Comment by felixhageloh** [comment]
make sure you type the full widget id as it appears in the menu. In your case it is probably "datetime-coffee" or "datetime-jsx" depending on your file extension
