### ISSUE TITLE
All calendar functionality is broken

### ISSUE THREAD

**Issue by peterbaker** [felixhageloh/uebersicht#367]
Because of Mojave's sandboxing/permissions, iCalbuddy is no longer usable in Ubersicht without an update to ask for those permissions.

iTerm2 went through the same thing: https://github.com/ali-rantakari/icalBuddy/issues/20

Given that Calendar functionality is a huge aspect of a lot of Ubersicht widgets, I'd hope getting this updated is a priority?

**Comment by felixhageloh** [comment]
as a quick fix for now: You can grant Übersicht access to your calendar manually in your 'Security and Privacy' settings

![image](https://user-images.githubusercontent.com/367503/57866024-e93d0680-77fe-11e9-8a56-0b8112645652.png)

**Comment by peterbaker** [comment]
But that's the problem, there is no way to get Ubersicht into that list unless it requests Calendar access. I'm fully up to date on the application, how are you seeing that in your Privacy/Access list?

https://github.com/ali-rantakari/icalBuddy/issues/20#issuecomment-416007074

**Comment by willsunnn** [comment]
I have the same problem as well. Ubersicht never requests for calendar access, and ubsericht doesn't appear in the calendar tab in privacy settings because it never asked for it. @felixhageloh, to recreate the issue, maybe try executing tccutil reset calendar in your terminal

**Comment by peterbaker** [comment]
Here's some more info on the "Purpose String" you have to add to the plist file:
https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy/accessing_protected_resources

You can run `tccutil reset Calendar` to recreate the issue we're all having.

**Comment by felixhageloh** [comment]
thanks for the additional info - hoping to release a fix soon!

**Comment by felixhageloh** [comment]
released a fix today! Let me know if any permission strings are missing for you

**Comment by tareqmy** [comment]
I was using ubersicht 1.4(60) in mojave. and it was working fine. I made a clean install of Catalina. and now i am getting this issue.
![Screenshot 2019-11-20 at 12 36 11 PM](https://user-images.githubusercontent.com/6842492/69214899-65d7e580-0b92-11ea-8f20-c36cdc5d323e.png)

problem is as mentioned above ubersicht does not asks for calendar permissions
![Screenshot 2019-11-20 at 12 36 16 PM](https://user-images.githubusercontent.com/6842492/69214954-8bfd8580-0b92-11ea-89e8-369f1f5c7bd5.png)

i really depend on this feature. can you kindly fix the issue for catalina?
