### ISSUE TITLE
Bootstrap CDN background issue

### ISSUE THREAD

**Issue by Al7ech** [felixhageloh/uebersicht#373]
When using bootstrap, I get this white background and can't see my background.

<img width="1440" alt="스크린샷 2019-09-01 오전 12 30 17" src="https://user-images.githubusercontent.com/21143608/64091211-1f8c9a80-cd8a-11e9-9dc8-7ffd5e943494.png">
widget with bootstrap

<img width="1440" alt="스크린샷 2019-09-01 오전 12 30 28" src="https://user-images.githubusercontent.com/21143608/64091230-316e3d80-cd8a-11e9-9110-d952dc13a150.png">

widget without bootstrap

What's the problem, and how can I get rid of it?

**Comment by felixhageloh** [comment]
Not really familiar with Bootstrap, but I am guessing it uses some reset style to set the background of `html` or `body` to white (Übersicht sets it to transparent by default)

**Comment by felixhageloh** [comment]
closing this issue (because it is a question not directly related to the app itself). Feel free to continue the conversation here tho!

**Comment by Al7ech** [comment]
Thanks for your anwser. As you mentioned, bootstrap's body background was set to white.

By adding 

`<style type="text/css">{"body {background-color  :rgba(0,0,0,0) !important;}"}</style>`

under `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />`

i could get the transparent background.
