### ISSUE TITLE
Insane VM usage even with no widgets

### ISSUE THREAD

**Issue by lane-brain** [felixhageloh/uebersicht#374]
Hi! I've been having a lot of fun using the new JSX system to code widgets. While looking at htop I realized that the vmem usage of webkit is MASSIVE! It idles at like 85 gigs when I don't have a single widget loaded. I realized it couldn't have been like this in its default state. 

Maybe something I did may have contributed to what was going on. When I was developing a series of widgets, it had at first seemed like it wasn't actually live updating them. So I had basically just removed and reinstalled the widgets from the folder again and again in order for them to load. Oftentimes when doing this, the app would stop updating the widgets and I would have to relaunch the app. This was stupid for me to do in hindsight, as it turned out that this issue was something peculiar to macvim; when I switched to my trusty nvim in Terminal the live updates on hitting :w worked as had originally been described.

I've tried clearing my App Caches for Übersicht, as well as restarting. I've cleaned out the widgets folder and tried to relaunch the app several times, but webkit still is astronomically high in vmem usage. I feel like this is undesired behavior.

<img width="1190" alt="Screen Shot 2019-09-05 at 12 04 57 PM" src="https://user-images.githubusercontent.com/4432331/64360033-98ccfd00-cfd7-11e9-9314-db54e5dfdeb2.png">

<img width="894" alt="Screen Shot 2019-09-05 at 12 05 14 PM" src="https://user-images.githubusercontent.com/4432331/64360047-a1bdce80-cfd7-11e9-80fd-d276f430359c.png">

<img width="178" alt="Screen Shot 2019-09-05 at 12 05 52 PM" src="https://user-images.githubusercontent.com/4432331/64360058-a84c4600-cfd7-11e9-9dbd-8671cf2d0dfe.png">

**Comment by felixhageloh** [comment]
(sorry for the late reply) That does seem very high and also not in line with what I am typically seeing. Is this still the case for you?

**Comment by pbioc** [comment]
That's what htop reports, but cross checking it with activity monitor, the latter doesn't show these amounts. Perhaps webkit 'reserves' large shares of virtual memory that htop reports literally but isn't actually being utilized by the system.
