### ISSUE TITLE
Changing number of monitors

### ISSUE THREAD

**Issue by skonesam** [felixhageloh/uebersicht#38]
I have a nice three-monitor (laptop + 2) setup at my desk – plenty of room to display lots of widgets. When I take my laptop to a meeting, it would be great to automatically disable some widgets, enable others (battery) and reposition them on a smaller screen.

Don't need to detect number of monitors or anything – there are other programs that do this – but an ability to have groups of widgets and their screen position would be wonderful. 

Workaround for now, I suppose, is to have a "desktop" and "laptop" folder with duplicate widgets and different locations specified…

**Comment by felixhageloh** [comment]
another related issue https://github.com/felixhageloh/uebersicht/issues/52

closing this one for now
