### ISSUE TITLE
Exit Übersicht from command line

### ISSUE THREAD

**Issue by matthiasbe** [felixhageloh/uebersicht#380]
Is it possible to exit Übersicht from command line ? I tried the following without success:

- `osascript -e 'quit app "Übersicht"'`
- `osascript -e 'tell application "Übersicht" to quit'`
- `pkill Übersicht`
- `killall Übersicht`

 I tried those without the `¨` also. For each command I don't have any error, but nothing happens.

I'd like to integrate this in a script to temporary reset my computer config. Any idea why it doesn't work ?

**Comment by felixhageloh** [comment]
you can use the app id instead of the app name. Typing the Umlaut Ü is very tricky because it seems like the command line uses a different unicode character than the file system. 

This should work:
```bash
osascript -e 'quit app id "tracesOf.Uebersicht"'
```
