### ISSUE TITLE
calendar permission broken in macos catalina

### ISSUE THREAD

**Issue by tareqmy** [felixhageloh/uebersicht#383]
I was using ubersicht 1.4(60) in mojave. and it was working fine. I made a clean install of Catalina. and now i am getting this issue.

![69214899-65d7e580-0b92-11ea-8f20-c36cdc5d323e](https://user-images.githubusercontent.com/6842492/70244259-41892500-179e-11ea-909a-f78720d23ad6.png)

problem is as mentioned above ubersicht does not asks for calendar permissions
![69214954-8bfd8580-0b92-11ea-89e8-369f1f5c7bd5](https://user-images.githubusercontent.com/6842492/70244268-43eb7f00-179e-11ea-8c81-c5263f3dc55f.png)

i really depend on this feature. can you kindly fix the issue for catalina?
for reference there was an old issue that was resolved --- #367

**Comment by felixhageloh** [comment]
I can conform this - working on a fix

**Comment by felixhageloh** [comment]
this should be fixed in 1.4.61 released today. Please re-open if you still have this issue after upgrading

**Comment by tareqmy** [comment]
it is working now. thanks!
