### ISSUE TITLE
iStat error Ruby version on Catalina

### ISSUE THREAD

**Issue by jeduarz** [felixhageloh/uebersicht#384]
Hi!
iStat is not working after install Catalina on Mac OS.
The error message on desktop is:

bash: /usr/local/bin/istats: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by felixhageloh** [comment]
I think Catalina now ships with ruby 2.6. This is a issue with the widgets itself tho, so best to create an issue on the widget's repo
