### ISSUE TITLE
Interaction: onClick event doesn't work.

### ISSUE THREAD

**Issue by jachymjanousek** [felixhageloh/uebersicht#386]
Can not make widget interactive, clickable. I want to create button for updating widget data on demand.
I tried basic logging into console. onClick event wasn't triggered, even initial :active style didn't apply on button. Widget is behaving like covered with overlay. If I open Uebersicht widget in browser on 127.0.0.1:41416 button works and also trigger system sound inside run() function  as I expected.
```js
"osascript -e beep"
```
Somebody knows where is the problem?

I have Allowed Accessibility

My code:
```jsx
import { run } from 'uebersicht'

export const render = (props, dispatch) => {
  return (
    <button
      onClick={() => {
        console.log(true);
        run("osascript -e beep")
      }}
    >
      Update
    </button>
  );
}
```

MBP Early2015
macOS Catalina
v 10.15.1

**Comment by aldo-sanchez** [comment]
Same. Can't quite pinpoint the issue. Any help is appreciated.

**Comment by felixhageloh** [comment]
have a look at #149

**Comment by felixhageloh** [comment]
I have a change that finally seems to make clickable widgets work btw. Hoping to release it soon!

**Comment by benjitusk** [comment]
@felixhageloh has that been released yet? OnClick events are still not being fired.
