### ISSUE TITLE
The widget does not refresh with the given frequency if command is empty

### ISSUE THREAD

**Issue by Jim-Zenn** [felixhageloh/uebersicht#389]
I'm writing a clock which utilize JS's `Date` object, and does not need a `command`. However, I DO wish the widget to refresh with the set refresh frequency. 
Unfortunately, it seems if the `command` constant is not set, the widget does not refresh at all. If I set a dummy command like `echo hi`, the refresh process then happens. I believe it's probably design to be like this, but I feel the widget should be static only if `refreshFrequency` is not set.

**Comment by Jim-Zenn** [comment]
Well, I can even set `command` to just a shell comment like `#doNothing` and the refreshing then works.

**Comment by felixhageloh** [comment]
whether a widget updates has nothing to do with running commands, but whether there is a state change. Running a command currently forces a state change, even if there were no real changes, but that behavior might change in the future. 

State changes occur by triggering an event using `dispatch` and responding to it in your `updateState` function. You could set up a timer inside `init` (dispatch is passed as an argument) and then dispatch a 'CLOCK_TICKED' event every time the timer fires. 

However, In your case the easiest is probably to use a command function:

```jsx

export const refreshFrequency = 1000;

export const command = () => new Date();

export const render = ({output}) => {
   // render the clock. `output` will be the current time
};
```

In this example, dispatching events and updating the state will be handled automatically for you

**Comment by felixhageloh** [comment]
closing the issue, but feel free to follow up with more questions on this thread!

**Comment by Jim-Zenn** [comment]
Cool! Thank you for answering my question. I didn't realize the command could be a JS function. Your explanation is also very thorough. I really appreciate it. Thank you for this great tool!
