### ISSUE TITLE
Internal Server Error when calling yabai command

### ISSUE THREAD

**Issue by ddyjis** [felixhageloh/uebersicht#391]
I found that whenever my widget calls yabai command e.g. 
```javascript
export const command = "yabai -m query --windows | jq '.[] | select( .focused | contains(1)) | .title'";
```
Ubersicht server gives 500 Internal Server Error. The command works fine in my terminal. Could anyone advice me what I can do?

Ubersicht version: 1.4
yabai version: 2.3.0

**Comment by ppiotrowicz** [comment]
Try to use full paths 
eg `/usr/local/bin/yabai` and `/usr/local/bin/jq`

**Comment by ddyjis** [comment]
I tried using full paths but still have the error. Do you have any idea how to debug the backend?

**Comment by zweck** [comment]
Did you figure this out?

**Comment by ddyjis** [comment]
I use full path for yabai.

jq is not working for me even though I use the full path so I parse the json using javascript instead

**Comment by felixhageloh** [comment]
as a note: Übersicht does not load your bashrc/bash.profile by default. You can configure it in preferences tho
