### ISSUE TITLE
Copy created widget to widget folder

### ISSUE THREAD

**Issue by nikeyambing** [felixhageloh/uebersicht#404]
Hi all - I need some help with my issue. I'm planning to deploy the app to our 100+ Macs in our company. What I'm trying to achieve is, build a version of the app that has my own widget and logo (png file) baked inside the widgets folder automatically (replacing the getting-started.coffee and Übersichtlogo.png) if possible. I tried to replace both files in Xcode under the supporting files, but when I build/archive the app. The widgets folder is empty. What am I missing or doing wrong? 
I appreciate all the help.

Thank you.

**Comment by felixhageloh** [comment]
Have a look at UBPreferencesController.m#createIfNotExists. It sets up the initial widget directory and copies the geting-started widget

**Comment by felixhageloh** [comment]
closing this issue, but feel free to follow up if you have more questions
