### ISSUE TITLE
"Ubersicht" will damage your computer. You should move it to trash.

### ISSUE THREAD

**Issue by nikeyambing** [felixhageloh/uebersicht#407]
@felixhageloh Thanks for replying to my previous issue. I was able to add the two custom widgets into the widget folder. I was also able to successfully deploy the app on my test machines. Out of nowhere, I'm getting this error message when I try to open Ubersicht. The error message shows on OSX Catalina (the screenshot was taken from BigSur).
![Screen Shot 2020-07-08 at 9 02 48 AM](https://user-images.githubusercontent.com/17793622/86943851-d02a9f80-c0fb-11ea-89dc-21a38dd639c4.png)

**Comment by felixhageloh** [comment]
wow, I have not seen this before. Maybe try re-downloading the app (could be a corrupt download)

**Comment by nikeyambing** [comment]
I was surprised too when i saw the error message. I can certainly re-download the app again.
I'm planning on deploying the app to all the Macs in our company (100+). I'm afraid I can't ask all my users to do that. I will play around with it and see if I can debug and update the app.

**Comment by felixhageloh** [comment]
did you manage to resolve this?

**Comment by nikeyambing** [comment]
Yes, I repackaged the app and so far everything is good.

**Comment by felixhageloh** [comment]
great to hear! Btw, curious to hear what you are using the app for at your company (if I can ask)!

**Comment by nikeyambing** [comment]
I'm using it to display the machine's information so that our user's won't have a hard time finding their TeamViewer ID or remembering our HelpDesk email/portal and extension...

On a side note: the logo is not showing up even though I have the png file added into the Supporting Files, updated the UBPreferencesController. The weird part is, the coffee script I created is working. 👍 

![Screen Shot 2020-09-28 at 8 51 28 AM (2)](https://user-images.githubusercontent.com/17793622/94455641-2b52b800-0168-11eb-8ddf-b670028d64ad.png)

**Comment by felixhageloh** [comment]
Hard to judge what's going on without seeing the widget's code. 

Btw I am offering more extended support through the GitHub sponsorship program; maybe something of interest for your company.
