### ISSUE TITLE
Support react hooks

### ISSUE THREAD

**Issue by entropitor** [felixhageloh/uebersicht#409]
Upgrade react to ~16.7~ 16.8 to support react-hooks

**Comment by MynockSpit** [comment]
16.8, but yes.

**Comment by felixhageloh** [comment]
working on a release with updated npm modules

**Comment by entropitor** [comment]
That's awesome! 😄

**Comment by felixhageloh** [comment]
It turns out that widgets are not compatible with hooks just yet. Hooks need to be called from the top level of a functional component and because of the way widgets are wrapped, that's not the case when using a hook from within the `render` method. 

How were you planning on using hooks, btw?

**Comment by entropitor** [comment]
I was planning on having an internal timer so I can have a clock widget correct to a second while not having to refetch all other data for this widget every second

**Comment by felixhageloh** [comment]
The way to achieve that with Übersicht right now would be something like: 

```jsx
export const init = (dispatch) => {
  setInterval(() => {
    dispatch({type: 'CLOCK_TICKED', time: performance.now()});
  });
}
```

I.e set up a timer when the widget is initialized. You would then use `updateState` to distinguish between timer events vs events generated by `command` and update your state accordingly.

That's not to say that supporting hooks is not necessary. It's a great pattern that many developers are already familiar with. Beginning to think it might be a larger change tho.

**Comment by MynockSpit** [comment]
I'm not familiar with how this is implemented, but if you're just taking the `render` fn and using running inside the `render` method of a class component the following will work, right?

```js
export const render = (state, dispatch) => <MyComponent state={state} dispatch={dispatch} />

function MyComponent({ state, dispatch }) {
  // ... whatever hooks
}
```

**Comment by felixhageloh** [comment]
Very good point, hadn't thought about it! You can basically treat the widget as a container component and defer all the rendering to a functional react component. 
I wouldn't call it full hooks support yet, but good enough to release for now! I will test a bit more for regressions first

**Comment by felixhageloh** [comment]
update was released this morning!

**Comment by MynockSpit** [comment]
Woohoo! As a note for anyone who finds this, you'll need to import React from ubersicht, then pull the hook off that. 

```js
import { React } from 'uebersicht'
const useState = React.useState
```

**Comment by MynockSpit** [comment]
I just found this comment and it helped me again. @felixhageloh -- would you be opposed to adding something to the readme that indicates you can `import { React } from 'uebersicht'` like this?
