### ISSUE TITLE
Unable to use jq library in command 

### ISSUE THREAD

**Issue by JohnAPA** [felixhageloh/uebersicht#415]
When calling a command and using an external library like jq to extract json from a file, the command cant be found for the external library. If I try calling the library in an external script and calling the file, it still breaks for some reason.  

For example
`export const command = "cat file.json | jq '.' "`
`_returns 'jq' command cannot be found_`

I've even gone as far as trying to install jq from NPM which wraps the jq syntax in javascript so it can be utilized in node. Even that doesn't seem to work. 

Any suggestions? I have the feeling that for some reason something is missing in $path in reference to ueber.

**Comment by MynockSpit** [comment]
So far as I know, Ubersicht doesn't run your `.bashrc` or `.bash_profile` by default, so if `jq` is being added to the path by your config files and not in one of the default places, that's probably why. You can turn that behaviour on, but only for bash (I believe) not another shell.

**Comment by JohnAPA** [comment]
Thank you for responding! Would you have any advice by any chance, on how exactly I can turn that behavior on?

**Comment by felixhageloh** [comment]
The option is called 'Load Bash env'  and You can find it in the app's preferences. Alternatively you can also use the full path to your binary (`which jq` will show you the full path)

**Comment by felixhageloh** [comment]
closing issue. Feel free to follow up tho
