### ISSUE TITLE
Have widgets ignore Mission Control

### ISSUE THREAD

**Issue by MynockSpit** [felixhageloh/uebersicht#416]
First of all, I **love** that widgets are now interact-able by default. That's truly excellent! The *only* caveat here is that I have been using Mission Control's "Desktop" action to shove every window to the side except the widgets. B/c they're interactable now, the widgets behave like a window and get hidden too. 

Would it be possible to have them ignore Mission Control? In my ideal world, it'd be configurable per-widget, but I get that that might not be possible given that it's just one web view.

If not, no worries, I can adapt but I figured I'd ask.

**Comment by felixhageloh** [comment]
I would love to have this behavior as well, but wasn't able to get it to work so far. Will keep on trying tho!

**Comment by chunkhang** [comment]
then is it possible to have a setting to revert to the old behaviour, to make it clickable using a modifier key and ignored by mission control?

**Comment by MynockSpit** [comment]
(Just one vote but,) I'd personally prefer not. Interaction by default is excellent. That said, if it doesn't make the code too messy, it might be cool to have the option between *interaction always* and *interaction with a modifier*.

**Comment by felixhageloh** [comment]
I think I managed to make it work. Will test for a while before releasing it

**Comment by felixhageloh** [comment]
Alright, version 1.5.63, released today, should fix it!

**Comment by MynockSpit** [comment]
Just got the update. Love it! Thank you!
