### ISSUE TITLE
Using Show Desktop hides widgets

### ISSUE THREAD

**Issue by jreljac** [felixhageloh/uebersicht#418]
I noticed this after I updated to version 1.5 (62)

With this version, when I hit <kbd>F11</kbd> Show Desktop runs and flies all my screens out of the way to show the desktop.  Before this version I would see my widgets, now the widgets disappear.  If I minimize all apps, the widgets are where they belong.

Is there a setting I am missing to get the old behavior back or is this an issue?  

I'm running macOS 10.15.6

**Comment by jreljac** [comment]
Not sure if this is it but if I uncheck **Enable Interaction** things work as they used to.

**Comment by MynockSpit** [comment]
That is exactly it. See https://github.com/felixhageloh/uebersicht/issues/418.

**Comment by felixhageloh** [comment]
You probably meant https://github.com/felixhageloh/uebersicht/issues/416 🙂. Closing this as a duplicate

**Comment by MynockSpit** [comment]
Whoops, yup.
