### ISSUE TITLE
Disabling server

### ISSUE THREAD

**Issue by 12-Seconds** [felixhageloh/uebersicht#420]
Is it possible to disable the Übersicht Networking process that allows you to view Übersicht in a web browser? It seems to consume a lot of the CPU

**Comment by felixhageloh** [comment]
The server is the actually the core of Übersicht, i.e. also the standard app uses it. If you are seeing hight cpu  usage it is usually one of your widgets that is either 
- updating very frequently 
- doing some expensive drawing operations 
- running a very heavy command

**Comment by 12-Seconds** [comment]
I checked the code of the widgets, and indeed one of it was refreshing too often. Thanks.
