### ISSUE TITLE
[Bug] Uebersicht overlays entire desktop

### ISSUE THREAD

**Issue by 3raxton** [felixhageloh/uebersicht#421]
Great work on Übersicht! It's incredibly enhanced the experience and amount of personalization on my Mac. 

Recently I updated to Übersicht 1.5.62 and have encountered a bug that causes Übersicht to overlay the entire Desktop causing everything under the overlay not to be clickable. I've downgraded to 1.4.60 for the time being because of this issue. I'm not sure if this is due to my Mac or if it's an issue with Übersicht, so I've my specs for my Mac below. 

– MacBook Pro (16-inch, 2019)
– macOS 10.15.6 (19G2021)

Please let me know if there's anything further needed!

**Comment by 23d1** [comment]
I encountered the same issue, so I ended up adding pointer-events: none; where applicable.

**Comment by felixhageloh** [comment]
Thanks! Have a look at https://github.com/felixhageloh/uebersicht/issues/417 - I think it should address your issue

**Comment by felixhageloh** [comment]
This twitter thread might also give some more info https://twitter.com/Felx/status/1302530236907692035

Hoping to add that to the readme soon as well.

**Comment by felixhageloh** [comment]
closing this as a duplicate. Feel free to follow up on this issue still tho
