### ISSUE TITLE
can't use interaction shortcut with the latest updates

### ISSUE THREAD

**Issue by SgtBauerFR** [felixhageloh/uebersicht#426]
Hi,

Since you add the interaction button in the uebersicht preferences. I can't use anymore the interaction shortcut to ⌘+leftclic.

I used to ⌘+left-clicked on prox01 to open an ssh connection in this server.
Now everything is selectable with a single click and its quite hard to get a file behind the widget.

Can you put back the interaction with shortcut ?

Best regards

![Screen Shot 2020-09-30 at 15 50 53](https://user-images.githubusercontent.com/25414651/94697194-2fcdcb00-0338-11eb-9a44-b0e05e762d8e.png)
![Screen Shot 2020-09-30 at 15 51 08](https://user-images.githubusercontent.com/25414651/94697214-34927f00-0338-11eb-943b-88c56afbb981.png)
![Screen Shot 2020-09-30 at 15 51 40](https://user-images.githubusercontent.com/25414651/94697216-35c3ac00-0338-11eb-8926-66f808c4fd64.png)

**Comment by felixhageloh** [comment]
Hi, check out this thread here here https://twitter.com/Felx/status/1302530236907692035. I'm also posting release notes here https://twitter.com/home

I think from those you should get a good idea about the latest developments around interaction and widgets!

**Comment by felixhageloh** [comment]
closing this issue but feel free to follow up with other questions
