### ISSUE TITLE
TypeError: Origin http://127.0.0.1:41416....

### ISSUE THREAD

**Issue by TechJedi51** [felixhageloh/uebersicht#427]
I am getting the error below when trying to fetch a JSON url.

TypeError: Origin http://127.0.01:41416 is not allowed by Access-Control-Allow-Origin.

`export const command = dispatch => {
    let url = new URL(options.protocol + "://" + options.plexpyHost+ "/api/v2");
    url.searchParams.append('apiKey', options.apiKey);
    url.searchParams.append('cmd', "get_activity");

    fetch(url.href)
        .then(response => {
            return response.json();
        })
        .then(data => {
            return dispatch({
                type: 'FETCH_SUCCEEDED',
                data: data
            });
        })
        .catch(error => {
            return dispatch({
                type: 'FETCH_FAILED',
                error: error + " - " + url
            });
        });
}
`

**Comment by alex-taxiera** [comment]
`http://1270.0.01:41416`
Is this URL correct?

localhost would be `127.0.0.1`

**Comment by TechJedi51** [comment]
Yep, that was a type. it is localhost (127.0.0.1)

**Comment by TechJedi51** [comment]
Here is the actual error message:
![Screen Shot 2020-10-07 at 10 33 17 AM](https://user-images.githubusercontent.com/28914268/95366683-9d25b280-0888-11eb-9b61-3594786dd93c.png)

**Comment by TechJedi51** [comment]
Here is the actual error:
![Screen_Shot_2020-10-07_at_10_33_17_AM](https://user-images.githubusercontent.com/28914268/95366930-f42b8780-0888-11eb-9bb6-6f3bf61997d2.png)

**Comment by TechJedi51** [comment]
Not sure if this will help, but I downloaded the Newsticker widget and am getting the same error:
https://raw.githubusercontent.com/freakimkaefig/uebersicht-newsticker-widget/master/newsticker.widget.zip

**Comment by TechJedi51** [comment]
It appears the the Proxy server isn't setting the origin header:

`Missing required request header. Must specify one of: origin`
