### ISSUE TITLE
Displaying Home Assistant Sensor

### ISSUE THREAD

**Issue by PeteSSMMSS** [felixhageloh/uebersicht#428]
Hey I'm wondering how I can display a [Home Assistant](https://www.home-assistant.io/) Sensor via [CLI](https://github.com/home-assistant-ecosystem/home-assistant-cli)? I tried

`command: "export HASS_TOKEN=MYHOMEASSISTANTTOKEN /usr/local/bin/hass-cli -o json state get sensor.test | /usr/local/bin/jq -r '.[].state'"`

but I get this error:

```
[Error] SU_ActualSale_Kopie-index-coffee: – Error: bash: line 1: export: `/usr/local/bin/hass-cli': not a valid identifier
bash: line 1: export: `-o': not a valid identifier
bash: line 1: export: `sensor.test': not a valid identifier
```

**Comment by fishcymbal** [comment]
Sorry if this is obvious but just a question, since I've made this mistake before -- do you have a back-tick (`) at the beginning and a single quote ( ['] apostrophe) at the end? Should they both be back-ticks?

**Comment by felixhageloh** [comment]
I think you don't need `export` here, so this should work:

```
command: "HASS_TOKEN=MYHOMEASSISTANTTOKEN /usr/local/bin/hass-cli -o json state get sensor.test | /usr/local/bin/jq -r '.[].state'"
```

**Comment by felixhageloh** [comment]
closing this issue but feel free to follow up!

**Comment by PeteSSMMSS** [comment]
Thank you very much @felixhageloh! Seems to work now, the only problem is that I only need the last line from the three (12:13) - The first two ones only appear while connecting to the Home Assistant server
![SCREENSHOT-2020-11-19 at 12-11-11](https://user-images.githubusercontent.com/54634565/99659425-253ed080-2a61-11eb-92e1-b53d8dca0525.png)
