### ISSUE TITLE
Cannot show/hide widgets after waking from sleep

### ISSUE THREAD

**Issue by mlcampbe** [felixhageloh/uebersicht#433]
I reported this same problem back in issue #269  but it somehow resolved itself at some point. However, I am now running on another machine (macbook if that makes any difference) and seeing the same behavior again.

In essence after the machine sleeps and wakes back up the displayed widgets continue to update properly but I've noticed 3 issues after the machine wakes:
1 - If I add or delete a new widget from the widget folder that is not recognized until I restart the program.
2 - If I edit one of the running widgets the changes are not reflected in the running widget until I refresh all or restart the program
3 - Using the menu bar and selecting either hide or show widget does nothing. If the widget is already visible then hiding it does not work and similarly if I try to show one that is hidden it does not appear.

Any ideas as to what is going on?

**Comment by mlcampbe** [comment]
I've updated the subject as I have determined that the problem occurs for me even after the screensaver kicks in and I then unlock the machine. Once unlocking the machine the existing widgets are still running as expected but again the 3 problems listed above starts to occur. Even after using 'refresh all widgets' still no resolution until I restart the app.

Oddly enough if I access http://127.0.0.1:41416/69992768 in a browser I do not have problem (2). If I edit a running widget, save it, then access http://127.0.0.1:41416/69992768 those changes are seen there just not reflected on the desktop.

**Comment by felixhageloh** [comment]
thanks for the detailed report! I will see if I can reproduce

**Comment by mlcampbe** [comment]
Just to add a few more facts. After the screensaver engages and I wake it back up and I go to the system menu and select any widget to hide/show the option dot beside the widget does not change nor does the checkmark beside 'hide widget' ever check or uncheck.

**Comment by mlcampbe** [comment]
I removed all of my widgets from the widget folder and added back in a single simple widget for the weekend. This morning all was working properly. Therefore this could be related to one of my custom widgets. I am going to try adding in individual widgets and see if I can identify which one may the cause of the problem.

**Comment by mlcampbe** [comment]
Is there any chance this problem could be related to widgets that require internet access? I removed all widgets from the folder and started enabling them 1 by 1. I see that the ones that do local stuff (files, images, calendar, IP) all work fine after a system sleep/wake up. But, as soon as I put in a widget that requires internet access the problem occurs. Is it possible that these widgets are trying to access the internet before the connection is re-established after waking up and causing a hang?

**Comment by mlcampbe** [comment]
I can confirm now that the problem is related to widgets that need internet access to work. I have 8 widgets that do not require internet access and if ONLY these 8 widgets are loaded into the widgets folder I have no problems at all after waking from sleep.

However, I have 5 widgets that require internet access to pull data (weather, speedtest, images, bible verse, etc). As soon as I add any of these 5 widgets to the widget folder the problem occurs. It seems that I do not have to even have the widget enabled to cause the problem. Just the fact that 1 of these widgets is in the widget folder will cause none of the widgets to be able to be shown/hidden.

**Comment by the-sweet** [comment]
I have this issue as well, where I only have one widget (out of three total) that requires Internet for this to happen.
