### ISSUE TITLE
Latest version 1.68(68) brakes some widgets

### ISSUE THREAD

**Issue by metatron23** [felixhageloh/uebersicht#436]
I have updated today to latest version and new version brakes some widgets  (istat, darksky).

[https://d.pr/i/uR4bxD](url)
[https://d.pr/i/ddH7aC](url)

**Comment by felixhageloh** [comment]
hey thanks for the report. Do yo see any errors in the console? The root url for the widget window has changed, which could be the reason for them breaking

**Comment by metatron23** [comment]
I see error for darksky: "An error occured trying to load resource" (rain.png), but I don't see anything for istat.

**Comment by metatron23** [comment]
So it is up to developers of widget to fix this?

**Comment by felixhageloh** [comment]
yeah I I will send a head up to developers to adjust their code. If you are able to adjust the code yourself you can probably fix the issue quickly as well. Basically, you need to change the path for all images to start with a slash `/`

**Comment by metatron23** [comment]
Ok, will try to fix it myself.
Thx again!

**Comment by felixhageloh** [comment]
after some consideration, i've disabled the update again to give me some time to review wether I can achieve the same thing without breaking a lot of widgets. You can downgrade the app by downloading it again from the website (should revert to 1.6.66).

**Comment by metatron23** [comment]
Great, great work as always!
