### ISSUE TITLE
Output formatting question

### ISSUE THREAD

**Issue by computeristic** [felixhageloh/uebersicht#443]
I am not a developer so I'm not familiar with javascript or react. I have a couple of python and shell scripts that more than one line of text. I am wondering how I can apply formatting to each line of the output individually. Eg, I'd like to indent the beginning of each line, or make the first word of each line bold. If anyone can point me in the direction of a relatively beginner-friendly resource or give me an example of code, it would be greatly appreciated.

**Comment by computeristic** [comment]
Also, when I print a line with leading space, the space gets deleted (I have 'text-align: left;' maybe this is the reason). Is there a way to keep the space?

**Comment by upstageleft** [comment]
I usually output values as a string with commas separating chunks I want to format separately, then in the render function I use output.split(',') to create an array of the separate values and then apply the formatting to the elements in the array by index.
