### ISSUE TITLE
Widgets not working on Mac os Big sur

### ISSUE THREAD

**Issue by Hikari31** [felixhageloh/uebersicht#448]
I tried to use the widgets but this error sign popped up. I don't really know how to code yet. Does anyone know what to do?
<img width="722" alt="Screenshot 2021-04-22 at 7 17 03 PM" src="https://user-images.githubusercontent.com/83011571/115705798-89aee480-a39f-11eb-8d08-534e165e9d58.png">

**Comment by 2lach** [comment]
Hey @Hikari31 i'am running übersight Big Sur with no issues.
That specific error is related to React/JSX and not necessarily übersight.
[Here](https://stackoverflow.com/questions/66220168/error-objects-are-not-valid-as-a-react-child-found-object-with-keys) you can look at a similar error and how to solve it.

Have a good one 😄

**Comment by Hikari31** [comment]
> Hey @Hikari31 i'am running übersight Big Sur with no issues.
> That specific error is related to React/JSX and not necessarily übersight.
> [Here](https://stackoverflow.com/questions/66220168/error-objects-are-not-valid-as-a-react-child-found-object-with-keys) you can look at a similar error and how to solve it.
> 
> Have a good one 😄

Hey @2lach thanks for your reply. The only problem is I dont know where or how to replace the code. I have looked at the all JSX files and none of them have "const List = (title: any, children: any) => ( ". I have tried the debug console but I simply do not understand any of it. Can you please tell me where I can add/replace the code? Thanks in advance.
<img width="1000" alt="Screenshot 2021-04-26 at 3 45 30 PM" src="https://user-images.githubusercontent.com/83011571/116047363-93d62900-a6a6-11eb-9632-7935bb928039.png">
<img width="997" alt="Screenshot 2021-04-26 at 3 45 55 PM" src="https://user-images.githubusercontent.com/83011571/116047373-98024680-a6a6-11eb-9887-386df73179f5.png">
<img width="1000" alt="Screenshot 2021-04-26 at 3 46 01 PM" src="https://user-images.githubusercontent.com/83011571/116047378-99337380-a6a6-11eb-809f-91432f14ecef.png">

**Comment by 2lach** [comment]
Ah if i'am not misstaking  your running the iStat wigdet (its a nice one)
Have your followed the setup guide found here:
You need a gem (Ruby pkg) to run it.
Follow the steps in the Readme found here:
https://github.com/roele/istats.widget

And if the problem doesn't solve itself let me know


Have a good one 😎

**Comment by Hikari31** [comment]
> Ah if i'am not misstaking your running the iStat wigdet (its a nice one)
> Have your followed the setup guide found here:
> You need a gem (Ruby pkg) to run it.
> Follow the steps in the Readme found here:
> https://github.com/roele/istats.widget
> 
> And if the problem doesn't solve itself let me know
> 
> Have a good one 😎

hey thanks for your swift reply again. I did in fact try to download the ruby gem but this error appeared and again I really have no clue. Do you by any chance know what this means? Sorry for troubling you so much. Thanks in adavnce
![Screenshot 2021-04-26 at 7 49 40 PM](https://user-images.githubusercontent.com/83011571/116078445-30a9be00-a6c9-11eb-88ab-dadfb156dd7c.png)

**Comment by 2lach** [comment]
Hey don't worry about it everybody was new in the beginning 😉
So the error above indicates that your mac user (you can get your username by running `echo $USER` in the terminal does not have system admin rights.
Which is why you can't install the package

To fix this you need to update your users permisson level to admin.

You do this in mac setting > users
Follow the steps here:
https://www.wikihow.com/Become-an-Administrator-on-a-Mac

Then reboot your computer and try installing the Gem again

Let me know how it works out 😎

**Comment by Hikari31** [comment]
> Hey don't worry about it everybody was new in the beginning 😉
> So the error above indicates that your mac user (you can get your username by running `echo $USER` in the terminal) does not have system admin rights.
> Which is why you can't install the package
> 
> To fix this you need to update your users permisson level to admin.
> 
> You do this in mac setting > users
> Follow the steps here:
> https://www.wikihow.com/Become-an-Administrator-on-a-Mac
> 
> Then reboot your computer and try installing the Gem again
> 
> Let me know how it works out 😎

Once again thanks for such a quick response. IT FINALLY WORKED! TYSM.

**Comment by 2lach** [comment]
Think nothing of it 😄  
One day you will be the one with the answers, and it might very well be me looking for those answers :wink

**Comment by felixhageloh** [comment]
thanks for you help @2lach. Closing this for now
