### ISSUE TITLE
[Bug] Transparent Widget keeps randomly flashing

### ISSUE THREAD

**Issue by twio142** [felixhageloh/uebersicht#463]
As in the screenshot:
![output](https://user-images.githubusercontent.com/64556708/128658730-4903ee9e-e21c-42ac-957d-9b31395b5d84.gif)

The transparency setting seems to fall apart. 
Removing `-webkit-backdrop-filter` or `-webkit-box-shadow` didn't help, yet removing both of them did.
I already stoped this widget from auto refreshing, it still keeps flashing.

Any idea why this happened and how I could fix it?

**Comment by twio142** [comment]
Console gives this error: 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by mister-infinity** [comment]
Dear @twio142 try running http://127.0.0.1:41416 and inspect the element. Maybe the refresh rate is not ok?

**Comment by twio142** [comment]
Hi. I checked this on http://127.0.0.1:41416, and it seems like there is no flashing (was hard to tell without a background wallpaper).

The blurring effect was not rendered, yet the shadows were.

![image](https://user-images.githubusercontent.com/64556708/141174455-e09b57d0-0069-4de6-8ed3-0e6f04d29989.png)

What would you advise me to do if it was indeed a problem of the refresh rate?

**Comment by je-kizer** [comment]
@twio142 I'm having the same issue, were you able to resolve this?

**Comment by twio142** [comment]
> @twio142 I'm having the same issue, were you able to resolve this?

Try changing all `-webkit-something` to `something`, like `-webkit-backdrop-filter` to `backdrop-filter`, or try using them both.

**Comment by je-kizer** [comment]
`backdrop-filter` doesn't seem to function at all without the `-webkit-' part. The flickering is really just that one effect working and not working intermittently, so when the effect doesn't work at all, naturally it stops flickering.

I've noticed the flickering might be tied to focus somehow. Like if the effect flickers off, hovering the cursor over the widget causes the effect to turn on again.
