### ISSUE TITLE
Run Local Script

### ISSUE THREAD

**Issue by LucaDillenburg** [felixhageloh/uebersicht#473]
I was wondering how I could run some scripts locally after a click for example.

I tried the following but the import doesn't work.
```jsx
const { exec } = require('child_process');
// exec is undefined
```

Also tried creating a ```package.json``` and adding the ```child_process```, but it did not work either.

I want to do something similar to [this Issue](https://github.com/felixhageloh/uebersicht/issues/91), but with React instead of CoffeeScript.

Thanks in advance.

**Comment by neoswallow** [comment]
You can use `run` provided by Übersicht.
```javascript
import { css, request, run, styled } from 'uebersicht'
```

**Comment by LucaDillenburg** [comment]
Thank you @neoswallow
