### ISSUE TITLE
Force update of a specific widget via commandline

### ISSUE THREAD

**Issue by robsalasco** [felixhageloh/uebersicht#50]
Hi! I have a imap idle script running on my machine and I want to "push" a notification to uebersicht for updating the widget every new mail arrives. Could be this possible in a future? I really like some kind of widgets awaiting for input instead of reloading a script every X seconds. Thank you for your work!

**Comment by felixhageloh** [comment]
You can now probably do this by using this script 

```
 osascript -e 'tell application "Übersicht" to refresh widget id "my-widget"'
```

Check the readme section for Scripting Support (also for getting the `Ü` right)

**Comment by nilliu** [comment]
ah, I was came to here because the idea to add an click event to manually trigger the widget refresh.

anyway, want to update the script example here, 
end up I get it working as following code.
```coffee
afterRender: (domEl) -> 
    $(domEl).on 'click', '#langtext', => 
        @run "osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"daily-random-kanji-widget-main-coffee\"' "
```  

for `Übersicht` 1.6.69,
thank you for you guys.

FYI.

world peace. 

-Nil
