### ISSUE TITLE
How to find the widget id for specific widget?

### ISSUE THREAD

**Issue by yuchen-lea** [felixhageloh/uebersicht#511]
Thanks for this great work! I'm trying to use apple script to control Uebersicht, refreshing all widgets works:
```
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh' 
```

But refreshing widget with id doesn't. I guess I didn't get the correct id.

For example, I want to control this widget:
<img width="363" alt="图片" src="https://github.com/felixhageloh/uebersicht/assets/7555085/c1d734a5-fc96-413c-a53f-0206509ff74e">

and it was located in `…/Übersicht/widgets/particals.widget/index.js`

I tried following, but none of them worked:

```
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "particles"'
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "particles-widget-index-js"'
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "particles-js"'
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "particles-index-js"'
```

Environments:
- Übersicht 1.6
- MacOS Ventura 13.3.1 on M1 Max

**Comment by ajrosen** [comment]
So close!  Refresh is for all widgets, _reload_ is for an individual widget.

`osascript -e 'tell application id "tracesOf.Uebersicht" to **reload** widget id "particles-widget-index-js"'`

**Comment by yuchen-lea** [comment]
Oh, thank you sooooooooo much! Maybe we could update the readme
<img width="869" alt="图片" src="https://github.com/felixhageloh/uebersicht/assets/7555085/db52cf68-776f-4fc0-94c1-b8b9c4e9b061">
