### ISSUE TITLE
Different widgets on different displays/spaces

### ISSUE THREAD

**Issue by nigobo** [felixhageloh/uebersicht#52]
Thanks for an awesome utility, I really love it! 

I really would like to have the ability to place a widget on a specific desktop/space. I think that the GeekTools-guy told me that there wasn't any way to identify the current desktop/space. And with desktop/spaces I refer to the different "views" per display presented in the Mission Control.

**Comment by alins** [comment]
+1 for me as well.

**Comment by alins** [comment]
quick proposal:

how about exposing the monitor number (or name) as a property to the script?. if is not set in the widget than the default monitor as selected from the menu is used, if set than that widget is renderer on the specified monitor. this will not solve the spaces problem, on the specified monitor the widget will be displayed on all spaces in this proposal. i don't know how complex this is, honestly i figure is not that complex since detecting the monitors is already done.

let's take as example:

**Comment by felixhageloh** [comment]
finally got around building this. Anyone interested in being a beta tester?

**Comment by oisin** [comment]
Happy to try it out here.

**Comment by nigobo** [comment]
Awesome! Yes please! :)

**Comment by alins** [comment]
yes please

**Comment by felixhageloh** [comment]
Here you go guys https://dl.dropboxusercontent.com/u/49351082/Uebersicht-0.8beta.app.zip
Let me know here if you find any issues (which is likely :) )

**Comment by nigobo** [comment]
Looks like it's working. :) I will try it out more as soon as I get to my second screen. I can't find any way to select a specific space. Does this release only cover physical displays?

Great work!

**Comment by alins** [comment]
yap, working pretty good so far. i have 3 monitors (including the build-in one), each monitor has two spaces.so far my widgets are showing exactly where i want them in all spaces.

Awesome job!

**Comment by felixhageloh** [comment]
great to hear! Did you guys get a chance to play around with different settings as well (sending a widget to a specific screen etc)?

@nigobo this is indeed only for physical displays. OS X provides no official way of identifying different workspaces (AFAIK)

**Comment by alins** [comment]
yes, for me that part seems to work (sending a widget to a specific screen or select 2 screens out of 3 for a widget to show up to).

some minors things (usability):
1. What is 'edit' suppose to do? i don't see anything happening
2. when i choose "Show only on selected screens" the menu closes and it automatically selects all the screens. if i want to actually 'select the screen' i need to open the menu again and make my selection. not a big deal, just not obvious at all what's going on

**Comment by leothelocust** [comment]
Using that beta app link I'm getting an error on this file any ideas?  (part of this widget https://github.com/herrbischoff/nerdbar.widget)

````coffee
#background.coffee
command: ""

render: (output) ->
  ""

style: """
  top: 0
  left: 0
  height: 20px
  width: 100%
  background-color: #171717
  z-index: -1
"""
````

**Comment by felixhageloh** [comment]
@leothelocust thanks for mentioning! The problem is the empty `command` - I reported the issue to the widget author https://github.com/herrbischoff/nerdbar.widget/issues/4. I had made the validations for widgets more strict, which is something I'd like to re-introduce in the future, but for now I will revert it to the old behavior. New beta version coming soon!

**Comment by leothelocust** [comment]
Thanks for the update @felixhageloh! For now, i just did this:

````coffee
#background.coffee
command: "echo ''"

render: (output) ->
  "#{output}"

style: """
  top: 0
  left: 0
  height: 20px
  width: 100%
  background-color: #171717
  z-index: -1
"""
````

**Comment by felixhageloh** [comment]
@leothelocust you can also just use `refreshFrequency: false` and omit `command` altogether. Anyway, I've updated the app (same link) with fixes!

@alins  good feedback, thanks!
1. It is supposed to open the widget in your text editor of choice. I guess it goes wrong if you have no app/editor configured to open .coffee or .js files. I've added a check for that and I'm now showing a warning notification if that's the case.

2. That behavior bugged me as well! I did another iteration over the UI design - some things still feel a bit off, but let me know what you think! 

The new version is available under the same link!

**Comment by leothelocust** [comment]
thanks again @felixhageloh 

got another error on that beta one now, everything seems to still work, but here is the error:

```
Library/Application Support/Übersicht/widgets/now-playing.widget/scripts/jquery.textfill.min.js: SyntaxError: Unexpected token (              exports client.js:3547
```
The above error may have been present before, but not sure.

The other error I get happens after I click "Refresh All Widgets" and here it is:
```
nerdbar-widget-prefix-coffee:  – "error running command"          redraw client.js:3610 
```

Neither of these seem to affect the outcome, but just thought you would want to know.

Thanks again!

**Comment by felixhageloh** [comment]
@leothelocust I think it has to do with the widgets themselves. Let me know tho if you see any widgets that used to work and stopped working in the latest version!

**Comment by felixhageloh** [comment]
This has been added with the 0.8 release!

**Comment by fleicher** [comment]
The above beta link of version 0.8 is dead and I couldn't find any option in the Übersicht menu to show a widget only for a specific desktop/space. Where does the functionality hide in version 1.4 
Also great job, man!

**Comment by ohnoitsfraa** [comment]
I am also looking for this functionality, especially about being able to only show it on one space instead of all spaces. Is this possible in the current version?

**Comment by firewalkwithB** [comment]
man this is the single issue preventing me from having my display exactly as i'd like it
any progress would be greatly appreciated!

**Comment by felixhageloh** [comment]
@fleicher thanks, I wish I had more time for Übersicht these days! The feature in the 0.8 beta is now part of the standard release. As you guessed it is only for attaching widgets to a specific screen (see my comment here https://github.com/felixhageloh/uebersicht/issues/52#issuecomment-184826978)
