### ISSUE TITLE
Feature: Allow use of geolocation API

### ISSUE THREAD

**Issue by filipebarros** [felixhageloh/uebersicht#59]
As it stands, when trying to use the geolocation API (I am trying to adapt your weather widget to allow a user not to hardcode the location), it just throws a ReferenceError: navigation is not defined. 

I understand that this might not be a bug, for me it's more of a new feature.

Best regards

**Comment by farski** [comment]
When using the location data to determine what data is being requested from some given API, is there a better way to get the coordinates into the command than something like this?

```
apiKey: '1234512345123451234512345'
coords: false # or default values
exclude: 'minutely,hourly,alerts,flags'

command: "curl -sS 'https://api.forecast.io/forecast/#{@apiKey}/#{@coords}?units=si&exclude=#{@exclude}'"

render: (output) ->
  console.log 'Checking for location...'
  window.geolocation.getCurrentPosition (geo) =>
    if geo && geo.position && geo.position.coords
      lat = geo.position.coords.latitude
      lon = geo.position.coords.longitude
      
      console.log 'Location: ' + lat + ', ' + lon
      
      @coords = lat + ',' + lon
      
      @command = "curl -sS 'https://api.forecast.io/forecast/#{@apiKey}/#{@coords}?units=si&exclude=#{@exclude}'"
      @refresh()
#  
  "<h1></h1><h2></h2>"
```

**Comment by TraderStf** [comment]
Perhaps this can help
http://phantomjs.org

**Comment by felixhageloh** [comment]
@farski no at the moment I haven't found a much better way either. You can check the [pretty weather widger](https://github.com/felixhageloh/pretty-weather/blob/master/pretty-weather.widget/index.coffee) (look for the `afterRender` method), but it is pretty much the same as you are doing. 

I'm thinking of eventually adding a wrapper over the standard geolocation api that could make it easier, but the exact way hasn't quite crystallised in my head yet. Open to suggestions!
