### ISSUE TITLE
UX for widgets page

### ISSUE THREAD

**Issue by phaseOne** [felixhageloh/uebersicht#63]
After watching a few people attempt to download widgets with no prior knowledge of Übersicht, it's clear that the user experience needs to be different.

People click on the image in attempts to download the widget. Therefore, clicking on the image should initiate a download. The text should also be changed from "click for more details", to "click to download". Perhaps a download icon should also be added.

The description might be able to stay, but it also covers up the image while people are deciding whether or not to download the widget. Perhaps making the blur less intense, and making the overlay more translucent will help with that.

The text at the bottom that says download should remain, but there should be a link right next to it that says "view on GitHub".

Here's what I'm thinking:
![](https://dl.dropboxusercontent.com/u/3777028/Example-Hover.gif)

**Comment by felixhageloh** [comment]
so I got a bit carried away with this one and ended up implementing a popup with the widget details and a download link instead. Let me know what you think and if this fixes the issue :)

**Comment by larkov** [comment]
The new popup window is great! At least when the repos contain a Readme :)
