### ISSUE TITLE
A few questions on widget writing

### ISSUE THREAD

**Issue by edasque** [felixhageloh/uebersicht#7]
Hoping to understand the runtime env better so I can code some widgets:

• Is Uebersicht limited to one screen right now? How do you control which screen it's running on? It seems that positioning the widgets off one screen doesn't make it appear in the others.

• It seems render doesn't have access to global variables set before it. Are they not in scope for some reason?

``` coffeescript
note = "bob"
command: "date"
refreshFrequency: 10000
render: (output) -> """
  <h3>#{output} #{note}</h3>
...
```

• Can I make calls to external modules within the render or update methods? As I understand it, this is executed in node so I should be able to require modules, right?

``` coffeescript
loremIpsum = require('lorem-ipsum')
loremString = loremIpsum();
```

Specifically I am hoping to make use of the vast node.js ecosystem to generate the HTML content for the widget

• Why is `command` mandatory/required. With the `update: (output, domEl) ->` mechanism and access to node.js modules, one could get all the info they need without resorting to calling a shell.

• When the coffeescript compiles but throws an exception at run time, the debug console doesn't show it (admittedly because it shows browser side output, not node.js output). Where can I see the node.js side errors? 

I am sure I'll have others but for now this would help tremendously. Looks like the start of a great app. I am tired of Geektool idiosyncracies.

**Comment by jhvanophem** [comment]
So how many things were implemented from this discussion, and what still needs to be done?

**Comment by felixhageloh** [comment]
@jhvanophem sorry for the late response. From the top of my head:
- multiple screens are supported now
- you can require npm modules 
- `command` is not mandatory anymore (if `refreshFrequency` is set to false)
- I would need to double check but I think global vars also work now

**Comment by motleydev** [comment]
Is there an example of how to to "require" a node module in the script? Just like normal with a var x = require(...) ? Do I understand the docs correct that this is only available if using coffeescript? Thanks!

**Comment by motleydev** [comment]
Also, if this is running with node in the background, does it mean that it uses the default version of node? IE if I set a default with NVM it will use that and if so does it mean that I can use es6 syntax as long as my node version supports it?

**Comment by felixhageloh** [comment]
Did you figure out how to use `require` - I think there were some answers in another thread?

Regarding node, there are a few things to keep in mind: 
- all js code in widgets runs in a 'browser' so the node version doesn't really matter. The browser is a WebView which is in sync with the current version of Safari you have on your system, so it supports anything that your version of Safari does. Regardless of that, all widgets, except plain JS ones are compiled using babel, so you can use ES6 in JSX widgets. 
- You can make a node script which you can call as your command, in which case you can use whatever version of node you have installed on your system. Keep in mind that by default Übersicht doesn't load your .bash_profile so you might have to do that manually in your command (or use full paths to your node binary)
- Übersicht does come with its own version of node but it is not easily possible to access it (it is called `localnode` and is inside the Übersicht app bundle)


Hop this helps!
