### ISSUE TITLE
Basic Applescript Support

### ISSUE THREAD

**Issue by skonesam** [felixhageloh/uebersicht#73]
Would love to have a very basic applescript or shell script interface – mostly to refresh widgets without having to go spelunking through the menu bar. (Or does this already exist and I'm just missing it?)

**Comment by alins** [comment]
yes please, that would be awesome

**Comment by felixhageloh** [comment]
agreed, it sounds like nice feature!

**Comment by andrewheiss** [comment]
Ooh. Just came here to make the same request. With GeekTool, refreshing all widgets is as simple as `osascript -e 'tell application "GeekTool Helper" to refresh all'`. Something similar for Übersicht would be fantastic.

**Comment by jdaverth** [comment]
+1 on this - have no idea how to implement myself but for me this is the number benefit of GeekTool over ubersicht.  I have a number of widgets refreshing on too long of a frequency to cut down on CPU cycles -- would vastly prefer to script out an interaction that just updates on demand the few times per day I actually need them to.

**Comment by jdaverth** [comment]
Just to revive this discussion -- if Applescript is not an easy add, then I would appreciate any advice on another method to trigger a global refresh outside of the menu bar icon.  Javascript, perhaps?

**Comment by farski** [comment]
@jdaverth Adding scriptability to a Cocoa application in many cases can be [fairly trivial](http://www.apeth.net/matt/scriptability/scriptabilityTutorial.html). Since it seems like this would be a simple implementation, wherein a script call just needs to call an [existing method](https://github.com/felixhageloh/uebersicht/blob/master/Uebersicht/UBWindow.m#L86) perhaps you or someone else requesting the feature could take a shot at adding it?

**Comment by flipdoubt** [comment]
+1 - I would love to use AppleScript to show tasks from Things on my desktop using the Things API from https://culturedcode.com/things/download/ThingsAppleScriptGuide.pdf.

**Comment by hawkrives** [comment]
@flipdoubt You should be able to do that now, with a widget who's command is an applescript script. [fitzagard/omnifocus-widget](https://github.com/fitzagard/omnifocus-widget) is an example of a widget that uses that method.

For your stated goal of a Things widget, you might look at [digitalbias/things.widget](https://github.com/digitalbias/things.widget).

**Comment by felixhageloh** [comment]
AppleScript support has been released in 1.1.45 yesterday

**Comment by andrewheiss** [comment]
Thanks! This is delightful.

![image](https://cloud.githubusercontent.com/assets/73663/21991414/7ea87dc0-dbe0-11e6-9fa9-85a15c7e1d83.png)
