### ISSUE TITLE
Change name of Application Support folder to U(e)bersicht

### ISSUE THREAD

**Issue by deanishe** [felixhageloh/uebersicht#77]
As noted in the README, the Ü in Übersicht sometimes causes problems for `git`. This isn't the only developer tool it causes problems for.

While I realise that's the fault of the tools, there are quite a few of them (some Sublime Text Python plugins don't like it; powerline for vim chokes on it, and GitHub doesn't really like umlauts either).

I think it'd cause far fewer problems if Übersicht's Application Support folder didn't have the Ü in it, and were called `Uebersicht` instead.

Beyond that, not everybody knows how to make an Ü with a non-German keyboard, nor are they aware of the ü -> ue convention in German.

In view of the latter, `Ubersicht` might be a better, if less correct, alternative.

**Comment by felixhageloh** [comment]
Probably not :)

It wasn't fun (Xcode not being really helpful either), but I've renamed the application folder to Uebersicht

**Comment by deanishe** [comment]
Love that you can now select the widget folder: No more need to keep it in ~/Library. Marvellous :+1:
