### ISSUE TITLE
XMLDocument support?

### ISSUE THREAD

**Issue by OscarBarrett** [felixhageloh/uebersicht#79]
I'm parsing an XML file using DOMParser (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser). In the browser debug window, the resulting object is of type `XMLDocument` but in the widget it is just `Document`.

    command: 'curl -s host/document.xml'
    refreshFrequency: 10000

    update: (output, domEl) ->
      parser = new DOMParser
      xmlDoc = parser.parseFromString(output, 'text/xml')
      ...

I also tried using `application/xml` as the mime type.

It's not a big deal as I can still parse it as a `Document` object, but is there a reason why DOMParser doesn't create an `XMLDocument` object in the widget?

**Comment by felixhageloh** [comment]
not quite sure tbh. I'll have a look if that is something that isn't supported by the standard WebView

**Comment by felixhageloh** [comment]
had a quick look, and Safari and Chrome seem behave the same - did you use Firefox for this? If so, then I think this is a WebKit specific thing (which is what Übersicht is using)

**Comment by OscarBarrett** [comment]
I was using Chrome, which shows it as XMLDocument. I just checked in Safari, and it has an XMLDocument class but it doesn't look like their implementation is complete yet (and the W3 specification for Document/XMLDocument is still a "Working Draft") . Thanks for looking into it.
