### ISSUE TITLE
Is there any way to run shell commands from <button onClick=""> action?

### ISSUE THREAD

**Issue by brookesdjb** [felixhageloh/uebersicht#80]
I am trying to create a widget with a button to toggle a fixed ip with command: "sudo ipconfig set en1 INFORM 192.168.0.150"

Is there any way to use the @run(command, callback) as a function connected to the button onclick="" action?

**Comment by felixhageloh** [comment]
I don't think you can use the onclick attribute like that - although it might a good idea to make that work. For now you have to bind the action using javascript. For example, in `afterRender` you can do: 

```
afterRender: (domEl) ->
  domEl.find('selector for you button').on 'click', => @run( ...

```

Note that you need to use the fat arrow `=>` to make sure that `this` is bound properly

**Comment by brookesdjb** [comment]
Amazing, thanks so much. I havnt seen many interactive widgets out there yet, I hope more people take advantage of it soon. 
Here is my finished widget, or first revision anyway; https://github.com/brookesdjb/Set-networking.widget

I have also posted it as an issue in your widgets repo.

**Comment by felixhageloh** [comment]
Glad it worked out :) I saw your widget request and I will get to it ASAP!
