### ISSUE TITLE
Document uninstall process.

### ISSUE THREAD

**Issue by Zegnat** [felixhageloh/uebersicht#82]
People use all sorts of third-party applications to get rid of their applications these days. Dragging the app bundle to the trash no longer cuts it as people are more and more worried about cluttering their systems with metadata files.

Übersicht seems to put files outside of its app bundle as well. Maybe these files could be listed somewhere for people who really want to make sure they do a complete uninstall?

![Screenshot: AppCleaner showing Übersicht related files.](https://cloud.githubusercontent.com/assets/6445731/3510954/9a42d9c0-06ab-11e4-8648-473908796c91.png)
(Screenshot taken from [a previous issue, made by Spencer](https://github.com/felixhageloh/uebersicht/issues/24#issuecomment-48343118).)

**Comment by felixhageloh** [comment]
I agree in principal, but as far as I know these files are the same as any other app (with some sort of preferences) would leave lying around. In other words, I am not creating these files, they get created as a result of using the standard App framework that OS X provides. I also have no control over where they get created and those places might be different in different versions of OS X. So as far as listing these files in the documentation goes, I think people are better served with checking Apple's documentation where Apps store standard preferences on their version of OS X

**Comment by Zegnat** [comment]
Ah, interesting, I never knew Apple would create those files whether an application requested them or not. Closing this then, sorry to be a bother.
