### ISSUE TITLE
No widgets work / Mysterious error

### ISSUE THREAD

**Issue by aastratinei** [felixhageloh/uebersicht#84]
Not sure why this is happening but whatever widget I try to install I get this error message. I'm running OS X 10.10.2
![screen shot 2015-01-26 at 16 32 12](https://cloud.githubusercontent.com/assets/10710553/5902111/94b11dae-a580-11e4-9885-b8e86459140a.png)
I didn't change any of the widget css, I simply downloaded the widget from safari, the folder is automatically unzipped so I move the '.coffee' file to the 'widgets' folder. It happened with all the ones I tried, and also if I moved the entire folder (and not just the '.coffee' file) and it also happened when I tried to edit the text on the 'getting started' widget (it wasn't the css it was just the actual writing in the widget).

**Comment by felixhageloh** [comment]
So two things I can think off:

- are you using TextEdit to modify the file? TextEdit is known to break widgets (it messes up the formatting)

- that wouldn't explain widgets breaking that you didn't edit. Do you maybe have a virus scanner installed, or anything that could touch files that are put in the Downloads folder?

**Comment by aastratinei** [comment]
I did open one widget with textedit, but like you said that doesn't really explain why all the other one's won't work. I don't have any anti-virus scanners. PS: what application can I open them with?

**Comment by felixhageloh** [comment]
You can use any 'code' editor like http://www.sublimetext.com or Xcode 

Do you have an example widget that broke without modifying it (so I can try it here)?

**Comment by aastratinei** [comment]
"pretty weather" widget

**Comment by felixhageloh** [comment]
I see! So this one needs to be changed first to be used (to configure the api key) - did you do that?

**Comment by aastratinei** [comment]
Yup. I added an api key and the lat/long

**Comment by TraderStf** [comment]
Try http://www.barebones.com/ free TextWrangler, a very good editor.
The paying version, BBEdit, with more features is really great too.

**Comment by felixhageloh** [comment]
Cool! So you probably did that in TextEdit, which is why the widget breaks. Not your fault - I should add a notice that you can't use TextEdit for widgets, unfortunately

**Comment by aastratinei** [comment]
Ok I deleted that one and tried a different one, the "calendar". I presume you don't have to edit that one so I didn't open it at all. I moved it into the folder, and the same error popped up.

**Comment by aastratinei** [comment]
![screen shot 2015-01-26 at 17 46 13](https://cloud.githubusercontent.com/assets/10710553/5902457/41f5eb50-a583-11e4-90a0-b26f4d88a85f.png)
Maybe this helps... am I putting them in wrong?

**Comment by felixhageloh** [comment]
hmm strange.
You do usually need to drag the entire folder of the widget, but for this one it should be ok (also you would get a different error)
Can you use one of the text editors we mentioned here to open the widget file and post a screenshot here? (BTW i won't be able to respond the next 1h or so)

**Comment by aastratinei** [comment]
Thats cool

Here is the screen shot 
![screen shot 2015-01-26 at 17 51 19](https://cloud.githubusercontent.com/assets/10710553/5902541/00f8be24-a584-11e4-9293-f7e25c02c611.png)
(with sublime text)

**Comment by felixhageloh** [comment]
thanks! Very strange - looks all good. Do you get any errors in the debug console (if so can you post a screenshot as well)?

**Comment by aastratinei** [comment]
My debug console also won't open. I'm going to try reinstalling the app and see if that makes a difference

**Comment by aastratinei** [comment]
I reinstalled everything, debug console still wouldn't open, the 'getting started' widget appeared and as soon as I double clicked the file and opened it with sublime it disappeared from my desk top.

**Comment by aastratinei** [comment]
it's back now somehow... and the debug console as well

**Comment by aastratinei** [comment]
I just installed a widget and everything now works! I honestly don't know what made it happen, but I guess it was reinstalling it? Anyway, thank you so much for all the help, you've been very patient :)

**Comment by felixhageloh** [comment]
No worries, great to hear it is working now :)

**Comment by ChrisEelmaa** [comment]
I had the same issue, I haven't tried again, but these are the steps I used:

1) Downloaded Übersicht into Downloads folder, (13mb application)
2) Run it!
3) Move it to "Applications folder"

Realized nothing worked, checked comments & arrived to github, tried again, but this time:

1) Deleted every trace of Übersicht
2) Moved it into applications folder
3) Run it
4) Works.
