### ISSUE TITLE
"Flicker" on large image refreshes

### ISSUE THREAD

**Issue by majorsl** [felixhageloh/uebersicht#86]
I'm only a dabbler in JS (and now coffee) so it is entirely possible I'm doing something wrong.  Coming from GeekTool, I thought about learning this by duplicating some of my existing Geeklets.

Once of these is a large weather icon. I did a simple widget that grabs the image from URL and refreshes it at a set frequency.  I note when it refreshes, it flickers on my desktop which is a bit distracting. I suspect it is the momentary vanishing before the new image is redrawn.  I think somehow GeekTool did this more smoothly, although I don't know how, maybe doing some pre-caching?

**Comment by soberstadt** [comment]
That would be a really cool widget that I would probably use.

I'd look into using sprite sheets. That way you're just moving one big image around. Or you could load the new image behind the old one and then use css or JS annimation to fade.

Do you have a repo (or gist) for your widget that I could poke around at?

**Comment by felixhageloh** [comment]
In addition to @soberstadt's suggestions some simple tricks could potentially help: 
I'm not sure how you implemented it, but if you use the simplest approach (something like `render: "<img src='...' />"`) you will most likely see a flicker because the image tag is trashed and re-created on every redraw. If you use the `update` method instead, to just change the source of the image I would expect most of the flicker to disappear (let me know if you need a code sample).
To get it super smooth (ubersmooth ;) ), maybe using a fade transitions, you'd have to use Spencer's suggestions tho!

**Comment by majorsl** [comment]
Well, it's so primitive (and so am I with JS) you'll see 100 ways to do it better - probably more ;)

But, I started simple. Background: at work we have a status update that runs against our main services page that is updated about every 5 minutes and gives our users a tactical overview of systems status e.g. is email working? A perfect solution for our Helpdesk techs is to also have this right on their desktops so they can know when taking calls at a glance.

I believe I got rid of the flicker by downloading the image locally and drawing it as a background image and a foreground image when it renders the output. Since it doesn't appear that background img is destroyed and recreated, it masks the effect.

Thank you both for offering your advice, I really appreciate it.
--
command: "curl -s -o status.jpg http://www.example.com/status.jpg"
refreshFrequency: 300000

style: """
  bottom:10px
  right:10px
  width:292px
  height:355px
  background-image: url('status.jpg')
"""

render: (output) -> """
<img src="status.jpg">
"""

**Comment by TraderStf** [comment]
This might perhaps do it, clip area and move it to show the current one.
http://www.w3schools.com/css/css3_2dtransforms.asp
http://www.w3schools.com/cssref/pr_pos_clip.asp
just ideas...
http://www.w3schools.com/css/css3_animations.asp

**Comment by felixhageloh** [comment]
Looks like you already solved your issue, but this could be a slightly nicer solution:

``` coffeescript
command: "curl -s -o status.jpg http://www.example.com/status.jpg"
refreshFrequency: 300000

style: """
  bottom:10px
  right:10px
  width:292px
  height:355px
"""

render: (output) -> """
  <img id="status_image" src="status.jpg"/>
"""

update: ->
  @image ?= document.getElementById('status_image')
  # appending the current time will force the image to reload
  @image.src = "status.jpg?#{new Date().getTime()}" 
```

**Comment by majorsl** [comment]
Ah, I see. I've used the "appending the date/time solution" for some other things in the past.  That's a good way to do this.

I think for the coffee/JS new folks, like me, the more small and simple code samples you could add to the project, the better. It would encourage people to tinker. You could comment up the above and add it as a sample, if you think it is worth it.

Again, thank you!

**Comment by majorsl** [comment]
This is closed.  I'm not doing a weather widget, that might be someone else.  If I do come up with any widget worthy of sharing, I'll definitely do so. Thanks!
