### ISSUE TITLE
Error running command for specific types

### ISSUE THREAD

**Issue by cukal** [felixhageloh/uebersicht#89]
Hi, 

Loving Ubersicht but it seems I am having an issue with some specific commands.
The iostats.widget for instance:

Original code: 

disk = 'disk0'
delay = '5'  #seconds
command: "iostat -dw #{delay} -c 2  #{disk} | awk 'FNR>3' | awk '{printf \"%s,%s,%s\",$1,$2,$3}'"

When I translate that to regular cmd line I get the nice oneliner: iostat -dw 5 -c 2 disk0 | awk 'FNR>3' | awk '{printf \"%s,%s,%s\",$1,$2,$3}.
I can execute it perfectly in a terminal window but when I enable the widget it returns an "error running command" message. Merely changing the command to "echo 7.00,58,0.40" to mimic the output works so there does not seem to be anything wrong with the rest of the script, only the execution of the command which goes wrong.

Another example is the sys-mon-set.widget, it contains netstat.widget which includes a simple netst.c compiled to a binary netst. Again, when I execute it from a terminal shell the command works flawless but inside the index.coffee script as the command: param it returns the same "error running command" when enabled, even copying it to /bin/ and referring to it correctly does not work. Replacing the command in /bin/netst with a simple script that outputs the same values works. 

It seems something goes wrong upon invocation of the command. 
Permissions? Env vars? 

Who knows?

Thanks for any help!

**Comment by cukal** [comment]
I missed that one. You are correct. Updating the refreshFrequency is the trick.
Thanks!

**Comment by felixhageloh** [comment]
np!
