### ISSUE TITLE
Unable to interact with debug console

### ISSUE THREAD

**Issue by whirka** [felixhageloh/uebersicht#90]
After leaving the debug console open for an undetermined amount of time or refreshes the console becomes unresponsive to any interactions. The console remains open and I can see the counters incrementing at the top, but am unable to click on any button.

The only way to make the console responsive again is to go to the tray icon and click on "Show Debug Console" again even though the console is already visible.

**Comment by felixhageloh** [comment]
Have not seen this issue, but the console is definitely a bit unreliable at times (same goes for Safari). Is this on OS X 10.10 or on 10.9?

**Comment by whirka** [comment]
I'm seeing this on 10.10.2

**Comment by fitzagard** [comment]
I've seen this issue. The workaround from @whirka is the only way i've been able to get around it.  I'm on 10.10.2 as well.

**Comment by TheLoverZ** [comment]
I just encountered a bug which cannot open debug console at all, a possible solution is to clear Widget Folder and reopen the app.
