### ISSUE TITLE
Launching Applications

### ISSUE THREAD

**Issue by ddgond** [felixhageloh/uebersicht#91]
I would like to use Übersicht as an alternative application launcher. How would I be able to run a Terminal command such as "open ../../Applications/Google\ Chrome.app/" in response to a button click?

**Comment by soberstadt** [comment]
Very clever idea. Felix, any thoughts?

**Comment by felixhageloh** [comment]
This works :)
```coffeescript
afterRender: (domEl)->
  $(domEl).on 'click', '.map-icon', => @run "open /Applications/Maps.app"
```

**Comment by soberstadt** [comment]
@ddgond, you should share your widget when you get something together!

**Comment by ddgond** [comment]
So far, it works for one element at a time. How would I be able to include two of those commands that go to two different applications?

**Comment by soberstadt** [comment]
Do you mean running two applications with one button
`@run "open /Applications/Maps.app && open /Applications/Mail.app`
 or 
have two buttons each opening different applications?

    $(domEl).on 'click', '.map-icon', => @run "open /Applications/Maps.app"
    $(domEl).on 'click', '.mail-icon', => @run "open /Applications/Mail.app"

**Comment by ddgond** [comment]
That works. I tried it last time with Google Chrome, but forgot to put the path in quotes. I'll post it after I get it configured. Thanks!

**Comment by ddgond** [comment]
Here's the finished widget. Thanks for your help!
https://github.com/ddgond/uebersicht-grid-launcher

**Comment by felixhageloh** [comment]
@ddgond looks great :)! If you want to have it on the widgets gallery, make sure to use the project layout described in the [readme](https://github.com/felixhageloh/uebersicht-widgets#readme) (or see example [here](https://github.com/felixhageloh/pretty-weather)).

**Comment by felixhageloh** [comment]
basically the widget needs a zip file so that users can download it and some other things need to be in place because we are using an automatic build script for the widget gallery

**Comment by mischievous** [comment]
My clicks are not working.  Any suggestions?

**Comment by felixhageloh** [comment]
@mischievous make sure you have an interaction shortcut key configured in preferences!

**Comment by blahsd** [comment]
Hi! I'm making a sort of task manager. 
I'm trying to have procedurally generated elements clickable, but I need to pass as an argument that object which has been clicked. Something like this:
`afterRender: (domEl) ->
  $(domEl).on 'click', ".button", =>  $(domEl).find([THAT BUTTON WHICH HAS BEEN CLICKED]).addClass("clicked")`

Since the script generates a button for each running application, I don't know in advance the id that they will have, so I can't pass that to $(domEl).find. Is there a way to do this?
