### ISSUE TITLE
Command called twice each refresh

### ISSUE THREAD

**Issue by farski** [felixhageloh/uebersicht#93]
I rewrote a few widgets that use Forecast.io to take advantage of geolocation. Since then, the number of daily requests I'm making to the API have gone way up. Initially it was because I was calling `@refresh()` on all location changes, which turns out to be thousands throughout the day, even if the computer doesn't move. Since dealing with that, though, I'm still seeing an issue where every refresh cycle, the API is getting hit twice. The `refreshFrequency` is set to 10 minutes, and every 10 minutes I see the API get hit six times (there are three separate widgets).

I am calling `@refresh()` in `afterRender`, but my understanding was that should only get called once ever per widget. Logging makes it seem like that _is_ only being called once, and I've even added a flag to make sure it only gets called once, but I'm still seeing the additional request to the API.

Does this seem like something wrong on my end?

**Comment by felixhageloh** [comment]
Are you using `getCurrentPosition` for this? If so, then I'll need to double check that the callback only get's called once.

**Comment by farski** [comment]
@felixhageloh I am using `getCurrentPosition`, but I don't call @refresh() in the callback, so I wouldn't think that should change how often the command is getting called.

Here's the whole widget: https://gist.github.com/farski/a9d5f404cd1e875d3180

**Comment by felixhageloh** [comment]
from what I can tell so far, the widget looks fine and it should run the command (i.e. hit the forecast API) once per refresh cycle. Do you see this `console.log "UPDATE: simple-weather #{new Date()}"` being logged only once per refresh cycle?

**Comment by felixhageloh** [comment]
btw, slightly different topic, but from what I understand it is not the best to call `watchPosition` like that. You can either use it to get a super accurate position (watch it till the accuracy is hight enough, then stop)  or in a scenario where you really need to update the current position every second or so (like a navigation app). There is an api for listening only to significant location changes, which is better for your battery and probably also what you have in mind. However, I have not seen this exposed in the standard HTML5 geolocation api (which doesn't keep us from implementing it for Übersicht of course :) ).
Again, this is assuming that I understood the HTML5 geolocation specs correctly :)

**Comment by farski** [comment]
I'm seeing that get logged twice https://gist.github.com/farski/074137a46f47b3cad0e7, and if I watch the API requests in real time I see the counter go up two times, so it's not just the `update()` getting called twice.

I'll rethink how I'm using `watchPosition`, At one point I was trying to just periodically hit `getCurrentPosition`, but I think because I was seeing the multiple requests from this (potential) bug, I mistakenly thought `getCurrentPosition` was causing the extra calls. I was going through a lot of iterations trying to get things working, so I didn't actually do a good job isolating problems.

**Comment by felixhageloh** [comment]
very late response, but I believe this has been fixed in 0.7.24
