### ISSUE TITLE
Allow specifying refreshFrequency as a string

### ISSUE THREAD

**Issue by hawkrives** [felixhageloh/uebersicht#94]
For instance, `"1 hour"` or `"1 second"`, or even `"1 min"`.

I keep having to calculate the number of milliseconds in some time period, and then I can never remember how long of a duration I've specified in the future.

I suppose that the second bit could be simplified by me adding a comment to the line, but would you be opposed to a PR that added support for english time spans?

**Comment by farski** [comment]
This seems like unnecessary complexity at the app level. Probably a better solution would be something like

```
HOUR = (60 * 60 * 1000)
refreshFrequency: 2 * HOUR
```

**Comment by felixhageloh** [comment]
I can see both points I guess. I'm all for keeping the app as simple as possible, but I also realise that it is an app for people to have some fun to hack around with. So if it makes that easier and the solution doesn't add too much complexity (i.e. is nice and self contained) I'm open to a pull req

**Comment by hawkrives** [comment]
@felixhageloh Would you be opposed to including a new package from npm to handle this? 

I just found https://www.npmjs.com/package/ms, which is pretty much what I was imagining when I filed this issue.

**Comment by felixhageloh** [comment]
No think that sounds good!
