### ISSUE TITLE
localStorage does not persist

### ISSUE THREAD

**Issue by drewvolz** [felixhageloh/uebersicht#95]
For instance, if I quit Übersicht and launch it again, any stored values will have been wiped.

According to [MDN's DOM Storage guide](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#localStorage), localStorage is described as having "same same-origin rules" applied (much like sessionStorage), but is persistent.

**Comment by felixhageloh** [comment]
That should not be the case - I'll have a look to see what's happening!

**Comment by macjools** [comment]
Has there been any progress on this issue?

**Comment by felixhageloh** [comment]
It turns out it needs to be explicitly enabled. Ideally I would like to upgrade to the newest version of WebView first (and make sure it works there) tho

**Comment by felixhageloh** [comment]
This has been fixed in version 1.0.42 released today
