### ISSUE TITLE
Error Message when installing into 10.10.2

### ISSUE THREAD

**Issue by Lammy-Lam** [felixhageloh/uebersicht#98]
Error message when installing index.coffee into 10.10.2
no edits, nothing changed.
This use to work on my last laptop with an older version of OSX. This error occurs on every widget I tried to install.

![image](https://cloud.githubusercontent.com/assets/11843105/7034196/ae0c1272-dd34-11e4-9f8c-e7ebe0eb819b.png)

**Comment by felixhageloh** [comment]
did you figure this one out?

**Comment by Lammy-Lam** [comment]
Yes. I renamed Uebersicht by removing the ü and worked perfect. Thanks. 

Sandra Winn
